INSERT INTO careers (name,degree_id) VALUES ('Actuaria',3);
INSERT INTO careers (name,degree_id) VALUES ('Administración',3);
INSERT INTO careers (name,degree_id) VALUES ('Arquitectura del Paisaje',3);
INSERT INTO careers (name,degree_id) VALUES ('Arquitectura',3);
INSERT INTO careers (name,degree_id) VALUES ('Artes Visuales',3);
INSERT INTO careers (name,degree_id) VALUES ('Bibliotecología',3);
INSERT INTO careers (name,degree_id) VALUES ('Biología',3);
INSERT INTO careers (name,degree_id) VALUES ('Canto',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias Políticas y Administración Pública - Opción Administración Pública',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias de la Computación',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias de la Comunicación',3);
INSERT INTO careers (name,degree_id) VALUES ('Cirujano Dentista (Odontología)',3);
INSERT INTO careers (name,degree_id) VALUES ('Composición',3);
INSERT INTO careers (name,degree_id) VALUES ('Comunicación Gráfica',3);
INSERT INTO careers (name,degree_id) VALUES ('Contaduría',3);
INSERT INTO careers (name,degree_id) VALUES ('Derecho',3);
INSERT INTO careers (name,degree_id) VALUES ('Diseño Gráfico',3);
INSERT INTO careers (name,degree_id) VALUES ('Diseño Industrial',3);
INSERT INTO careers (name,degree_id) VALUES ('Economía',3);
INSERT INTO careers (name,degree_id) VALUES ('Educación Musical',3);
INSERT INTO careers (name,degree_id) VALUES ('Enfermería y Obstetricia',3);
INSERT INTO careers (name,degree_id) VALUES ('Enseñanza del Inglés',3);
INSERT INTO careers (name,degree_id) VALUES ('Estudios Latinomericanos',3);
INSERT INTO careers (name,degree_id) VALUES ('Etnomusicología',3);
INSERT INTO careers (name,degree_id) VALUES ('Filosofía',3);
INSERT INTO careers (name,degree_id) VALUES ('Física',3);
INSERT INTO careers (name,degree_id) VALUES ('Geografía',3);
INSERT INTO careers (name,degree_id) VALUES ('Historia',3);
INSERT INTO careers (name,degree_id) VALUES ('Informática',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Agrícola',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Civil',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Eléctrica y Electrónica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Geofísica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Geológica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Industrial',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Mecánica Eléctrica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Mecánica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Petrolera',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Química Metalúrgica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Química',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Topográfica y Geodésica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería de Minas y Metalurgía',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería en Alimentos',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería en Computación',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería en Telecomunicaciones',3);
INSERT INTO careers (name,degree_id) VALUES ('Instrumentista',3);
INSERT INTO careers (name,degree_id) VALUES ('Investigación Biomédica Básica',3);
INSERT INTO careers (name,degree_id) VALUES ('Lengua y Literaturas Hispánicas',3);
INSERT INTO careers (name,degree_id) VALUES ('Lengua y Literaturas Modernas',3);
INSERT INTO careers (name,degree_id) VALUES ('Letras Clásicas',3);
INSERT INTO careers (name,degree_id) VALUES ('Literatura Dramática y Teatro',3);
INSERT INTO careers (name,degree_id) VALUES ('Matemáticas Aplicadas y Computación',3);
INSERT INTO careers (name,degree_id) VALUES ('Matemáticas',3);
INSERT INTO careers (name,degree_id) VALUES ('Medicina Veterinaria y Zootecnia',3);
INSERT INTO careers (name,degree_id) VALUES ('Medicina',3);
INSERT INTO careers (name,degree_id) VALUES ('Optometría',3);
INSERT INTO careers (name,degree_id) VALUES ('Pedagogía',3);
INSERT INTO careers (name,degree_id) VALUES ('Periodismo y Comunicación Colectiva',3);
INSERT INTO careers (name,degree_id) VALUES ('Piano',3);
INSERT INTO careers (name,degree_id) VALUES ('Planificación para el Desarrollo Agropecuario',3);
INSERT INTO careers (name,degree_id) VALUES ('Psicología',3);
INSERT INTO careers (name,degree_id) VALUES ('Química Farmacéutico Biológica',3);
INSERT INTO careers (name,degree_id) VALUES ('Química Industrial',3);
INSERT INTO careers (name,degree_id) VALUES ('Química de Alimentos',3);
INSERT INTO careers (name,degree_id) VALUES ('Química',3);
INSERT INTO careers (name,degree_id) VALUES ('Relaciones Internacionales',3);
INSERT INTO careers (name,degree_id) VALUES ('Sociología',3);
INSERT INTO careers (name,degree_id) VALUES ('Trabajo Social',3);
INSERT INTO careers (name,degree_id) VALUES ('Urbanismo',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias Políticas y Administración Pública - Opción Ciencia Política',3);      
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Antropología', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias de la Administración', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Derecho', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Economía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Geografía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Pedagogía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Psicología', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Arquitectura', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Urbanismo', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Bibliotecología y Estudios de la Información,', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencxias e Ingeniería de Materiales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias (Astronomía)', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Biológicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Bioquímicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias de la producción y salud animal', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias de la Tierra', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Matemáticas y de la Especialización en Estadística Aplicada', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría eb Ciencias del Mar y Limnología', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencia e In genriería de la Computación', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Físicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Médicas Odontológicas y de la Salud', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Químicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios Mesoamericanos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Filosofía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Filosofía de la Ciencia', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Historia', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestrá en Historia del Arte', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ingeniería', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Letras', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Lingüística', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Música', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Artes Visuales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias (Neurobiología)', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Diseño Industrial', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Enfermería', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios Políticos y Sociales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Gobierno y Asuntos Públicos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Comunicación', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios en Relaciones Internacionales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios México-Estados Unidos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios Latinoamericanos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Docencia para la Educación Media Superior', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Trabajo Social', 5);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Antropología', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias de la Administración', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Derecho', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Pedagogía', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Economía', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Arquitectura', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Urbanismo', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Bibliotecología y Estudios de la Información', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias e Ingeniería de Materiales', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias (Astronomía)', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Biológicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Bioquímicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias de la producción y salud animal', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias de la Tierra', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Matemáticas y de la Especialización en Estadística Aplicada', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias del Mar y Limnología', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencia e In genriería de la Computación', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Físicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Médicas Odontológicas y de la Salud', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Químicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Estudios Mesoamericanos', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Filosofía', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Filosofía de la Ciencia', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Historia', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ingeniería', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Letras', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Lingüística', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Música', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Biomédicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Ciencia Política', 6);
INSERT INTO careers (name,degree_id) VALUES ('Sociología', 6);
INSERT INTO careers (name,degree_id) VALUES ('Administración Pública', 6);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias de la Comunicación', 6);
INSERT INTO careers (name,degree_id) VALUES ('Relaciones Internacionales', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Estudios Latinoamericanos', 6);
