INSERT INTO careers (name) VALUES ('Actuaria');
INSERT INTO careers (name) VALUES ('Administración');
INSERT INTO careers (name) VALUES ('Arquitectura del Paisaje');
INSERT INTO careers (name) VALUES ('Arquitectura');
INSERT INTO careers (name) VALUES ('Artes Visuales');
INSERT INTO careers (name) VALUES ('Bibliotecología');
INSERT INTO careers (name) VALUES ('Biología');
INSERT INTO careers (name) VALUES ('Canto');
INSERT INTO careers (name) VALUES ('Ciencias Políticas y Administración Pública');
INSERT INTO careers (name) VALUES ('Ciencias de la Computación');
INSERT INTO careers (name) VALUES ('Ciencias de la Comunicación');
INSERT INTO careers (name) VALUES ('Cirujano Dentista (Odontología)');
INSERT INTO careers (name) VALUES ('Composición');
INSERT INTO careers (name) VALUES ('Comunicación Gráfica');
INSERT INTO careers (name) VALUES ('Contaduría');
INSERT INTO careers (name) VALUES ('Derecho');
INSERT INTO careers (name) VALUES ('Diseño Gráfico');
INSERT INTO careers (name) VALUES ('Diseño Industrial');
INSERT INTO careers (name) VALUES ('Economía');
INSERT INTO careers (name) VALUES ('Educación Musical');
INSERT INTO careers (name) VALUES ('Enfermería y Obstetricia');
INSERT INTO careers (name) VALUES ('Enseñanza del Inglés');
INSERT INTO careers (name) VALUES ('Estudios Latinomericanos');
INSERT INTO careers (name) VALUES ('Etnomusicología');
INSERT INTO careers (name) VALUES ('Filosofía');
INSERT INTO careers (name) VALUES ('Física');
INSERT INTO careers (name) VALUES ('Geografía');
INSERT INTO careers (name) VALUES ('Historia');
INSERT INTO careers (name) VALUES ('Informática');
INSERT INTO careers (name) VALUES ('Ingeniería Agrícola');
INSERT INTO careers (name) VALUES ('Ingeniería Civil');
INSERT INTO careers (name) VALUES ('Ingeniería Eléctrica y Electrónica');
INSERT INTO careers (name) VALUES ('Ingeniería Geofísica');
INSERT INTO careers (name) VALUES ('Ingeniería Geológica');
INSERT INTO careers (name) VALUES ('Ingeniería Industrial');
INSERT INTO careers (name) VALUES ('Ingeniería Mecánica Eléctrica');
INSERT INTO careers (name) VALUES ('Ingeniería Mecánica');
INSERT INTO careers (name) VALUES ('Ingeniería Petrolera');
INSERT INTO careers (name) VALUES ('Ingeniería Química Metalúrgica');
INSERT INTO careers (name) VALUES ('Ingeniería Química');
INSERT INTO careers (name) VALUES ('Ingeniería Topográfica y Geodésica');
INSERT INTO careers (name) VALUES ('Ingeniería de Minas y Metalurgía');
INSERT INTO careers (name) VALUES ('Ingeniería en Alimentos');
INSERT INTO careers (name) VALUES ('Ingeniería en Computación');
INSERT INTO careers (name) VALUES ('Ingeniería en Telecomunicaciones');
INSERT INTO careers (name) VALUES ('Instrumentista');
INSERT INTO careers (name) VALUES ('Investigación Biomédica Básica');
INSERT INTO careers (name) VALUES ('Lengua y Literaturas Hispánicas');
INSERT INTO careers (name) VALUES ('Lengua y Literaturas Modernas');
INSERT INTO careers (name) VALUES ('Letras Clásicas');
INSERT INTO careers (name) VALUES ('Literatura Dramática y Teatro');
INSERT INTO careers (name) VALUES ('Matemáticas Aplicadas y Computación');
INSERT INTO careers (name) VALUES ('Matemáticas');
INSERT INTO careers (name) VALUES ('Medicina Veterinaria y Zootecnia');
INSERT INTO careers (name) VALUES ('Medicina');
INSERT INTO careers (name) VALUES ('Optometría');
INSERT INTO careers (name) VALUES ('Pedagogía');
INSERT INTO careers (name) VALUES ('Periodismo y Comunicación Colectiva');
INSERT INTO careers (name) VALUES ('Piano');
INSERT INTO careers (name) VALUES ('Planificación para el Desarrollo Agropecuario');
INSERT INTO careers (name) VALUES ('Psicología');
INSERT INTO careers (name) VALUES ('Química Farmacéutico Biológica');
INSERT INTO careers (name) VALUES ('Química Industrial');
INSERT INTO careers (name) VALUES ('Química de Alimentos');
INSERT INTO careers (name) VALUES ('Química');
INSERT INTO careers (name) VALUES ('Relaciones Internacionales');
INSERT INTO careers (name) VALUES ('Sociología');
INSERT INTO careers (name) VALUES ('Trabajo Social');
INSERT INTO careers (name) VALUES ('Urbanismo');
