INSERT INTO cities (state_id, name) VALUES (1, 'AGUASCALIENTES');
INSERT INTO cities (state_id, name) VALUES (1, 'CALVILLO');
INSERT INTO cities (state_id, name) VALUES (1, 'PABELLON DE ARTEAGA');
INSERT INTO cities (state_id, name) VALUES (1, 'RINCON DE ROMOS');
INSERT INTO cities (state_id, name) VALUES (2, 'ENSENADA');
INSERT INTO cities (state_id, name) VALUES (2, 'GUADALUPE VICTORIA (KM. 43)');
INSERT INTO cities (state_id, name) VALUES (2, 'MEXICALI');
INSERT INTO cities (state_id, name) VALUES (2, 'RODOLFO SANCHEZ T. (MANEADERO)');
INSERT INTO cities (state_id, name) VALUES (2, 'SANTA ISABEL');
INSERT INTO cities (state_id, name) VALUES (2, 'TECATE');
INSERT INTO cities (state_id, name) VALUES (2, 'TIJUANA');
INSERT INTO cities (state_id, name) VALUES (3, 'CABO SAN LUCAS');
INSERT INTO cities (state_id, name) VALUES (3, 'CIUDAD CONSTITUCION');
INSERT INTO cities (state_id, name) VALUES (3, 'LA PAZ');
INSERT INTO cities (state_id, name) VALUES (3, 'SAN JOSE DEL CABO');
INSERT INTO cities (state_id, name) VALUES (4, 'CAMPECHE');
INSERT INTO cities (state_id, name) VALUES (4, 'CHAMPOTON');
INSERT INTO cities (state_id, name) VALUES (4, 'CIUDAD DEL CARMEN');
INSERT INTO cities (state_id, name) VALUES (4, 'ESCARCEGA');
INSERT INTO cities (state_id, name) VALUES (5, 'ARRIAGA');
INSERT INTO cities (state_id, name) VALUES (5, 'BERRIOZABAL');
INSERT INTO cities (state_id, name) VALUES (5, 'CINTALAPA DE FIGUEROA');
INSERT INTO cities (state_id, name) VALUES (5, 'COMITAN DE DOMINGUEZ');
INSERT INTO cities (state_id, name) VALUES (5, 'HUIXTLA');
INSERT INTO cities (state_id, name) VALUES (5, 'LAS ROSAS');
INSERT INTO cities (state_id, name) VALUES (5, 'MOTOZINTLA DE MENDOZA');
INSERT INTO cities (state_id, name) VALUES (5, 'OCOSINGO');
INSERT INTO cities (state_id, name) VALUES (5, 'OCOZOCOAUTLA DE ESPINOSA');
INSERT INTO cities (state_id, name) VALUES (5, 'PALENQUE');
INSERT INTO cities (state_id, name) VALUES (5, 'REFORMA');
INSERT INTO cities (state_id, name) VALUES (5, 'SAN CRISTOBAL DE LAS CASAS');
INSERT INTO cities (state_id, name) VALUES (5, 'TAPACHULA DE CORDOVA Y ORDOÑEZ');
INSERT INTO cities (state_id, name) VALUES (5, 'TONALA');
INSERT INTO cities (state_id, name) VALUES (5, 'TUXTLA GUTIÉRREZ');
INSERT INTO cities (state_id, name) VALUES (5, 'VILLAFLORES');
INSERT INTO cities (state_id, name) VALUES (6, 'CHIHUAHUA');
INSERT INTO cities (state_id, name) VALUES (6, 'CUAUHTEMOC');
INSERT INTO cities (state_id, name) VALUES (6, 'DELICIAS');
INSERT INTO cities (state_id, name) VALUES (6, 'HIDALGO DEL PARRAL');
INSERT INTO cities (state_id, name) VALUES (6, 'JOSE MARIANO JIMENEZ');
INSERT INTO cities (state_id, name) VALUES (6, 'JUAN ALDAMA');
INSERT INTO cities (state_id, name) VALUES (6, 'JUAREZ');
INSERT INTO cities (state_id, name) VALUES (6, 'MANUEL OJINAGA');
INSERT INTO cities (state_id, name) VALUES (6, 'NUEVO CASAS GRANDES');
INSERT INTO cities (state_id, name) VALUES (6, 'PEDRO MEOQUI');
INSERT INTO cities (state_id, name) VALUES (6, 'SANTA ROSALIA DE CAMARGO');
INSERT INTO cities (state_id, name) VALUES (7, 'ALLENDE');
INSERT INTO cities (state_id, name) VALUES (7, 'CIUDAD ACUÑA');
INSERT INTO cities (state_id, name) VALUES (7, 'CIUDAD MELCHOR MUZQUIZ');
INSERT INTO cities (state_id, name) VALUES (7, 'FRANCISCO I. MADERO');
INSERT INTO cities (state_id, name) VALUES (7, 'MONCLOVA');
INSERT INTO cities (state_id, name) VALUES (7, 'NUEVA ROSITA - CLOETE');
INSERT INTO cities (state_id, name) VALUES (7, 'PALAU');
INSERT INTO cities (state_id, name) VALUES (7, 'PARRAS DE LA FUENTE');
INSERT INTO cities (state_id, name) VALUES (7, 'PIEDRAS NEGRAS');
INSERT INTO cities (state_id, name) VALUES (7, 'SABINAS');
INSERT INTO cities (state_id, name) VALUES (7, 'SALTILLO');
INSERT INTO cities (state_id, name) VALUES (7, 'SAN BUENAVENTURA');
INSERT INTO cities (state_id, name) VALUES (7, 'SAN PEDRO');
INSERT INTO cities (state_id, name) VALUES (7, 'TORREÓN');
INSERT INTO cities (state_id, name) VALUES (8, 'COLIMA');
INSERT INTO cities (state_id, name) VALUES (8, 'MANZANILLO');
INSERT INTO cities (state_id, name) VALUES (8, 'TECOMAN - ARMERIA');
INSERT INTO cities (state_id, name) VALUES (9, 'CIUDAD DE MÉXICO');
INSERT INTO cities (state_id, name) VALUES (10, 'EL SALTO');
INSERT INTO cities (state_id, name) VALUES (10, 'SANTIAGO PAPASQUIARO');
INSERT INTO cities (state_id, name) VALUES (10, 'VICTORIA DE DURANGO');
INSERT INTO cities (state_id, name) VALUES (11, 'AMECAMECA DE JUAREZ');
INSERT INTO cities (state_id, name) VALUES (11, 'ATLACOMULCO - TECOAC');
INSERT INTO cities (state_id, name) VALUES (11, 'CAPULHUAC - SANTIAGO TIANGUISTENCO');
INSERT INTO cities (state_id, name) VALUES (11, 'IXTAPAN DE LA SAL');
INSERT INTO cities (state_id, name) VALUES (11, 'LOS BAÑOS');
INSERT INTO cities (state_id, name) VALUES (11, 'OCOYOACAC');
INSERT INTO cities (state_id, name) VALUES (11, 'OZUMBA');
INSERT INTO cities (state_id, name) VALUES (11, 'SAN BARTOLO DEL LLANO - SANTA CRUZ TEPEXPAN');
INSERT INTO cities (state_id, name) VALUES (11, 'SANTO DOMINGO');
INSERT INTO cities (state_id, name) VALUES (11, 'TEJUPILCO DE HIDALGO');
INSERT INTO cities (state_id, name) VALUES (11, 'TEMASCALCINGO - LA MAGDALENA');
INSERT INTO cities (state_id, name) VALUES (11, 'TENANCINGO DE DEGOLLADO');
INSERT INTO cities (state_id, name) VALUES (11, 'TENANGO - SATIAGUITO');
INSERT INTO cities (state_id, name) VALUES (11, 'TEQUIXQUIAC');
INSERT INTO cities (state_id, name) VALUES (11, 'TOLUCA');
INSERT INTO cities (state_id, name) VALUES (11, 'VALLE DE BRAVO');
INSERT INTO cities (state_id, name) VALUES (11, 'VILLA CUAUHTEMOC');
INSERT INTO cities (state_id, name) VALUES (11, 'XALATLACO - SANTIAGO TILAPA');
INSERT INTO cities (state_id, name) VALUES (12, 'ABASOLO');
INSERT INTO cities (state_id, name) VALUES (12, 'ACAMBARO');
INSERT INTO cities (state_id, name) VALUES (12, 'APASEO EL ALTO');
INSERT INTO cities (state_id, name) VALUES (12, 'APASEO EL GRANDE');
INSERT INTO cities (state_id, name) VALUES (12, 'CELAYA');
INSERT INTO cities (state_id, name) VALUES (12, 'CENTRO FAMILIAR LA SOLEDAD');
INSERT INTO cities (state_id, name) VALUES (12, 'COMONFORT');
INSERT INTO cities (state_id, name) VALUES (12, 'CORTAZAR');
INSERT INTO cities (state_id, name) VALUES (12, 'DOLORES HIDALGO CUNA DE LA INDEP. NAL.');
INSERT INTO cities (state_id, name) VALUES (12, 'GUANAJUATO');
INSERT INTO cities (state_id, name) VALUES (12, 'IRAPUATO');
INSERT INTO cities (state_id, name) VALUES (12, 'JARAL DEL PROGRESO');
INSERT INTO cities (state_id, name) VALUES (12, 'JUVENTINO ROSAS');
INSERT INTO cities (state_id, name) VALUES (12, 'LEON');
INSERT INTO cities (state_id, name) VALUES (12, 'MOROLEÓN - URIANGATO');
INSERT INTO cities (state_id, name) VALUES (12, 'PENJAMO');
INSERT INTO cities (state_id, name) VALUES (12, 'ROMITA');
INSERT INTO cities (state_id, name) VALUES (12, 'SALAMANCA');
INSERT INTO cities (state_id, name) VALUES (12, 'SALVATIERRA');
INSERT INTO cities (state_id, name) VALUES (12, 'SAN FELIPE');
INSERT INTO cities (state_id, name) VALUES (12, 'SAN FRANCISCO - PURÍSIMA');
INSERT INTO cities (state_id, name) VALUES (12, 'SAN LUIS DE LA PAZ');
INSERT INTO cities (state_id, name) VALUES (12, 'SAN MIGUEL DE ALLENDE');
INSERT INTO cities (state_id, name) VALUES (12, 'SILAO');
INSERT INTO cities (state_id, name) VALUES (12, 'VALLE DE SANTIAGO');
INSERT INTO cities (state_id, name) VALUES (12, 'VILLAGRAN');
INSERT INTO cities (state_id, name) VALUES (12, 'YURIRIA');
INSERT INTO cities (state_id, name) VALUES (13, 'ACAPULCO DE JUAREZ');
INSERT INTO cities (state_id, name) VALUES (13, 'ARCELIA');
INSERT INTO cities (state_id, name) VALUES (13, 'ATOYAC DE ALVAREZ');
INSERT INTO cities (state_id, name) VALUES (13, 'CHILAPA DE ALVAREZ');
INSERT INTO cities (state_id, name) VALUES (13, 'CHILPANCINGO DE LOS BRAVO');
INSERT INTO cities (state_id, name) VALUES (13, 'CIUDAD ALTAMIRANO - RIVA PALACIO');
INSERT INTO cities (state_id, name) VALUES (13, 'CIUDAD DE HUITZUCO');
INSERT INTO cities (state_id, name) VALUES (13, 'IGUALA DE LA INDEPENDENCIA');
INSERT INTO cities (state_id, name) VALUES (13, 'OMETEPEC');
INSERT INTO cities (state_id, name) VALUES (13, 'PETATLAN');
INSERT INTO cities (state_id, name) VALUES (13, 'SAN JOSE ITURBIDE');
INSERT INTO cities (state_id, name) VALUES (13, 'TAXCO DE ALARCON');
INSERT INTO cities (state_id, name) VALUES (13, 'TECPAN DE GALEANA - EL SUCHIL');
INSERT INTO cities (state_id, name) VALUES (13, 'TELOLOAPAN');
INSERT INTO cities (state_id, name) VALUES (13, 'TIXTLA DE GUERRERO');
INSERT INTO cities (state_id, name) VALUES (13, 'TLAPA DE COMONFORT');
INSERT INTO cities (state_id, name) VALUES (13, 'TULANCINGO');
INSERT INTO cities (state_id, name) VALUES (13, 'ZIHUATANEJO');
INSERT INTO cities (state_id, name) VALUES (13, 'ZUMPANGO DEL RIO');
INSERT INTO cities (state_id, name) VALUES (14, 'ACTOPAN');
INSERT INTO cities (state_id, name) VALUES (14, 'APAN');
INSERT INTO cities (state_id, name) VALUES (14, 'CIUDAD SAHAGUN');
INSERT INTO cities (state_id, name) VALUES (14, 'HUEJUTLA');
INSERT INTO cities (state_id, name) VALUES (14, 'IXMIQUILPAN');
INSERT INTO cities (state_id, name) VALUES (14, 'MIXQUIAHUALA - PROGRESO');
INSERT INTO cities (state_id, name) VALUES (14, 'PACHUCA');
INSERT INTO cities (state_id, name) VALUES (14, 'TEPEJI DE OCAMPO');
INSERT INTO cities (state_id, name) VALUES (14, 'TEZONTEPEC DE ALDAMA');
INSERT INTO cities (state_id, name) VALUES (14, 'TLAXCOAPAN');
INSERT INTO cities (state_id, name) VALUES (14, 'TULA');
INSERT INTO cities (state_id, name) VALUES (14, 'ZACUALTIPAN');
INSERT INTO cities (state_id, name) VALUES (15, 'AMECA');
INSERT INTO cities (state_id, name) VALUES (15, 'ARANDAS');
INSERT INTO cities (state_id, name) VALUES (15, 'ATOTONILCO EL ALTO');
INSERT INTO cities (state_id, name) VALUES (15, 'AUTLAN DE NAVARRO');
INSERT INTO cities (state_id, name) VALUES (15, 'CHAPALA');
INSERT INTO cities (state_id, name) VALUES (15, 'CIHUATLAN');
INSERT INTO cities (state_id, name) VALUES (15, 'CIUDAD GUZMAN');
INSERT INTO cities (state_id, name) VALUES (15, 'EL GRULLO');
INSERT INTO cities (state_id, name) VALUES (15, 'ENCARNACION DE DIAZ');
INSERT INTO cities (state_id, name) VALUES (15, 'GUADALAJARA');
INSERT INTO cities (state_id, name) VALUES (15, 'IXTAPA');
INSERT INTO cities (state_id, name) VALUES (15, 'JALOSTOTITLAN');
INSERT INTO cities (state_id, name) VALUES (15, 'JAMAY');
INSERT INTO cities (state_id, name) VALUES (15, 'JOCOTEPEC');
INSERT INTO cities (state_id, name) VALUES (15, 'LA BARCA');
INSERT INTO cities (state_id, name) VALUES (15, 'LAGOS DE MORENO');
INSERT INTO cities (state_id, name) VALUES (15, 'OCOTLÁN');
INSERT INTO cities (state_id, name) VALUES (15, 'PUERTO VALLARTA');
INSERT INTO cities (state_id, name) VALUES (15, 'SAN JUAN DE LOS LAGOS');
INSERT INTO cities (state_id, name) VALUES (15, 'SAN MIGUEL EL ALTO');
INSERT INTO cities (state_id, name) VALUES (15, 'SAYULA');
INSERT INTO cities (state_id, name) VALUES (15, 'TALA');
INSERT INTO cities (state_id, name) VALUES (15, 'TAMAZULA DE GORDIANO');
INSERT INTO cities (state_id, name) VALUES (15, 'TEOCALTICHE');
INSERT INTO cities (state_id, name) VALUES (15, 'TEPATITLAN DE MORELOS');
INSERT INTO cities (state_id, name) VALUES (15, 'TEQUILA');
INSERT INTO cities (state_id, name) VALUES (15, 'TUXPAN');
INSERT INTO cities (state_id, name) VALUES (15, 'ZACOALCO DE TORRES');
INSERT INTO cities (state_id, name) VALUES (15, 'ZAPOTILTIC');
INSERT INTO cities (state_id, name) VALUES (15, 'ZAPOTLANEJO');
INSERT INTO cities (state_id, name) VALUES (16, 'APATZINGAN DE LA CONSTITUCION');
INSERT INTO cities (state_id, name) VALUES (16, 'CIUDAD HIDALGO');
INSERT INTO cities (state_id, name) VALUES (16, 'HUETAMO DE NUÑEZ');
INSERT INTO cities (state_id, name) VALUES (16, 'JIQUILPAN DE JUAREZ');
INSERT INTO cities (state_id, name) VALUES (16, 'LA PIEDAD - SANTA ANA PACUECO');
INSERT INTO cities (state_id, name) VALUES (16, 'LAZARO CARDENAS');
INSERT INTO cities (state_id, name) VALUES (16, 'LOS REYES DE SALGADO');
INSERT INTO cities (state_id, name) VALUES (16, 'MARAVATIO DE OCAMPO');
INSERT INTO cities (state_id, name) VALUES (16, 'MORELIA');
INSERT INTO cities (state_id, name) VALUES (16, 'NUEVA ITALIA DE RUIZ');
INSERT INTO cities (state_id, name) VALUES (16, 'PARACHO DE VERDUZCO');
INSERT INTO cities (state_id, name) VALUES (16, 'PATZCUARO');
INSERT INTO cities (state_id, name) VALUES (16, 'PURUANDIRO');
INSERT INTO cities (state_id, name) VALUES (16, 'SAHUAYO DE MORELOS');
INSERT INTO cities (state_id, name) VALUES (16, 'TACAMBARO DE CODALLOS');
INSERT INTO cities (state_id, name) VALUES (16, 'URUAPAN');
INSERT INTO cities (state_id, name) VALUES (16, 'YURECUARO');
INSERT INTO cities (state_id, name) VALUES (16, 'ZACAPU');
INSERT INTO cities (state_id, name) VALUES (16, 'ZAMORA');
INSERT INTO cities (state_id, name) VALUES (16, 'ZINAPECUARO - BOCANEO');
INSERT INTO cities (state_id, name) VALUES (16, 'ZITACUARO');
INSERT INTO cities (state_id, name) VALUES (17, 'AXOCHIAPAN');
INSERT INTO cities (state_id, name) VALUES (17, 'CUAUTLA');
INSERT INTO cities (state_id, name) VALUES (17, 'CUERNAVACA');
INSERT INTO cities (state_id, name) VALUES (17, 'JOJUTLA - TLAQUILTENANGO');
INSERT INTO cities (state_id, name) VALUES (17, 'PUENTE DE IXTLA');
INSERT INTO cities (state_id, name) VALUES (17, 'XOXOCOTLA');
INSERT INTO cities (state_id, name) VALUES (17, 'ZACATEPEC - SANTA ROSA');
INSERT INTO cities (state_id, name) VALUES (18, 'ACAPONETA');
INSERT INTO cities (state_id, name) VALUES (18, 'COMPOSTELA');
INSERT INTO cities (state_id, name) VALUES (18, 'IXTLAN DEL RIO');
INSERT INTO cities (state_id, name) VALUES (18, 'SANTIAGO IXCUINTLA');
INSERT INTO cities (state_id, name) VALUES (18, 'TEPIC');
INSERT INTO cities (state_id, name) VALUES (18, 'TUXPAN  (Nayarit)');
INSERT INTO cities (state_id, name) VALUES (19, 'ANAHUAC');
INSERT INTO cities (state_id, name) VALUES (19, 'CADEREYTA JIMENEZ');
INSERT INTO cities (state_id, name) VALUES (19, 'CIUDAD DE ALLENDE');
INSERT INTO cities (state_id, name) VALUES (19, 'CIUDAD SABINAS HIDALGO');
INSERT INTO cities (state_id, name) VALUES (19, 'LINARES');
INSERT INTO cities (state_id, name) VALUES (19, 'MONTEMORELOS');
INSERT INTO cities (state_id, name) VALUES (19, 'MONTERREY');
INSERT INTO cities (state_id, name) VALUES (20, 'CIUDAD IXTEPEC');
INSERT INTO cities (state_id, name) VALUES (20, 'HEROICA CIUDAD DE HUAJUAPAN DE LEON');
INSERT INTO cities (state_id, name) VALUES (20, 'JUCHITAN DE ZARAGOZA');
INSERT INTO cities (state_id, name) VALUES (20, 'LOMA BONITA');
INSERT INTO cities (state_id, name) VALUES (20, 'MATIAS ROMERO');
INSERT INTO cities (state_id, name) VALUES (20, 'MIAHUATLAN DE PORFIRIO DIAZ');
INSERT INTO cities (state_id, name) VALUES (20, 'OAXACA');
INSERT INTO cities (state_id, name) VALUES (20, 'OCOTLAN DE MORELOS - SAN ANTONIO');
INSERT INTO cities (state_id, name) VALUES (20, 'PUERTO ESCONDIDO - ZICATELA');
INSERT INTO cities (state_id, name) VALUES (20, 'SALINA CRUZ');
INSERT INTO cities (state_id, name) VALUES (20, 'SANTIAGO PINOTEPA NACIONAL');
INSERT INTO cities (state_id, name) VALUES (20, 'SANTO DOMINGO TEHUANTEPEC');
INSERT INTO cities (state_id, name) VALUES (20, 'TUXTEPEC');
INSERT INTO cities (state_id, name) VALUES (21, 'ACAJETE');
INSERT INTO cities (state_id, name) VALUES (21, 'ACATZINGO - LOS REYES');
INSERT INTO cities (state_id, name) VALUES (21, 'AJALPAN - ALTEPEJI');
INSERT INTO cities (state_id, name) VALUES (21, 'ATLIXCO');
INSERT INTO cities (state_id, name) VALUES (21, 'CIUDAD SERDAN');
INSERT INTO cities (state_id, name) VALUES (21, 'HUAUCHINANGO');
INSERT INTO cities (state_id, name) VALUES (21, 'HUEJOTZINGO');
INSERT INTO cities (state_id, name) VALUES (21, 'IZUCAR DE MATAMOROS');
INSERT INTO cities (state_id, name) VALUES (21, 'NUEVO NECAXA - TENANGO');
INSERT INTO cities (state_id, name) VALUES (21, 'PALMARITO TOCHAPAN');
INSERT INTO cities (state_id, name) VALUES (21, 'PUEBLA');
INSERT INTO cities (state_id, name) VALUES (21, 'SAN LORENZO CHIAUTZINGO - SAN FELIPE TEOTLALCINGO');
INSERT INTO cities (state_id, name) VALUES (21, 'SAN MARTÍN TEXMELUCAN');
INSERT INTO cities (state_id, name) VALUES (21, 'TECAMACHALCO');
INSERT INTO cities (state_id, name) VALUES (21, 'TEHUACAN');
INSERT INTO cities (state_id, name) VALUES (21, 'TEPEACA');
INSERT INTO cities (state_id, name) VALUES (21, 'TEZIUTLAN');
INSERT INTO cities (state_id, name) VALUES (21, 'XICOTEPEC DE JUAREZ');
INSERT INTO cities (state_id, name) VALUES (21, 'ZACATLAN');
INSERT INTO cities (state_id, name) VALUES (22, 'QUERÉTARO');
INSERT INTO cities (state_id, name) VALUES (22, 'SAN JUAN DEL RIO');
INSERT INTO cities (state_id, name) VALUES (22, 'TEQUISQUIAPAN');
INSERT INTO cities (state_id, name) VALUES (23, 'CANCUN');
INSERT INTO cities (state_id, name) VALUES (23, 'CHETUMAL');
INSERT INTO cities (state_id, name) VALUES (23, 'COZUMEL');
INSERT INTO cities (state_id, name) VALUES (23, 'FELIPE CARRILLO PUERTO');
INSERT INTO cities (state_id, name) VALUES (23, 'PLAYA DEL CARMEN');
INSERT INTO cities (state_id, name) VALUES (24, 'CIUDAD VALLES');
INSERT INTO cities (state_id, name) VALUES (24, 'EBANO');
INSERT INTO cities (state_id, name) VALUES (24, 'MATEHUALA');
INSERT INTO cities (state_id, name) VALUES (24, 'RIOVERDE - CIUDAD FERNÁNDEZ');
INSERT INTO cities (state_id, name) VALUES (24, 'SAN LUIS POTOSÍ');
INSERT INTO cities (state_id, name) VALUES (24, 'TAMAZUNCHALE');
INSERT INTO cities (state_id, name) VALUES (25, 'COSTA RICA');
INSERT INTO cities (state_id, name) VALUES (25, 'CULIACAN ROSALES');
INSERT INTO cities (state_id, name) VALUES (25, 'ESCUINAPA');
INSERT INTO cities (state_id, name) VALUES (25, 'GABRIEL LEYVA SOLANO (BENITO JUAREZ)');
INSERT INTO cities (state_id, name) VALUES (25, 'GUAMUCHIL');
INSERT INTO cities (state_id, name) VALUES (25, 'GUASAVE');
INSERT INTO cities (state_id, name) VALUES (25, 'HEROICA CABORCA');
INSERT INTO cities (state_id, name) VALUES (25, 'JUAN JOSE RIOS');
INSERT INTO cities (state_id, name) VALUES (25, 'LIC. BENITO JUAREZ (CAMPO GOBIERNO)');
INSERT INTO cities (state_id, name) VALUES (25, 'LOS MOCHIS');
INSERT INTO cities (state_id, name) VALUES (25, 'MAZATLAN');
INSERT INTO cities (state_id, name) VALUES (25, 'NAVOLATO');
INSERT INTO cities (state_id, name) VALUES (26, 'AGUA PRIETA');
INSERT INTO cities (state_id, name) VALUES (26, 'CANANEA');
INSERT INTO cities (state_id, name) VALUES (26, 'CIUDAD OBREGON');
INSERT INTO cities (state_id, name) VALUES (26, 'ESPERANZA');
INSERT INTO cities (state_id, name) VALUES (26, 'GUAYMAS');
INSERT INTO cities (state_id, name) VALUES (26, 'HERMOSILLO');
INSERT INTO cities (state_id, name) VALUES (26, 'HEROICA NOGALES');
INSERT INTO cities (state_id, name) VALUES (26, 'HUATABAMPO');
INSERT INTO cities (state_id, name) VALUES (26, 'MAGDALENA DE KINO');
INSERT INTO cities (state_id, name) VALUES (26, 'MIGUEL ALEMAN (LA DOCE)');
INSERT INTO cities (state_id, name) VALUES (26, 'NAVOJOA');
INSERT INTO cities (state_id, name) VALUES (26, 'PUERTO PEÑASCO');
INSERT INTO cities (state_id, name) VALUES (26, 'SAN LUIS RIO COLORADO');
INSERT INTO cities (state_id, name) VALUES (27, 'CARDENAS');
INSERT INTO cities (state_id, name) VALUES (27, 'COMALCALCO');
INSERT INTO cities (state_id, name) VALUES (27, 'CUNDUACAN');
INSERT INTO cities (state_id, name) VALUES (27, 'EMILIANO ZAPATA');
INSERT INTO cities (state_id, name) VALUES (27, 'FRONTERA');
INSERT INTO cities (state_id, name) VALUES (27, 'HUIMANGUILLO');
INSERT INTO cities (state_id, name) VALUES (27, 'MACUSPANA');
INSERT INTO cities (state_id, name) VALUES (27, 'PARAISO');
INSERT INTO cities (state_id, name) VALUES (27, 'TEAPA');
INSERT INTO cities (state_id, name) VALUES (27, 'TENOSIQUE DE PINO SUAREZ');
INSERT INTO cities (state_id, name) VALUES (27, 'VILLAHERMOSA');
INSERT INTO cities (state_id, name) VALUES (28, 'CIUDAD MANTE');
INSERT INTO cities (state_id, name) VALUES (28, 'CIUDAD MIGUEL ALEMAN');
INSERT INTO cities (state_id, name) VALUES (28, 'CIUDAD RIO BRAVO');
INSERT INTO cities (state_id, name) VALUES (28, 'CIUDAD VICTORIA');
INSERT INTO cities (state_id, name) VALUES (28, 'HEROICA MATAMOROS');
INSERT INTO cities (state_id, name) VALUES (28, 'NUEVO LAREDO');
INSERT INTO cities (state_id, name) VALUES (28, 'REYNOSA');
INSERT INTO cities (state_id, name) VALUES (28, 'SAN FERNANDO');
INSERT INTO cities (state_id, name) VALUES (28, 'TAMPICO');
INSERT INTO cities (state_id, name) VALUES (28, 'VALLE HERMOSO');
INSERT INTO cities (state_id, name) VALUES (29, 'APIZACO');
INSERT INTO cities (state_id, name) VALUES (29, 'CALPULALPAN');
INSERT INTO cities (state_id, name) VALUES (29, 'HUAMANTLA');
INSERT INTO cities (state_id, name) VALUES (29, 'TLAXCALA');
INSERT INTO cities (state_id, name) VALUES (29, 'XALOZTOC');
INSERT INTO cities (state_id, name) VALUES (30, 'ACAYUCAN');
INSERT INTO cities (state_id, name) VALUES (30, 'AGUA DULCE');
INSERT INTO cities (state_id, name) VALUES (30, 'ALAMO');
INSERT INTO cities (state_id, name) VALUES (30, 'ALTOTONGA');
INSERT INTO cities (state_id, name) VALUES (30, 'ALVARADO');
INSERT INTO cities (state_id, name) VALUES (30, 'CATEMACO');
INSERT INTO cities (state_id, name) VALUES (30, 'CERRO AZUL');
INSERT INTO cities (state_id, name) VALUES (30, 'COATEPEC');
INSERT INTO cities (state_id, name) VALUES (30, 'COATZACOALCOS');
INSERT INTO cities (state_id, name) VALUES (30, 'CÓRDOBA');
INSERT INTO cities (state_id, name) VALUES (30, 'COSAMALOAPAN - CARLOS A. CARRILLO');
INSERT INTO cities (state_id, name) VALUES (30, 'HUATUSCO DE CHICUELLAR');
INSERT INTO cities (state_id, name) VALUES (30, 'ISLA');
INSERT INTO cities (state_id, name) VALUES (30, 'JOSE CARDEL - CABEZAS');
INSERT INTO cities (state_id, name) VALUES (30, 'LAS CHOAPAS');
INSERT INTO cities (state_id, name) VALUES (30, 'LERDO DE TEJADA');
INSERT INTO cities (state_id, name) VALUES (30, 'MARTINEZ DE LA TORRE');
INSERT INTO cities (state_id, name) VALUES (30, 'MINATITLÁN');
INSERT INTO cities (state_id, name) VALUES (30, 'MISANTLA');
INSERT INTO cities (state_id, name) VALUES (30, 'NARANJOS');
INSERT INTO cities (state_id, name) VALUES (30, 'ORIZABA');
INSERT INTO cities (state_id, name) VALUES (30, 'PANUCO');
INSERT INTO cities (state_id, name) VALUES (30, 'PAPANTLA DE OLARTE');
INSERT INTO cities (state_id, name) VALUES (30, 'PEROTE');
INSERT INTO cities (state_id, name) VALUES (30, 'POZA RICA');
INSERT INTO cities (state_id, name) VALUES (30, 'SAN ANDRES TUXTLA');
INSERT INTO cities (state_id, name) VALUES (30, 'SANTIAGO TUXTLA');
INSERT INTO cities (state_id, name) VALUES (30, 'TANTOYUCA');
INSERT INTO cities (state_id, name) VALUES (30, 'TIERRA BLANCA');
INSERT INTO cities (state_id, name) VALUES (30, 'TLAPACOYAN');
INSERT INTO cities (state_id, name) VALUES (30, 'TRES VALLES');
INSERT INTO cities (state_id, name) VALUES (30, 'TUXPAM');
INSERT INTO cities (state_id, name) VALUES (30, 'VERACRUZ');
INSERT INTO cities (state_id, name) VALUES (30, 'XALAPA');
INSERT INTO cities (state_id, name) VALUES (31, 'HUNUCMA');
INSERT INTO cities (state_id, name) VALUES (31, 'MÉRIDA');
INSERT INTO cities (state_id, name) VALUES (31, 'MOTUL DE CARRILLO PUERTO');
INSERT INTO cities (state_id, name) VALUES (31, 'OXKUTZCAB');
INSERT INTO cities (state_id, name) VALUES (31, 'PETO');
INSERT INTO cities (state_id, name) VALUES (31, 'PROGRESO');
INSERT INTO cities (state_id, name) VALUES (31, 'TEKAX DE ALVARO OBREGON');
INSERT INTO cities (state_id, name) VALUES (31, 'TICUL');
INSERT INTO cities (state_id, name) VALUES (31, 'TIZIMIN');
INSERT INTO cities (state_id, name) VALUES (31, 'VALLADOLID');
INSERT INTO cities (state_id, name) VALUES (32, 'FRESNILLO');
INSERT INTO cities (state_id, name) VALUES (32, 'JEREZ DE GARCIA SALINAS');
INSERT INTO cities (state_id, name) VALUES (32, 'LORETO');
INSERT INTO cities (state_id, name) VALUES (32, 'NOCHISTLAN DE MEJIA');
INSERT INTO cities (state_id, name) VALUES (32, 'OJOCALIENTE');
INSERT INTO cities (state_id, name) VALUES (32, 'RIO GRANDE');
INSERT INTO cities (state_id, name) VALUES (32, 'SOMBRERETE');
INSERT INTO cities (state_id, name) VALUES (32, 'VICTOR ROSALES');
INSERT INTO cities (state_id, name) VALUES (32, 'ZACATECAS');
