INSERT INTO cities (state_id, name) VALUES (1, 'Aguascalientes');
INSERT INTO cities (state_id, name) VALUES (1, 'Calvillo');
INSERT INTO cities (state_id, name) VALUES (1, 'Pabellón de Arteaga');
INSERT INTO cities (state_id, name) VALUES (1, 'Rincón de Romos');
INSERT INTO cities (state_id, name) VALUES (2, 'Ensenada');
INSERT INTO cities (state_id, name) VALUES (2, 'Guadalupe Victoria (km. 43)');
INSERT INTO cities (state_id, name) VALUES (2, 'Mexicali');
INSERT INTO cities (state_id, name) VALUES (2, 'Rodolfo Sánchez T. (maneadero)');
INSERT INTO cities (state_id, name) VALUES (2, 'Santa Isabel');
INSERT INTO cities (state_id, name) VALUES (2, 'Tecate');
INSERT INTO cities (state_id, name) VALUES (2, 'Tijuana');
INSERT INTO cities (state_id, name) VALUES (3, 'Cabo San Lucas');
INSERT INTO cities (state_id, name) VALUES (3, 'Ciudad Constitución');
INSERT INTO cities (state_id, name) VALUES (3, 'La Paz');
INSERT INTO cities (state_id, name) VALUES (3, 'San José del Cabo');
INSERT INTO cities (state_id, name) VALUES (4, 'Campeche');
INSERT INTO cities (state_id, name) VALUES (4, 'Champotón');
INSERT INTO cities (state_id, name) VALUES (4, 'Ciudad del Carmen');
INSERT INTO cities (state_id, name) VALUES (4, 'Escarcega');
INSERT INTO cities (state_id, name) VALUES (5, 'Arriaga');
INSERT INTO cities (state_id, name) VALUES (5, 'Berriozabal');
INSERT INTO cities (state_id, name) VALUES (5, 'Cintalapa de Figueroa');
INSERT INTO cities (state_id, name) VALUES (5, 'Comitán de Domínguez');
INSERT INTO cities (state_id, name) VALUES (5, 'Huixtla');
INSERT INTO cities (state_id, name) VALUES (5, 'Las Rosas');
INSERT INTO cities (state_id, name) VALUES (5, 'Motozintla de Mendoza');
INSERT INTO cities (state_id, name) VALUES (5, 'Ocosingo');
INSERT INTO cities (state_id, name) VALUES (5, 'Ocozocoautla de Espinosa');
INSERT INTO cities (state_id, name) VALUES (5, 'Palenque');
INSERT INTO cities (state_id, name) VALUES (5, 'Reforma');
INSERT INTO cities (state_id, name) VALUES (5, 'San Cristóbal de las Casas');
INSERT INTO cities (state_id, name) VALUES (5, 'Tapachula de Córdoba y Ordóñez');
INSERT INTO cities (state_id, name) VALUES (5, 'Tonalá');
INSERT INTO cities (state_id, name) VALUES (5, 'Tuxtla Gutiérrez');
INSERT INTO cities (state_id, name) VALUES (5, 'Villaflores');
INSERT INTO cities (state_id, name) VALUES (6, 'Chihuahua');
INSERT INTO cities (state_id, name) VALUES (6, 'Cuauhtémoc');
INSERT INTO cities (state_id, name) VALUES (6, 'Delicias');
INSERT INTO cities (state_id, name) VALUES (6, 'Hidalgo del Parral');
INSERT INTO cities (state_id, name) VALUES (6, 'José Mariano Jiménez');
INSERT INTO cities (state_id, name) VALUES (6, 'Juan Aldama');
INSERT INTO cities (state_id, name) VALUES (6, 'Juárez');
INSERT INTO cities (state_id, name) VALUES (6, 'Manuel Ojinaga');
INSERT INTO cities (state_id, name) VALUES (6, 'Nuevo Casas Grandes');
INSERT INTO cities (state_id, name) VALUES (6, 'Pedro Meoqui');
INSERT INTO cities (state_id, name) VALUES (6, 'Santa Rosalía de Camargo');
INSERT INTO cities (state_id, name) VALUES (7, 'Allende');
INSERT INTO cities (state_id, name) VALUES (7, 'Ciudad Acuña');
INSERT INTO cities (state_id, name) VALUES (7, 'Ciudad Melchor Muzquiz');
INSERT INTO cities (state_id, name) VALUES (7, 'Francisco I. Madero');
INSERT INTO cities (state_id, name) VALUES (7, 'Monclova');
INSERT INTO cities (state_id, name) VALUES (7, 'Nueva Rosita - Cloete');
INSERT INTO cities (state_id, name) VALUES (7, 'Palau');
INSERT INTO cities (state_id, name) VALUES (7, 'Parras de la Fuente');
INSERT INTO cities (state_id, name) VALUES (7, 'Piedras Negras');
INSERT INTO cities (state_id, name) VALUES (7, 'Sabinas');
INSERT INTO cities (state_id, name) VALUES (7, 'Saltillo');
INSERT INTO cities (state_id, name) VALUES (7, 'San Buenaventura');
INSERT INTO cities (state_id, name) VALUES (7, 'San Pedro');
INSERT INTO cities (state_id, name) VALUES (7, 'Torreón');
INSERT INTO cities (state_id, name) VALUES (8, 'Colima');
INSERT INTO cities (state_id, name) VALUES (8, 'Manzanillo');
INSERT INTO cities (state_id, name) VALUES (8, 'Tecomán - Armeria');
INSERT INTO cities (state_id, name) VALUES (9, 'Ciudad de México');
INSERT INTO cities (state_id, name) VALUES (10, 'El Salto');
INSERT INTO cities (state_id, name) VALUES (10, 'Santiago Papasquiaro');
INSERT INTO cities (state_id, name) VALUES (10, 'Victoria de Durango');
INSERT INTO cities (state_id, name) VALUES (11, 'Amecameca de Juárez');
INSERT INTO cities (state_id, name) VALUES (11, 'Atlacomulco - Tecoac');
INSERT INTO cities (state_id, name) VALUES (11, 'Capulhuac - Santiago Tianguistenco');
INSERT INTO cities (state_id, name) VALUES (11, 'Ixtapan de la Sal');
INSERT INTO cities (state_id, name) VALUES (11, 'Los Baños');
INSERT INTO cities (state_id, name) VALUES (11, 'Ocoyoacac');
INSERT INTO cities (state_id, name) VALUES (11, 'Ozumba');
INSERT INTO cities (state_id, name) VALUES (11, 'San Bartolo del Llano - Santa Cruz Tepexpan');
INSERT INTO cities (state_id, name) VALUES (11, 'Santo Domingo');
INSERT INTO cities (state_id, name) VALUES (11, 'Tejupilco de Hidalgo');
INSERT INTO cities (state_id, name) VALUES (11, 'Temascalcingo - La Magdalena');
INSERT INTO cities (state_id, name) VALUES (11, 'Tenancingo de Degollado');
INSERT INTO cities (state_id, name) VALUES (11, 'Tenango - Satiaguito');
INSERT INTO cities (state_id, name) VALUES (11, 'Tequixquiac');
INSERT INTO cities (state_id, name) VALUES (11, 'Toluca');
INSERT INTO cities (state_id, name) VALUES (11, 'Valle de Bravo');
INSERT INTO cities (state_id, name) VALUES (11, 'Villa Cuauhtémoc');
INSERT INTO cities (state_id, name) VALUES (11, 'Xalatlaco - Santiago Tilapa');
INSERT INTO cities (state_id, name) VALUES (12, 'Abasolo');
INSERT INTO cities (state_id, name) VALUES (12, 'Acambaro');
INSERT INTO cities (state_id, name) VALUES (12, 'Apaseo el Alto');
INSERT INTO cities (state_id, name) VALUES (12, 'Apaseo el Grande');
INSERT INTO cities (state_id, name) VALUES (12, 'Celaya');
INSERT INTO cities (state_id, name) VALUES (12, 'Centro Familiar la Soledad');
INSERT INTO cities (state_id, name) VALUES (12, 'Comonfort');
INSERT INTO cities (state_id, name) VALUES (12, 'Cortazar');
INSERT INTO cities (state_id, name) VALUES (12, 'Dolores Hidalgo Cuna de la Indep. Nal.');
INSERT INTO cities (state_id, name) VALUES (12, 'Guanajuato');
INSERT INTO cities (state_id, name) VALUES (12, 'Irapuato');
INSERT INTO cities (state_id, name) VALUES (12, 'Jaral del Progreso');
INSERT INTO cities (state_id, name) VALUES (12, 'Juventino Rosas');
INSERT INTO cities (state_id, name) VALUES (12, 'León');
INSERT INTO cities (state_id, name) VALUES (12, 'Moroleón - Uriangato');
INSERT INTO cities (state_id, name) VALUES (12, 'Pénjamo');
INSERT INTO cities (state_id, name) VALUES (12, 'Romita');
INSERT INTO cities (state_id, name) VALUES (12, 'Salamanca');
INSERT INTO cities (state_id, name) VALUES (12, 'Salvatierra');
INSERT INTO cities (state_id, name) VALUES (12, 'San Felipe');
INSERT INTO cities (state_id, name) VALUES (12, 'San Francisco - Purísima');
INSERT INTO cities (state_id, name) VALUES (12, 'San Luis de la Paz');
INSERT INTO cities (state_id, name) VALUES (12, 'San Miguel de Allende');
INSERT INTO cities (state_id, name) VALUES (12, 'Silao');
INSERT INTO cities (state_id, name) VALUES (12, 'Valle de Santiago');
INSERT INTO cities (state_id, name) VALUES (12, 'Villagrán');
INSERT INTO cities (state_id, name) VALUES (12, 'Yuriria');
INSERT INTO cities (state_id, name) VALUES (13, 'Acapulco de Juárez');
INSERT INTO cities (state_id, name) VALUES (13, 'Arcelia');
INSERT INTO cities (state_id, name) VALUES (13, 'Atoyac de Alvarez');
INSERT INTO cities (state_id, name) VALUES (13, 'Chilapa de Alvarez');
INSERT INTO cities (state_id, name) VALUES (13, 'Chilpancingo de los Bravo');
INSERT INTO cities (state_id, name) VALUES (13, 'Ciudad Altamirano - Riva Palacio');
INSERT INTO cities (state_id, name) VALUES (13, 'Ciudad de Huitzuco');
INSERT INTO cities (state_id, name) VALUES (13, 'Iguala de la Independencia');
INSERT INTO cities (state_id, name) VALUES (13, 'Ometepec');
INSERT INTO cities (state_id, name) VALUES (13, 'Petatlán');
INSERT INTO cities (state_id, name) VALUES (13, 'San José Iturbide');
INSERT INTO cities (state_id, name) VALUES (13, 'Taxco de Alarcón');
INSERT INTO cities (state_id, name) VALUES (13, 'Tecpan de Galeana - El Suchil');
INSERT INTO cities (state_id, name) VALUES (13, 'Teloloapan');
INSERT INTO cities (state_id, name) VALUES (13, 'Tixtla de Guerrero');
INSERT INTO cities (state_id, name) VALUES (13, 'Tlapa de Comonfort');
INSERT INTO cities (state_id, name) VALUES (13, 'Tulancingo');
INSERT INTO cities (state_id, name) VALUES (13, 'Zihuatanejo');
INSERT INTO cities (state_id, name) VALUES (13, 'Zumpango del Río');
INSERT INTO cities (state_id, name) VALUES (14, 'Actopan');
INSERT INTO cities (state_id, name) VALUES (14, 'Apan');
INSERT INTO cities (state_id, name) VALUES (14, 'Ciudad Sahagún');
INSERT INTO cities (state_id, name) VALUES (14, 'Huejutla');
INSERT INTO cities (state_id, name) VALUES (14, 'Ixmiquilpan');
INSERT INTO cities (state_id, name) VALUES (14, 'Mixquiahuala - Progreso');
INSERT INTO cities (state_id, name) VALUES (14, 'Pachuca');
INSERT INTO cities (state_id, name) VALUES (14, 'Tepeji de Ocampo');
INSERT INTO cities (state_id, name) VALUES (14, 'Tezontepec de Aldama');
INSERT INTO cities (state_id, name) VALUES (14, 'Tlaxcoapan');
INSERT INTO cities (state_id, name) VALUES (14, 'Tula');
INSERT INTO cities (state_id, name) VALUES (14, 'Zacualtipán');
INSERT INTO cities (state_id, name) VALUES (15, 'Ameca');
INSERT INTO cities (state_id, name) VALUES (15, 'Arandas');
INSERT INTO cities (state_id, name) VALUES (15, 'Atotonilco el Alto');
INSERT INTO cities (state_id, name) VALUES (15, 'Autlán de Navarro');
INSERT INTO cities (state_id, name) VALUES (15, 'Chapala');
INSERT INTO cities (state_id, name) VALUES (15, 'Cihuatlán');
INSERT INTO cities (state_id, name) VALUES (15, 'Ciudad Guzmán');
INSERT INTO cities (state_id, name) VALUES (15, 'El Grullo');
INSERT INTO cities (state_id, name) VALUES (15, 'Encarnación de Díaz');
INSERT INTO cities (state_id, name) VALUES (15, 'Guadalajara');
INSERT INTO cities (state_id, name) VALUES (15, 'Ixtapa');
INSERT INTO cities (state_id, name) VALUES (15, 'Jalostotitlán');
INSERT INTO cities (state_id, name) VALUES (15, 'Jamay');
INSERT INTO cities (state_id, name) VALUES (15, 'Jocotepec');
INSERT INTO cities (state_id, name) VALUES (15, 'La Barca');
INSERT INTO cities (state_id, name) VALUES (15, 'Lagos de Moreno');
INSERT INTO cities (state_id, name) VALUES (15, 'Ocotlán');
INSERT INTO cities (state_id, name) VALUES (15, 'Puerto Vallarta');
INSERT INTO cities (state_id, name) VALUES (15, 'San Juan de los Lagos');
INSERT INTO cities (state_id, name) VALUES (15, 'San Miguel el Alto');
INSERT INTO cities (state_id, name) VALUES (15, 'Sayula');
INSERT INTO cities (state_id, name) VALUES (15, 'Tala');
INSERT INTO cities (state_id, name) VALUES (15, 'Tamazula de Gordiano');
INSERT INTO cities (state_id, name) VALUES (15, 'Teocaltiche');
INSERT INTO cities (state_id, name) VALUES (15, 'Tepatitlan de Morelos');
INSERT INTO cities (state_id, name) VALUES (15, 'Tequila');
INSERT INTO cities (state_id, name) VALUES (15, 'Tuxpan');
INSERT INTO cities (state_id, name) VALUES (15, 'Zacoalco de Torres');
INSERT INTO cities (state_id, name) VALUES (15, 'Zapotiltic');
INSERT INTO cities (state_id, name) VALUES (15, 'Zapotlanejo');
INSERT INTO cities (state_id, name) VALUES (16, 'Apatzingán de la Constitución');
INSERT INTO cities (state_id, name) VALUES (16, 'Ciudad Hidalgo');
INSERT INTO cities (state_id, name) VALUES (16, 'Huetamo de Núñez');
INSERT INTO cities (state_id, name) VALUES (16, 'Jiquilpan de Juárez');
INSERT INTO cities (state_id, name) VALUES (16, 'La Piedad - Santa Ana Pacueco');
INSERT INTO cities (state_id, name) VALUES (16, 'Lázaro Cárdenas');
INSERT INTO cities (state_id, name) VALUES (16, 'Los Reyes de Salgado');
INSERT INTO cities (state_id, name) VALUES (16, 'Maravatio de Ocampo');
INSERT INTO cities (state_id, name) VALUES (16, 'Morelia');
INSERT INTO cities (state_id, name) VALUES (16, 'Nueva Italia de Ruiz');
INSERT INTO cities (state_id, name) VALUES (16, 'Paracho de Verduzco');
INSERT INTO cities (state_id, name) VALUES (16, 'Pátzcuaro');
INSERT INTO cities (state_id, name) VALUES (16, 'Puruándiro');
INSERT INTO cities (state_id, name) VALUES (16, 'Sahuayo de Morelos');
INSERT INTO cities (state_id, name) VALUES (16, 'Tacámbaro de Codallos');
INSERT INTO cities (state_id, name) VALUES (16, 'Uruapan');
INSERT INTO cities (state_id, name) VALUES (16, 'Yurécuaro');
INSERT INTO cities (state_id, name) VALUES (16, 'Zacapu');
INSERT INTO cities (state_id, name) VALUES (16, 'Zamora');
INSERT INTO cities (state_id, name) VALUES (16, 'Zinapécuaro - Bocaneo');
INSERT INTO cities (state_id, name) VALUES (16, 'Zitacuaro');
INSERT INTO cities (state_id, name) VALUES (17, 'Axochiapan');
INSERT INTO cities (state_id, name) VALUES (17, 'Cuautla');
INSERT INTO cities (state_id, name) VALUES (17, 'Cuernavaca');
INSERT INTO cities (state_id, name) VALUES (17, 'Jojutla - Tlaquiltenango');
INSERT INTO cities (state_id, name) VALUES (17, 'Puente de Ixtla');
INSERT INTO cities (state_id, name) VALUES (17, 'Xoxocotla');
INSERT INTO cities (state_id, name) VALUES (17, 'Zacatepec - Santa Rosa');
INSERT INTO cities (state_id, name) VALUES (18, 'Acaponeta');
INSERT INTO cities (state_id, name) VALUES (18, 'Compostela');
INSERT INTO cities (state_id, name) VALUES (18, 'Ixtlán del Río');
INSERT INTO cities (state_id, name) VALUES (18, 'Santiago Ixcuintla');
INSERT INTO cities (state_id, name) VALUES (18, 'Tepic');
INSERT INTO cities (state_id, name) VALUES (18, 'Tuxpan');
INSERT INTO cities (state_id, name) VALUES (19, 'Anáhuac');
INSERT INTO cities (state_id, name) VALUES (19, 'Cadereyta Jiménez');
INSERT INTO cities (state_id, name) VALUES (19, 'Ciudad de Allende');
INSERT INTO cities (state_id, name) VALUES (19, 'Ciudad Sabinas Hidalgo');
INSERT INTO cities (state_id, name) VALUES (19, 'Linares');
INSERT INTO cities (state_id, name) VALUES (19, 'Montemorelos');
INSERT INTO cities (state_id, name) VALUES (19, 'Monterrey');
INSERT INTO cities (state_id, name) VALUES (20, 'Ciudad Ixtepec');
INSERT INTO cities (state_id, name) VALUES (20, 'Heroica Ciudad de Huajuapan de León');
INSERT INTO cities (state_id, name) VALUES (20, 'Juchitán de Zaragoza');
INSERT INTO cities (state_id, name) VALUES (20, 'Loma Bonita');
INSERT INTO cities (state_id, name) VALUES (20, 'Matías Romero');
INSERT INTO cities (state_id, name) VALUES (20, 'Miahuatlán de Porfirio Díaz');
INSERT INTO cities (state_id, name) VALUES (20, 'Oaxaca');
INSERT INTO cities (state_id, name) VALUES (20, 'Ocotlán de Morelos - San Antonio');
INSERT INTO cities (state_id, name) VALUES (20, 'Puerto Escondido - Zicatela');
INSERT INTO cities (state_id, name) VALUES (20, 'Salina Cruz');
INSERT INTO cities (state_id, name) VALUES (20, 'Santiago Pinotepa Nacional');
INSERT INTO cities (state_id, name) VALUES (20, 'Santo Domingo Tehuantepec');
INSERT INTO cities (state_id, name) VALUES (20, 'Tuxtepec');
INSERT INTO cities (state_id, name) VALUES (21, 'Acajete');
INSERT INTO cities (state_id, name) VALUES (21, 'Acatzingo - Los Reyes');
INSERT INTO cities (state_id, name) VALUES (21, 'Ajalpan - Altepeji');
INSERT INTO cities (state_id, name) VALUES (21, 'Atlixco');
INSERT INTO cities (state_id, name) VALUES (21, 'Ciudad Serdan');
INSERT INTO cities (state_id, name) VALUES (21, 'Huauchinango');
INSERT INTO cities (state_id, name) VALUES (21, 'Huejotzingo');
INSERT INTO cities (state_id, name) VALUES (21, 'Izúcar de Matamoros');
INSERT INTO cities (state_id, name) VALUES (21, 'Nuevo Necaxa - Tenango');
INSERT INTO cities (state_id, name) VALUES (21, 'Palmarito Tochapan');
INSERT INTO cities (state_id, name) VALUES (21, 'Puebla');
INSERT INTO cities (state_id, name) VALUES (21, 'San Lorenzo Chiautzingo - San Felipe Teotlalcingo');
INSERT INTO cities (state_id, name) VALUES (21, 'San Martín Texmelucan');
INSERT INTO cities (state_id, name) VALUES (21, 'Tecamachalco');
INSERT INTO cities (state_id, name) VALUES (21, 'Tehuacán');
INSERT INTO cities (state_id, name) VALUES (21, 'Tepeaca');
INSERT INTO cities (state_id, name) VALUES (21, 'Teziutlán');
INSERT INTO cities (state_id, name) VALUES (21, 'Xicotepec de Juárez');
INSERT INTO cities (state_id, name) VALUES (21, 'Zacatlán');
INSERT INTO cities (state_id, name) VALUES (22, 'Querétaro');
INSERT INTO cities (state_id, name) VALUES (22, 'San Juan del Río');
INSERT INTO cities (state_id, name) VALUES (22, 'Tequisquiapan');
INSERT INTO cities (state_id, name) VALUES (23, 'Cancún');
INSERT INTO cities (state_id, name) VALUES (23, 'Chetumal');
INSERT INTO cities (state_id, name) VALUES (23, 'Cozumel');
INSERT INTO cities (state_id, name) VALUES (23, 'Felipe Carrillo Puerto');
INSERT INTO cities (state_id, name) VALUES (23, 'Playa del Carmen');
INSERT INTO cities (state_id, name) VALUES (24, 'Ciudad Valles');
INSERT INTO cities (state_id, name) VALUES (24, 'Ebano');
INSERT INTO cities (state_id, name) VALUES (24, 'Matehuala');
INSERT INTO cities (state_id, name) VALUES (24, 'Rioverde - Ciudad Fernández');
INSERT INTO cities (state_id, name) VALUES (24, 'San Luis Potosí');
INSERT INTO cities (state_id, name) VALUES (24, 'Tamazunchale');
INSERT INTO cities (state_id, name) VALUES (25, 'Costa Rica');
INSERT INTO cities (state_id, name) VALUES (25, 'Culiacán Rosales');
INSERT INTO cities (state_id, name) VALUES (25, 'Escuinapa');
INSERT INTO cities (state_id, name) VALUES (25, 'Gabriel Leyva Solano (Benito Juárez)');
INSERT INTO cities (state_id, name) VALUES (25, 'Guamuchil');
INSERT INTO cities (state_id, name) VALUES (25, 'Guasave');
INSERT INTO cities (state_id, name) VALUES (25, 'Heroica Caborca');
INSERT INTO cities (state_id, name) VALUES (25, 'Juan José Ríos');
INSERT INTO cities (state_id, name) VALUES (25, 'Lic. Benito Juárez (campo Gobierno)');
INSERT INTO cities (state_id, name) VALUES (25, 'Los Mochis');
INSERT INTO cities (state_id, name) VALUES (25, 'Mazatlán');
INSERT INTO cities (state_id, name) VALUES (25, 'Navolato');
INSERT INTO cities (state_id, name) VALUES (26, 'Agua Prieta');
INSERT INTO cities (state_id, name) VALUES (26, 'Cananea');
INSERT INTO cities (state_id, name) VALUES (26, 'Ciudad Obregón');
INSERT INTO cities (state_id, name) VALUES (26, 'Esperanza');
INSERT INTO cities (state_id, name) VALUES (26, 'Guaymas');
INSERT INTO cities (state_id, name) VALUES (26, 'Hermosillo');
INSERT INTO cities (state_id, name) VALUES (26, 'Heroica Nogales');
INSERT INTO cities (state_id, name) VALUES (26, 'Huatabampo');
INSERT INTO cities (state_id, name) VALUES (26, 'Magdalena de Kino');
INSERT INTO cities (state_id, name) VALUES (26, 'Miguel Alemán (la Doce)');
INSERT INTO cities (state_id, name) VALUES (26, 'Navojoa');
INSERT INTO cities (state_id, name) VALUES (26, 'Puerto Peñasco');
INSERT INTO cities (state_id, name) VALUES (26, 'San Luis Río Colorado');
INSERT INTO cities (state_id, name) VALUES (27, 'Cárdenas');
INSERT INTO cities (state_id, name) VALUES (27, 'Comalcalco');
INSERT INTO cities (state_id, name) VALUES (27, 'Cunduacan');
INSERT INTO cities (state_id, name) VALUES (27, 'Emiliano Zapata');
INSERT INTO cities (state_id, name) VALUES (27, 'Frontera');
INSERT INTO cities (state_id, name) VALUES (27, 'Huimanguillo');
INSERT INTO cities (state_id, name) VALUES (27, 'Macuspana');
INSERT INTO cities (state_id, name) VALUES (27, 'Paraiso');
INSERT INTO cities (state_id, name) VALUES (27, 'Teapa');
INSERT INTO cities (state_id, name) VALUES (27, 'Tenosique de Pino Suárez');
INSERT INTO cities (state_id, name) VALUES (27, 'Villahermosa');
INSERT INTO cities (state_id, name) VALUES (28, 'Ciudad Mante');
INSERT INTO cities (state_id, name) VALUES (28, 'Ciudad Miguel Alemán');
INSERT INTO cities (state_id, name) VALUES (28, 'Ciudad Río Bravo');
INSERT INTO cities (state_id, name) VALUES (28, 'Ciudad Victoria');
INSERT INTO cities (state_id, name) VALUES (28, 'Heroica Matamoros');
INSERT INTO cities (state_id, name) VALUES (28, 'Nuevo Laredo');
INSERT INTO cities (state_id, name) VALUES (28, 'Reynosa');
INSERT INTO cities (state_id, name) VALUES (28, 'San Fernando');
INSERT INTO cities (state_id, name) VALUES (28, 'Tampico');
INSERT INTO cities (state_id, name) VALUES (28, 'Valle Hermoso');
INSERT INTO cities (state_id, name) VALUES (29, 'Apizaco');
INSERT INTO cities (state_id, name) VALUES (29, 'Calpulalpan');
INSERT INTO cities (state_id, name) VALUES (29, 'Huamantla');
INSERT INTO cities (state_id, name) VALUES (29, 'Tlaxcala');
INSERT INTO cities (state_id, name) VALUES (29, 'Xaloztoc');
INSERT INTO cities (state_id, name) VALUES (30, 'Acayucan');
INSERT INTO cities (state_id, name) VALUES (30, 'Agua Dulce');
INSERT INTO cities (state_id, name) VALUES (30, 'Alamo');
INSERT INTO cities (state_id, name) VALUES (30, 'Altotonga');
INSERT INTO cities (state_id, name) VALUES (30, 'Alvarado');
INSERT INTO cities (state_id, name) VALUES (30, 'Catemaco');
INSERT INTO cities (state_id, name) VALUES (30, 'Cerro Azul');
INSERT INTO cities (state_id, name) VALUES (30, 'Coatepec');
INSERT INTO cities (state_id, name) VALUES (30, 'Coatzacoalcos');
INSERT INTO cities (state_id, name) VALUES (30, 'Córdoba');
INSERT INTO cities (state_id, name) VALUES (30, 'Cosamaloapan - Carlos A. Carrillo');
INSERT INTO cities (state_id, name) VALUES (30, 'Huatusco de Chicuellar');
INSERT INTO cities (state_id, name) VALUES (30, 'Isla');
INSERT INTO cities (state_id, name) VALUES (30, 'Jose Cardel - Cabezas');
INSERT INTO cities (state_id, name) VALUES (30, 'Las Choapas');
INSERT INTO cities (state_id, name) VALUES (30, 'Lerdo de Tejada');
INSERT INTO cities (state_id, name) VALUES (30, 'Martínez de la Torre');
INSERT INTO cities (state_id, name) VALUES (30, 'Minatitlán');
INSERT INTO cities (state_id, name) VALUES (30, 'Misantla');
INSERT INTO cities (state_id, name) VALUES (30, 'Naranjos');
INSERT INTO cities (state_id, name) VALUES (30, 'Orizaba');
INSERT INTO cities (state_id, name) VALUES (30, 'Pánuco');
INSERT INTO cities (state_id, name) VALUES (30, 'Papantla de Olarte');
INSERT INTO cities (state_id, name) VALUES (30, 'Perote');
INSERT INTO cities (state_id, name) VALUES (30, 'Poza Rica');
INSERT INTO cities (state_id, name) VALUES (30, 'San Andrés Tuxtla');
INSERT INTO cities (state_id, name) VALUES (30, 'Santiago Tuxtla');
INSERT INTO cities (state_id, name) VALUES (30, 'Tantoyuca');
INSERT INTO cities (state_id, name) VALUES (30, 'Tierra Blanca');
INSERT INTO cities (state_id, name) VALUES (30, 'Tlapacoyan');
INSERT INTO cities (state_id, name) VALUES (30, 'Tres Valles');
INSERT INTO cities (state_id, name) VALUES (30, 'Tuxpam');
INSERT INTO cities (state_id, name) VALUES (30, 'Veracruz');
INSERT INTO cities (state_id, name) VALUES (30, 'Xalapa');
INSERT INTO cities (state_id, name) VALUES (31, 'Hunucma');
INSERT INTO cities (state_id, name) VALUES (31, 'Mérida');
INSERT INTO cities (state_id, name) VALUES (31, 'Motul de Carrillo Puerto');
INSERT INTO cities (state_id, name) VALUES (31, 'Oxkutzcab');
INSERT INTO cities (state_id, name) VALUES (31, 'Peto');
INSERT INTO cities (state_id, name) VALUES (31, 'Progreso');
INSERT INTO cities (state_id, name) VALUES (31, 'Tekax de Alvaro Obregón');
INSERT INTO cities (state_id, name) VALUES (31, 'Ticul');
INSERT INTO cities (state_id, name) VALUES (31, 'Tizimín');
INSERT INTO cities (state_id, name) VALUES (31, 'Valladolid');
INSERT INTO cities (state_id, name) VALUES (32, 'Fresnillo');
INSERT INTO cities (state_id, name) VALUES (32, 'Jerez de García Salinas');
INSERT INTO cities (state_id, name) VALUES (32, 'Loreto');
INSERT INTO cities (state_id, name) VALUES (32, 'Nochistlán de Mejía');
INSERT INTO cities (state_id, name) VALUES (32, 'Ojocaliente');
INSERT INTO cities (state_id, name) VALUES (32, 'Río Grande');
INSERT INTO cities (state_id, name) VALUES (32, 'Sombrerete');
INSERT INTO cities (state_id, name) VALUES (32, 'Victor Rosales');
INSERT INTO cities (state_id, name) VALUES (32, 'Zacatecas');
