INSERT INTO countries VALUES (004, 'Afganistán', 'Afgana', 'AF');
INSERT INTO countries VALUES (248, 'Islas Åland', 'Ålandesa', 'AX');
INSERT INTO countries VALUES (008, 'Albania', 'Albanesa', 'AL');
INSERT INTO countries VALUES (276, 'Alemania', 'Alemana', 'DE');
INSERT INTO countries VALUES (020, 'Andorra', 'Andorrana', 'AD');
INSERT INTO countries VALUES (024, 'Angola', 'Angoleña', 'AO');
INSERT INTO countries VALUES (660, 'Anguilla', 'Anguilense', 'AI');
INSERT INTO countries VALUES (010, 'Antártida', 'Antártica', 'AQ');
INSERT INTO countries VALUES (028, 'Antigua y Barbuda', 'Antiguana', 'AG');
INSERT INTO countries VALUES (530, 'Antillas Neerlandesas', 'Antillana', 'AN');
INSERT INTO countries VALUES (682, 'Arabia Saudí', 'Arabe', 'SA');
INSERT INTO countries VALUES (012, 'Argelia', 'Argelina', 'DZ');
INSERT INTO countries VALUES (032, 'Argentina', 'Argentina', 'AR');
INSERT INTO countries VALUES (051, 'Armenia', 'Armenia', 'AM');
INSERT INTO countries VALUES (533, 'Aruba', 'Arubeño', 'AW');
INSERT INTO countries VALUES (036, 'Australia', 'Australiana', 'AU');
INSERT INTO countries VALUES (040, 'Austria', 'Austriaca', 'AT');
INSERT INTO countries VALUES (031, 'Azerbaiyán', 'Azerbaiyana', 'AZ');
INSERT INTO countries VALUES (044, 'Bahamas', 'Bahamesa', 'BS');
INSERT INTO countries VALUES (048, 'Bahréin', 'Bahreiní', 'BH');
INSERT INTO countries VALUES (050, 'Bangladesh', 'Bangladesha', 'BD');
INSERT INTO countries VALUES (052, 'Barbados', 'Barbadesa', 'BB');
INSERT INTO countries VALUES (112, 'Belarús', 'Bielorrusa', 'BY');
INSERT INTO countries VALUES (056, 'Bélgica', 'Belga', 'BE');
INSERT INTO countries VALUES (084, 'Belice', 'Beliceña', 'BZ');
INSERT INTO countries VALUES (204, 'Benin', 'Beninesa', 'BJ');
INSERT INTO countries VALUES (060, 'Bermudas', 'Bermudesa', 'BM');
INSERT INTO countries VALUES (064, 'Bhután', 'Bhutanesa', 'BT');
INSERT INTO countries VALUES (068, 'Bolivia', 'Boliviana', 'BO');
INSERT INTO countries VALUES (070, 'Bosnia y Herzegovina', 'Bosnia', 'BA');
INSERT INTO countries VALUES (072, 'Botsuana', 'Botsuana', 'BW');
INSERT INTO countries VALUES (074, 'Isla Bouvet', 'Bouvetana', 'BV');
INSERT INTO countries VALUES (076, 'Brasil', 'Brasileña', 'BR');
INSERT INTO countries VALUES (096, 'Brunéi', 'Bruneana', 'BN');
INSERT INTO countries VALUES (100, 'Bulgaria', 'Búlgara', 'BG');
INSERT INTO countries VALUES (854, 'Burkina Faso', 'Burkinesa', 'BF');
INSERT INTO countries VALUES (108, 'Burundi', 'Burundiana', 'BI');
INSERT INTO countries VALUES (132, 'Cabo Verde', 'Caboverdiana', 'CV');
INSERT INTO countries VALUES (136, 'Islas Caimán', 'Caimanesa', 'KY');
INSERT INTO countries VALUES (116, 'Camboya', 'Camboyana', 'KH');
INSERT INTO countries VALUES (120, 'Camerún', 'Camerunesa', 'CM');
INSERT INTO countries VALUES (124, 'Canadá', 'Canadiense', 'CA');
INSERT INTO countries VALUES (140, 'República Centroafricana', 'Centroafricana', 'CF');
INSERT INTO countries VALUES (148, 'Chad', 'Chadeña', 'TD');
INSERT INTO countries VALUES (203, 'Chequia', 'Checa', 'CZ');
INSERT INTO countries VALUES (152, 'Chile', 'Chilena', 'CL');
INSERT INTO countries VALUES (156, 'China', 'China', 'CN');
INSERT INTO countries VALUES (196, 'Chipre', 'Chipriota', 'CY');
INSERT INTO countries VALUES (162, 'Isla Christmas', 'De la Isla de Navidad', 'CX');
INSERT INTO countries VALUES (275, 'Cisjordania', 'Palestino', 'PS');
INSERT INTO countries VALUES (336, 'Ciudad del Vaticano', 'Vaticana', 'VA');
INSERT INTO countries VALUES (166, 'Islas Cocos', 'De la Isla de Cocos', 'CC');
INSERT INTO countries VALUES (170, 'Colombia', 'Colombiana', 'CO');
INSERT INTO countries VALUES (174, 'Comoras', 'Comorana', 'KM');
INSERT INTO countries VALUES (180, 'República Democrática del Congo', 'Congolesa', 'CD');
INSERT INTO countries VALUES (178, 'Congo', 'Congolesa', 'CG');
INSERT INTO countries VALUES (184, 'Islas Cook', 'De la Isla de Cook', 'CK');
INSERT INTO countries VALUES (408, 'Corea del Norte', 'Norcoreana', 'KP');
INSERT INTO countries VALUES (410, 'Corea del Sur', 'Surcoreana', 'KR');
INSERT INTO countries VALUES (384, 'Costa de Marfil', 'Marfilesa', 'CI');
INSERT INTO countries VALUES (188, 'Costa Rica', 'Costarricense', 'CR');
INSERT INTO countries VALUES (191, 'Croacia', 'Croata', 'HR');
INSERT INTO countries VALUES (192, 'Cuba', 'Cubana', 'CU');
INSERT INTO countries VALUES (208, 'Dinamarca', 'Danesa', 'DK');
INSERT INTO countries VALUES (212, 'Dominica', 'Dominiquesa', 'DM');
INSERT INTO countries VALUES (214, 'República Dominicana', 'Dominicana', 'DO');
INSERT INTO countries VALUES (218, 'Ecuador', 'Ecuatoriana', 'EC');
INSERT INTO countries VALUES (818, 'Egipto', 'Egipcia', 'EG');
INSERT INTO countries VALUES (222, 'El Salvador', 'Salvadoreña', 'SV');
INSERT INTO countries VALUES (784, 'Emiratos Árabes Unidos', 'Emiratounidense', 'AE');
INSERT INTO countries VALUES (232, 'Eritrea', 'Eritrea', 'ER');
INSERT INTO countries VALUES (703, 'Eslovaquia', 'Eslovaka', 'SK');
INSERT INTO countries VALUES (705, 'Eslovenia', 'Eslovena', 'SI');
INSERT INTO countries VALUES (724, 'España', 'Español', 'ES');
INSERT INTO countries VALUES (581, 'Islas Ultramarinas de Estados Unidos', 'De las Islas Ultramarinas de Estados Unidos', 'UM');
INSERT INTO countries VALUES (840, 'Estados Unidos', 'Estadounidense', 'US');
INSERT INTO countries VALUES (233, 'Estonia', 'Estona', 'EE');
INSERT INTO countries VALUES (231, 'Etiopía', 'Etíope', 'ET');
INSERT INTO countries VALUES (234, 'Islas Feroe', 'Feroésa', 'FO');
INSERT INTO countries VALUES (608, 'Filipinas', 'Filipina', 'PH');
INSERT INTO countries VALUES (246, 'Finlandia', 'Finesa', 'FI');
INSERT INTO countries VALUES (242, 'Fiyi', 'Fiyiana', 'FJ');
INSERT INTO countries VALUES (250, 'Francia', 'Francesa', 'FR');
INSERT INTO countries VALUES (266, 'Gabón', 'Gabonesa', 'GA');
INSERT INTO countries VALUES (270, 'Gambia', 'Gabiana', 'GM');
INSERT INTO countries VALUES (268, 'Georgia', 'Georgiana', 'GE');
INSERT INTO countries VALUES (239, 'Georgia del Sur', 'Surgeorgiana', 'GS');
INSERT INTO countries VALUES (288, 'Ghana', 'Ghanesa', 'GH');
INSERT INTO countries VALUES (292, 'Gibraltar', 'Gibraltareño', 'GI');
INSERT INTO countries VALUES (308, 'Granada', 'Granadeña', 'GD');
INSERT INTO countries VALUES (300, 'Grecia', 'Griega', 'GR');
INSERT INTO countries VALUES (304, 'Groenlandia', 'Groenlandesa', 'GL');
INSERT INTO countries VALUES (312, 'Guadalupe', 'Guadalupeño', 'GP');
INSERT INTO countries VALUES (316, 'Guam', 'Guameño', 'GU');
INSERT INTO countries VALUES (320, 'Guatemala', 'Guatemalteca', 'GT');
INSERT INTO countries VALUES (254, 'Guayana Francesa', 'Guayanesa', 'GF');
INSERT INTO countries VALUES (324, 'Guinea', 'Guineana', 'GN');
INSERT INTO countries VALUES (226, 'Guinea Ecuatorial', 'Ecuatoguineana', 'GQ');
INSERT INTO countries VALUES (624, 'Guinea-Bissau', 'Guineana', 'GW');
INSERT INTO countries VALUES (328, 'Guyana', 'Guyanesa', 'GY');
INSERT INTO countries VALUES (332, 'Haití', 'Haitiana', 'HT');
INSERT INTO countries VALUES (334, 'Islas Heard y McDonald', 'De las Islas Heard y McDonald', 'HM');
INSERT INTO countries VALUES (340, 'Honduras', 'Hondureña', 'HN');
INSERT INTO countries VALUES (344, 'Hong Kong', 'Hongkonesa', 'HK');
INSERT INTO countries VALUES (348, 'Hungría', 'Húngara', 'HU');
INSERT INTO countries VALUES (356, 'India', 'India', 'IN');
INSERT INTO countries VALUES (360, 'Indonesia', 'Indonesa', 'ID');
INSERT INTO countries VALUES (364, 'Irán', 'Iraní', 'IR');
INSERT INTO countries VALUES (368, 'Iraq', 'Iraquí', 'IQ');
INSERT INTO countries VALUES (372, 'Irlanda', 'Irlandesa', 'IE');
INSERT INTO countries VALUES (352, 'Islandia', 'Islandesa', 'IS');
INSERT INTO countries VALUES (376, 'Israel', 'Israelí', 'IL');
INSERT INTO countries VALUES (380, 'Italia', 'Italiana', 'IT');
INSERT INTO countries VALUES (388, 'Jamaica', 'Jamaiquina', 'JM');
INSERT INTO countries VALUES (392, 'Japón', 'Japonesa', 'JP');
INSERT INTO countries VALUES (400, 'Jordania', 'Jordana', 'JO');
INSERT INTO countries VALUES (398, 'Kazajstán', 'Kazaka', 'KZ');
INSERT INTO countries VALUES (404, 'Kenia', 'Keniata', 'KE');
INSERT INTO countries VALUES (417, 'Kirguistán', 'Kirguís', 'KG');
INSERT INTO countries VALUES (296, 'Kiribati', 'Kiribatí', 'KI');
INSERT INTO countries VALUES (414, 'Kuwait', 'Kuwaití', 'KW');
INSERT INTO countries VALUES (418, 'Laos', 'Laosiana', 'LA');
INSERT INTO countries VALUES (426, 'Lesotho', 'Lesothensa', 'LS');
INSERT INTO countries VALUES (428, 'Letonia', 'Letón', 'LV');
INSERT INTO countries VALUES (422, 'Líbano', 'Libanesa', 'LB');
INSERT INTO countries VALUES (430, 'Liberia', 'Liberiana', 'LR');
INSERT INTO countries VALUES (434, 'Libia', 'Libeña', 'LY');
INSERT INTO countries VALUES (438, 'Liechtenstein', 'Liechtenstein', 'LI');
INSERT INTO countries VALUES (440, 'Lituania', 'Lituana', 'LT');
INSERT INTO countries VALUES (442, 'Luxemburgo', 'Luxemburgues', 'LU');
INSERT INTO countries VALUES (446, 'Macao', 'Macaense', 'MO');
INSERT INTO countries VALUES (807, 'ARY Macedonia', 'Macedonia', 'MK');
INSERT INTO countries VALUES (450, 'Madagascar', 'Malgache', 'MG');
INSERT INTO countries VALUES (458, 'Malasia', 'Malasia', 'MY');
INSERT INTO countries VALUES (454, 'Malawi', 'Malawi', 'MW');
INSERT INTO countries VALUES (462, 'Maldivas', 'Maldivas', 'MV');
INSERT INTO countries VALUES (466, 'Malí', 'Maliense', 'ML');
INSERT INTO countries VALUES (470, 'Malta', 'Maltesa', 'MT');
INSERT INTO countries VALUES (238, 'Islas Malvinas', 'Malvinense', 'FK');
INSERT INTO countries VALUES (580, 'Islas Marianas del Norte', 'De las Islas Marianas del Norte', 'MP');
INSERT INTO countries VALUES (504, 'Marruecos', 'Marroquí', 'MA');
INSERT INTO countries VALUES (584, 'Islas Marshall', 'Marshalesa', 'MH');
INSERT INTO countries VALUES (474, 'Martinica', 'Martiniquesa', 'MQ');
INSERT INTO countries VALUES (480, 'Mauricio', 'Mauricio', 'MU');
INSERT INTO countries VALUES (478, 'Mauritania', 'Mauritana', 'MR');
INSERT INTO countries VALUES (175, 'Mayotte', 'Mayotense', 'YT');
INSERT INTO countries VALUES (484, 'México', 'Mexicana', 'MX');
INSERT INTO countries VALUES (583, 'Micronesia', 'Micronesia', 'FM');
INSERT INTO countries VALUES (498, 'Moldova', 'Moldava', 'MD');
INSERT INTO countries VALUES (492, 'Mónaco', 'Monegasca', 'MC');
INSERT INTO countries VALUES (496, 'Mongolia', 'Mongol', 'MN');
INSERT INTO countries VALUES (500, 'Montserrat', 'Montserratense', 'MS');
INSERT INTO countries VALUES (508, 'Mozambique', 'Mozambiqueña', 'MZ');
INSERT INTO countries VALUES (104, 'Myanmar', 'Birmana', 'MM');
INSERT INTO countries VALUES (516, 'Namibia', 'Namibia', 'NA');
INSERT INTO countries VALUES (520, 'Nauru', 'Nauru', 'NR');
INSERT INTO countries VALUES (524, 'Nepal', 'Nepalesa', 'NP');
INSERT INTO countries VALUES (558, 'Nicaragua', 'Nicaragüense', 'NI');
INSERT INTO countries VALUES (562, 'Níger', 'Nigerina', 'NE');
INSERT INTO countries VALUES (566, 'Nigeria', 'Nigeriana', 'NG');
INSERT INTO countries VALUES (570, 'Niue', 'Niueña', 'NU');
INSERT INTO countries VALUES (574, 'Isla Norfolk', 'De la Isla Norfolk', 'NF');
INSERT INTO countries VALUES (578, 'Noruega', 'Noruega', 'NO');
INSERT INTO countries VALUES (540, 'Nueva Caledonia', 'Neocaledonia', 'NC');
INSERT INTO countries VALUES (554, 'Nueva Zelanda', 'Neozelandesa', 'NZ');
INSERT INTO countries VALUES (512, 'Omán', 'Omaní', 'OM');
INSERT INTO countries VALUES (528, 'Países Bajos', 'Neerlandesa', 'NL');
INSERT INTO countries VALUES (586, 'Pakistán', 'Pakistaní', 'PK');
INSERT INTO countries VALUES (585, 'Palaos', 'Palauana', 'PW');
INSERT INTO countries VALUES (591, 'Panamá', 'Panameña', 'PA');
INSERT INTO countries VALUES (598, 'Papúa Nueva Guinea', 'Papú', 'PG');
INSERT INTO countries VALUES (600, 'Paraguay', 'Paraguaya', 'PY');
INSERT INTO countries VALUES (604, 'Perú', 'Peruana', 'PE');
INSERT INTO countries VALUES (612, 'Islas Pitcairn', 'Pitcairnesa', 'PN');
INSERT INTO countries VALUES (258, 'Polinesia Francesa', 'Polinesia', 'PF');
INSERT INTO countries VALUES (616, 'Polonia', 'Polaca', 'PL');
INSERT INTO countries VALUES (620, 'Portugal', 'Portuguesa', 'PT');
INSERT INTO countries VALUES (630, 'Puerto Rico', 'Puertorriqueña', 'PR');
INSERT INTO countries VALUES (634, 'Qatar', 'Qatarí', 'QA');
INSERT INTO countries VALUES (826, 'Reino Unido', 'Británica', 'GB');
INSERT INTO countries VALUES (638, 'Reunión', 'Reunionesa', 'RE');
INSERT INTO countries VALUES (646, 'Ruanda', 'Ruanda', 'RW');
INSERT INTO countries VALUES (642, 'Rumanía', 'Rumana', 'RO');
INSERT INTO countries VALUES (643, 'Rusia', 'Rusa', 'RU');
INSERT INTO countries VALUES (732, 'Sáhara Occidental', 'Saharaui', 'EH');
INSERT INTO countries VALUES (090, 'Islas Salomón', 'Salomonense', 'SB');
INSERT INTO countries VALUES (882, 'Samoa', 'Samoana', 'WS');
INSERT INTO countries VALUES (016, 'Samoa Americana', 'Samoamericana', 'AS');
INSERT INTO countries VALUES (659, 'San Cristóbal y Nieves', 'Sancristobaleña', 'KN');
INSERT INTO countries VALUES (674, 'San Marino', 'Sanmarinense', 'SM');
INSERT INTO countries VALUES (666, 'San Pedro y Miquelón', 'De San Pedro y Miquelón', 'PM');
INSERT INTO countries VALUES (670, 'San Vicente y las Granadinas', 'Sanvicentina', 'VC');
INSERT INTO countries VALUES (654, 'Santa Helena', 'Santahelena', 'SH');
INSERT INTO countries VALUES (662, 'Santa Lucía', 'Santalucense', 'LC');
INSERT INTO countries VALUES (678, 'Santo Tomé y Príncipe', 'Santotomense', 'ST');
INSERT INTO countries VALUES (686, 'Senegal', 'Senegalesa', 'SN');
INSERT INTO countries VALUES (891, 'Serbia y Montenegro', 'Serbomontenegrina', 'CS');
INSERT INTO countries VALUES (690, 'Seychelles', 'Serbomontenegrina', 'SC');
INSERT INTO countries VALUES (694, 'Sierra Leona', 'Sierraleonesa', 'SL');
INSERT INTO countries VALUES (702, 'Singapur', 'Singapur', 'SG');
INSERT INTO countries VALUES (760, 'Siria', 'Siria', 'SY');
INSERT INTO countries VALUES (706, 'Somalia', 'Somalia', 'SO');
INSERT INTO countries VALUES (144, 'Sri Lanka', 'Ceilandesa', 'LK');
INSERT INTO countries VALUES (748, 'Suazilandia', 'Suazilandesa', 'SZ');
INSERT INTO countries VALUES (710, 'Sudáfrica', 'Sudafricana', 'ZA');
INSERT INTO countries VALUES (736, 'Sudán', 'Sudanesa', 'SD');
INSERT INTO countries VALUES (752, 'Suecia', 'Sueca', 'SE');
INSERT INTO countries VALUES (756, 'Suiza', 'Suiza', 'CH');
INSERT INTO countries VALUES (740, 'Surinam', 'Surinamesa', 'SR');
INSERT INTO countries VALUES (744, 'Svalbard', 'Svalbardesa', 'SJ');
INSERT INTO countries VALUES (764, 'Tailandia', 'Tailandesa', 'TH');
INSERT INTO countries VALUES (158, 'Taiwán', 'Taiwanesa', 'TW');
INSERT INTO countries VALUES (834, 'Tanzania', 'Tanzana', 'TZ');
INSERT INTO countries VALUES (762, 'Tayikistán', 'Tayika', 'TJ');
INSERT INTO countries VALUES (086, 'Territorio Británico del Océano Índico', 'Del Territorio Británico del Océano Índico', 'IO');
INSERT INTO countries VALUES (260, 'Territorios Australes Franceses', 'De los Territorios Australes Franceses', 'TF');
INSERT INTO countries VALUES (626, 'Timor Oriental', 'Timorense', 'TL');
INSERT INTO countries VALUES (768, 'Togo', 'Togo', 'TG');
INSERT INTO countries VALUES (772, 'Tokelau', 'Tokelauésa', 'TK');
INSERT INTO countries VALUES (776, 'Tonga', 'Tonga', 'TO');
INSERT INTO countries VALUES (780, 'Trinidad y Tobago', 'Trinitense', 'TT');
INSERT INTO countries VALUES (788, 'Túnez', 'Tunecina', 'TN');
INSERT INTO countries VALUES (796, 'Islas Turcas y Caicos', 'De las Islas Turcas y Caicos', 'TC');
INSERT INTO countries VALUES (795, 'Turkmenistán', 'Turcomana', 'TM');
INSERT INTO countries VALUES (792, 'Turquía', 'Turca', 'TR');
INSERT INTO countries VALUES (798, 'Tuvalu', 'Tuvaluana', 'TV');
INSERT INTO countries VALUES (804, 'Ucrania', 'Ucraniana', 'UA');
INSERT INTO countries VALUES (800, 'Uganda', 'Ugandesa', 'UG');
INSERT INTO countries VALUES (858, 'Uruguay', 'Uruguaya', 'UY');
INSERT INTO countries VALUES (860, 'Uzbekistán', 'Uzbeka', 'UZ');
INSERT INTO countries VALUES (548, 'Vanuatu', 'Vanuatense', 'VU');
INSERT INTO countries VALUES (862, 'Venezuela', 'Venezolana', 'VE');
INSERT INTO countries VALUES (704, 'Vietnam', 'Vietnamita', 'VN');
INSERT INTO countries VALUES (092, 'Islas Vírgenes Británicas', 'De las Islas Vírgenes Británicas', 'VG');
INSERT INTO countries VALUES (850, 'Islas Vírgenes de los Estados Unidos', 'De las Islas Vírgenes de los Estados Unidos', 'VI');
INSERT INTO countries VALUES (876, 'Islas Wallis y Futuna', 'De las Islas Wallis y Futuna', 'WF');
INSERT INTO countries VALUES (887, 'Yemen', 'Yemení', 'YE');
INSERT INTO countries VALUES (262, 'Yibuti', 'Yibutiense', 'DJ');
INSERT INTO countries VALUES (894, 'Zambia', 'Zambiana', 'ZM');
INSERT INTO countries VALUES (716, 'Zimbabue', 'Zimbabuense', 'ZW');
