INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Artículos o ensayos en revistas', 1);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Nota de investigación', 1);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Reseña', 1);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Colecciones infantiles', 2);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Impresos', 2);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Reportes internos', 3);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Reportes técnicos', 3);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Gaceta', 3);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Antología', 4);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Antología critica', 4);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Guía de estudio', 4);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Notas de clase', 4);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Cuadernos', 4);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Manual de apoyo docente', 4);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Catálogos', 4);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Traducción de artículo', 5);
INSERT INTO genericworktypes (name, genericworkgroup_id) VALUES ('Traducción de sitio web', 5);
