INSERT INTO institutiontitles (name) VALUES ('Universidad');
INSERT INTO institutiontitles (name) VALUES ('Escuela');
INSERT INTO institutiontitles (name) VALUES ('Facultad');
INSERT INTO institutiontitles (name) VALUES ('Instituto');
INSERT INTO institutiontitles (name) VALUES ('Departamento');
INSERT INTO institutiontitles (name) VALUES ('Secretaría');
INSERT INTO institutiontitles (name) VALUES ('Unidad');
INSERT INTO institutiontitles (name) VALUES ('Centro');
INSERT INTO institutiontitles (name) VALUES ('Otro');
