INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '2', 'l-5144');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '6', 'l-5251');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '10', 'I-5356');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '4', 'I-5480');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '8', 'I-5584');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '12', 'I-5686');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '28', 'I-6160');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '32', 'I-6270');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '36', 'I-6376');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '30', 'I-6489');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '34', 'I-6593');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '1', '38', 'I-6696');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '2', '20', 'I-3121');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '2', '23', 'I-3227');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '2', '25', 'I-3333');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '2', '21', 'I-3446');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '2', '24', 'I-3558');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '2', '26', 'I-3667');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '13', 'I-7117');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '15', 'I-7220');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '17', 'I-7327');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '14', 'I-7439');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '16', 'I-7544');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '18', 'I-7658');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '2', 'I-8133');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '6', 'I-8242');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '10', 'I-8346');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '4', 'I-8467');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '8', 'I-8578');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '12', 'I-8682');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '28', 'I-9151');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '32', 'I-9254');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '36', 'I-9360');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '30', 'I-9484');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '34', 'I-9585');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('1', '3', '38', 'I-9689');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES ('1', 110, '');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES ('1', 111, '');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '4', '19', 'D-4100');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '4', '22', 'D-4200');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '5', '19', 'D-1200');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '5', '22', 'D-1300');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '6', '19', 'D-4310');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '6', '22', 'D-4420');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '1', 'D-5144');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '5', 'D-5251');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '9', 'D-5356');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '3', 'D-5480');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '7', 'D-5484');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '11', 'D-5686');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '27', 'D-6160');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '31', 'D-6270');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '35', 'D-6376');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '29', 'D-6489');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '33', 'D-6593');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '7', '37', 'D-6696');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '8', '20', 'D-3121');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '8', '23', 'D-3227');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '8', '25', 'D-3333');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '8', '21', 'D-3446');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '8', '24', 'D-3558');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '8', '26', 'D-3667');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '13', 'D-7117');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '15', 'D-7220');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '17', 'D-7327');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '14', 'D-7439');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '16', 'D-7544');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '18', 'D-7658');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '2', 'D-8133');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '6', 'D-8242');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '10', 'D-8346');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '4', 'D-8467');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '8', 'D-8578');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '12', 'D-8682');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '28', 'D-9151');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '32', 'D-9254');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '36', 'D-9360');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '30', 'D-9484');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '34', 'D-9585');
INSERT INTO jobpositioncategories (jobpositiontype_id, roleinjobposition_id, jobpositionlevel_id, administrative_key) VALUES ('2', '3', '38', 'D-9689');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,9,'C 01');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,10,'C 02');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,11,'C 03');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,12,'C 04');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,13,'C 05');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,14,'C 06');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,15,'C 07');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,16,'C 08');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,17,'C 09');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,18,'C 10');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,19,'C 11');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,20,'C 12');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,21,'C 13');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,22,'C 14');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,23,'C 15');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,24,'C 16');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,25,'C 17');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,26,'C 18');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,27,'C 19');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,28,'C 20');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,29,'C 21');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,30,'C 22');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,31,'C 23');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,32,'C 24');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,33,'C 25');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,34,'C 26');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,35,'C 27');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,36,'C 28');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,37,'C 29');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,38,'C 30');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,39,'C 31');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,40,'C 32');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,41,'C 33');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,42,'C 34');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,43,'C 35');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,44,'C 36');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,45,'C 37');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,46,'C 38');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,47,'C 39');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,48,'C 40');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,49,'C 41');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,50,'C 42');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,51,'C 43');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,52,'C 44');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,53,'C 45');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,54,'C 46');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,55,'C 47');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,56,'C 48');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,57,'C 49');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,58,'C 50');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,59,'C 51');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,60,'C 52');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,61,'C 54');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,62,'C 55');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,63,'C 56');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,64,'C 57');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,65,'C 58');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,66,'C 59');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,67,'C 60');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,68,'C 61');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,69,'C 62');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,70,'C 65');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,71,'C 66');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,72,'C 67');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,73,'C 68');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,74,'C 69');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,75,'C 70');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,76,'C 71');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,77,'C 72');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,78,'C 73');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,79,'C 74');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,80,'C 75');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,81,'C 76');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,82,'C 77');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,83,'C 79');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,84,'C 80');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,85,'C 81');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,86,'C 81');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,87,'C 82');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,88,'C 83');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,89,'C 85');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,90,'C 86');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,91,'C 87');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,92,'C 89');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,93,'C 90');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,94,'C 91');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,95,'C 92');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,96,'C 94');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,97,'C 95');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,98,'C 96');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,99,'C 97');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,100,'C 98');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,101,'C 99');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,102,'RC 01');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,103,'RC 02');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,104,'RC 04');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,105,'RC 05');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,106,'RC 06');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,107,'RC 07');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,108,'RC 08');
INSERT INTO  jobpositioncategories (jobpositiontype_id, roleinjobposition_id, administrative_key) VALUES (3,109,'RC 00');
