INSERT INTO newspapers (name, url) VALUES ('El Sur de Campeche', 'http://www.elsur.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('El Siglo de Torreón', 'http://www.elsiglodetorreon.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('El Hidrocálido', 'http://www.hidrocalido.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('El Diario de Delicias', 'http://www.eldiariodechihuahua.com.mx/regional/delicias/index.html');
INSERT INTO newspapers (name, url) VALUES ('El Norte', 'http://www.elnorte.com/edicionimpresa/');
INSERT INTO newspapers (name, url) VALUES ('El Informador', 'http://www.informador.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('La Jornada de Oriente', 'http://www.jornada.unam.mx/oriente/oriente.html');
INSERT INTO newspapers (name, url) VALUES ('La Jornada', 'http://www.jornada.unam.mx/');
INSERT INTO newspapers (name, url) VALUES ('Noroeste (Culiacán)', 'http://www.noroeste.com.mx/Culiacan/hoy/noroeste.php3');
INSERT INTO newspapers (name, url) VALUES ('Tabasco Hoy', 'http://www.tabascohoy.com.mx/th/nuevo/hoy.php');
INSERT INTO newspapers (name, url) VALUES ('Milenio Público (Guadalajara)', 'http://www.milenio.com/guadalajara/');
INSERT INTO newspapers (name, url) VALUES ('El Sur (Acapulco)', 'http://www.suracapulco.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('El Imparcial (Oaxaca)', 'http://www.imparoax.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('Cuarto Poder', 'http://www.cuarto-poder.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('El Diario de Colima', 'http://www.diariodecolima.com/palm.asp');
INSERT INTO newspapers (name, url) VALUES ('A.M. (Guanajuato)', 'http://www.am.com.mx');
INSERT INTO newspapers (name, url) VALUES ('Noroeste (Mazatlán)', 'http://www.noroeste.com/');
INSERT INTO newspapers (name, url) VALUES ('El Imparcial (Sonora)', 'http://www.elimparcial.com/EdicionImpresa/Hoy/General/Home.asp');
INSERT INTO newspapers (name, url) VALUES ('El Diario de Chihuahua', 'http://www.eldiariodechihuahua.com.mx/edicion/impresa/index.html');
INSERT INTO newspapers (name, url) VALUES ('El Financiero', 'http://www.elfinanciero.com.mx/pages/Home.asp?Show=CH');
INSERT INTO newspapers (name, url) VALUES ('Reforma', 'http://www.reforma.com/');
INSERT INTO newspapers (name, url) VALUES ('El Meridiano', 'http://www.meridiano.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('Pulso de San Luis Potosí', 'http://www.pulsoslp.com.mx/index.asp');
INSERT INTO newspapers (name, url) VALUES ('La Crónica', 'http://www.cronica.com.mx/welcome.php');
INSERT INTO newspapers (name, url) VALUES ('La Opinión de Veracruz', 'http://www.laopinion.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('Diario de Yucatán', 'http://edicion.yucatan.com.mx/noticias/portada.asp');
INSERT INTO newspapers (name, url) VALUES ('Imagen de Zacatecas', 'http://www.imagenzac.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('El Diario de Nuevo Laredo', 'http://www.diario.net/');
INSERT INTO newspapers (name, url) VALUES ('El Diario de Ciudad Juárez', 'http://www.diario.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('La Jornada de Morelos', 'http://lajornadamorelos.com/');
INSERT INTO newspapers (name, url) VALUES ('El Universal', 'http://www.eluniversal.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('Cambio de Michoacán', 'http://www.cambiodemichoacan.com.mx/');
INSERT INTO newspapers (name, url) VALUES ('La Crónica de Baja California', 'http://www.lacronica.com/EdicionImpresa/Hoy/General/Home.asp');
