INSERT INTO roleinjobpositions (name) VALUES ('Investigador ordinario de carrera');
INSERT INTO roleinjobpositions (name) VALUES ('Ayudante de investigador');
INSERT INTO roleinjobpositions (name) VALUES ('Técnico académico ordinario');
INSERT INTO roleinjobpositions (name) VALUES ('Profesor ordinario de asignatura');
INSERT INTO roleinjobpositions (name) VALUES ('Ayudante de profesor de asignatura');
INSERT INTO roleinjobpositions (name) VALUES ('Profesor de carrera de enseñanza media superior');
INSERT INTO roleinjobpositions (name) VALUES ('Profesor ordinario de carrera');
INSERT INTO roleinjobpositions (name) VALUES ('Ayudante de profesor');
INSERT INTO roleinjobpositions (name) VALUES ('Abogado Auxiliar');
INSERT INTO roleinjobpositions (name) VALUES ('Abogado General');
INSERT INTO roleinjobpositions (name) VALUES ('Administrador Técnico');
INSERT INTO roleinjobpositions (name) VALUES ('Arquitecto Residente');
INSERT INTO roleinjobpositions (name) VALUES ('Arquitecto Proyectista');
INSERT INTO roleinjobpositions (name) VALUES ('Director de Orquesta');
INSERT INTO roleinjobpositions (name) VALUES ('Asesor');
INSERT INTO roleinjobpositions (name) VALUES ('Asesor Contable');
INSERT INTO roleinjobpositions (name) VALUES ('Auditor Interno');
INSERT INTO roleinjobpositions (name) VALUES ('Auxiliar de Jefe de Departamento');
INSERT INTO roleinjobpositions (name) VALUES ('Ayudante de Director');
INSERT INTO roleinjobpositions (name) VALUES ('Ayudante de Unidad Administrativa');
INSERT INTO roleinjobpositions (name) VALUES ('Auditor B');
INSERT INTO roleinjobpositions (name) VALUES ('Cajero General');
INSERT INTO roleinjobpositions (name) VALUES ('Cajero Auxiliar');
INSERT INTO roleinjobpositions (name) VALUES ('Consejero');
INSERT INTO roleinjobpositions (name) VALUES ('Auditor A');
INSERT INTO roleinjobpositions (name) VALUES ('Auditor BB');
INSERT INTO roleinjobpositions (name) VALUES ('Auditor AA');
INSERT INTO roleinjobpositions (name) VALUES ('Contador');
INSERT INTO roleinjobpositions (name) VALUES ('Contador Auxiliar');
INSERT INTO roleinjobpositions (name) VALUES ('Contador General');
INSERT INTO roleinjobpositions (name) VALUES ('Productor');
INSERT INTO roleinjobpositions (name) VALUES ('Asistente de Productor');
INSERT INTO roleinjobpositions (name) VALUES ('Reportero');
INSERT INTO roleinjobpositions (name) VALUES ('Coordinador');
INSERT INTO roleinjobpositions (name) VALUES ('Coordinador de Bibliotecas');
INSERT INTO roleinjobpositions (name) VALUES ('Coordinador de Programa');
INSERT INTO roleinjobpositions (name) VALUES ('Coordinador de Cursos');
INSERT INTO roleinjobpositions (name) VALUES ('Subcoordinador');
INSERT INTO roleinjobpositions (name) VALUES ('Delegado');
INSERT INTO roleinjobpositions (name) VALUES ('Director');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario General');
INSERT INTO roleinjobpositions (name) VALUES ('Director de Seminario');
INSERT INTO roleinjobpositions (name) VALUES ('Director Auxiliar');
INSERT INTO roleinjobpositions (name) VALUES ('Director General');
INSERT INTO roleinjobpositions (name) VALUES ('Director Técnico');
INSERT INTO roleinjobpositions (name) VALUES ('Director de Area de Investigación ');
INSERT INTO roleinjobpositions (name) VALUES ('Entrenador');
INSERT INTO roleinjobpositions (name) VALUES ('Gerente');
INSERT INTO roleinjobpositions (name) VALUES ('Ingeniero Ayudante');
INSERT INTO roleinjobpositions (name) VALUES ('Ingeniero de Mantenimiento');
INSERT INTO roleinjobpositions (name) VALUES ('Engeniero Electrónico');
INSERT INTO roleinjobpositions (name) VALUES ('Coordinador de Proyectos');
INSERT INTO roleinjobpositions (name) VALUES ('Ingeniero Residente');
INSERT INTO roleinjobpositions (name) VALUES ('Subgerente');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Area');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Control');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Unidad');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Departamento');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Unidad Académica');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Departamento Técnico');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de División');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Estación');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Mantenimiento de Laboratorio');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Proyectistas');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Publicaciones');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Carrera');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario de Servicios a la Comunidad');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Sección Académica');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Seminario');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Unidad Administrativa');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Vigilancia');
INSERT INTO roleinjobpositions (name) VALUES ('Operador de Computadora');
INSERT INTO roleinjobpositions (name) VALUES ('Pagador Auxiliar');
INSERT INTO roleinjobpositions (name) VALUES ('Pagador General');
INSERT INTO roleinjobpositions (name) VALUES ('Proyectista');
INSERT INTO roleinjobpositions (name) VALUES ('Calculista');
INSERT INTO roleinjobpositions (name) VALUES ('Rector');
INSERT INTO roleinjobpositions (name) VALUES ('Residente');
INSERT INTO roleinjobpositions (name) VALUES ('Consultor Precios');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario Auxiliar');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario de Desarrollo Institucional');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario Administrativo');
INSERT INTO roleinjobpositions (name) VALUES ('Asistente Ejecutivo');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario Partícular');
INSERT INTO roleinjobpositions (name) VALUES ('Coordinador de Gestión');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario Académico');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario Técnico');
INSERT INTO roleinjobpositions (name) VALUES ('Subcontador');
INSERT INTO roleinjobpositions (name) VALUES ('Subcontador Auxiliar');
INSERT INTO roleinjobpositions (name) VALUES ('Subdirector');
INSERT INTO roleinjobpositions (name) VALUES ('Subauditor');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario de la Dirección');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario Adjunto');
INSERT INTO roleinjobpositions (name) VALUES ('Secretario Privado');
INSERT INTO roleinjobpositions (name) VALUES ('Subjefe de Departamento');
INSERT INTO roleinjobpositions (name) VALUES ('Subjefe de División');
INSERT INTO roleinjobpositions (name) VALUES ('Superintendente de Obras');
INSERT INTO roleinjobpositions (name) VALUES ('Comprador');
INSERT INTO roleinjobpositions (name) VALUES ('Asistente de Procesos');
INSERT INTO roleinjobpositions (name) VALUES ('Tesorero');
INSERT INTO roleinjobpositions (name) VALUES ('Capitan de Buques');
INSERT INTO roleinjobpositions (name) VALUES ('Jefe de Máquinas de Buque');
INSERT INTO roleinjobpositions (name) VALUES ('Primer Oficial Técnico Marino');
INSERT INTO roleinjobpositions (name) VALUES ('Primer Oficial de Cubierta');
INSERT INTO roleinjobpositions (name) VALUES ('Primero Oficial de Máquinas');
INSERT INTO roleinjobpositions (name) VALUES ('Segundo Oficial de Cubierta');
INSERT INTO roleinjobpositions (name) VALUES ('Segundo Oficial de Máquinas');
INSERT INTO roleinjobpositions (name) VALUES ('Supervisor de Escuelas Incorporadas');
