INSERT INTO states (country_id, name) VALUES (484, 'Aguascalientes');
INSERT INTO states (country_id, name) VALUES (484, 'Baja California Norte');
INSERT INTO states (country_id, name) VALUES (484, 'Baja California Sur');
INSERT INTO states (country_id, name) VALUES (484, 'Campeche');
INSERT INTO states (country_id, name) VALUES (484, 'Chiapas');
INSERT INTO states (country_id, name) VALUES (484, 'Chihuahua');
INSERT INTO states (country_id, name) VALUES (484, 'Coahuila');
INSERT INTO states (country_id, name) VALUES (484, 'Colima');
INSERT INTO states (country_id, name) VALUES (484, 'Distrito Federal');
INSERT INTO states (country_id, name) VALUES (484, 'Durango');
INSERT INTO states (country_id, name) VALUES (484, 'Estado de México');
INSERT INTO states (country_id, name) VALUES (484, 'Guanajuato');
INSERT INTO states (country_id, name) VALUES (484, 'Guerrero');
INSERT INTO states (country_id, name) VALUES (484, 'Hidalgo');
INSERT INTO states (country_id, name) VALUES (484, 'Jalisco');
INSERT INTO states (country_id, name) VALUES (484, 'Michoacan');
INSERT INTO states (country_id, name) VALUES (484, 'Morelos');
INSERT INTO states (country_id, name) VALUES (484, 'Nayarit');
INSERT INTO states (country_id, name) VALUES (484, 'Nuevo León');
INSERT INTO states (country_id, name) VALUES (484, 'Oaxaca');
INSERT INTO states (country_id, name) VALUES (484, 'Puebla');
INSERT INTO states (country_id, name) VALUES (484, 'Queretaro');
INSERT INTO states (country_id, name) VALUES (484, 'Quintana Roo');
INSERT INTO states (country_id, name) VALUES (484, 'San Luis Potosí');
INSERT INTO states (country_id, name) VALUES (484, 'Sinaloa');
INSERT INTO states (country_id, name) VALUES (484, 'Sonora');
INSERT INTO states (country_id, name) VALUES (484, 'Tabasco');
INSERT INTO states (country_id, name) VALUES (484, 'Tamaulipas');
INSERT INTO states (country_id, name) VALUES (484, 'Tlaxcala');
INSERT INTO states (country_id, name) VALUES (484, 'Veracruz');
INSERT INTO states (country_id, name) VALUES (484, 'Yucatán');
INSERT INTO states (country_id, name) VALUES (484, 'Zacatecas');
