INSERT INTO stimulustypes (name, descr, institution_id) VALUES ('PAIPA', 'Programa de Apoyo a la Incorporación de Personal Académico', 5603);
INSERT INTO stimulustypes (name, descr, institution_id) VALUES ('PRIDE', 'Programa de Reconocimiento a la Investigación y Desarrollo Académico', 5603);
INSERT INTO stimulustypes (name, descr, institution_id) VALUES ('SNI', 'Sistema Nacional de Investigadores', 5453);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('A',1);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('B',1);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('C',1);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('D',1);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('A',2);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('B',2);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('C',2);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('D',2);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('E',2);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('I',3);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('II',3);
INSERT INTO stimuluslevels (name, stimulustype_id) VALUES ('III',3);
