INSERT INTO careers (name,degree_id) VALUES ('Actuaria',3);
INSERT INTO careers (name,degree_id) VALUES ('Administración',3);
INSERT INTO careers (name,degree_id) VALUES ('Arquitectura del Paisaje',3);
INSERT INTO careers (name,degree_id) VALUES ('Arquitectura',3);
INSERT INTO careers (name,degree_id) VALUES ('Artes Visuales',3);
INSERT INTO careers (name,degree_id) VALUES ('Bibliotecología',3);
INSERT INTO careers (name,degree_id) VALUES ('Biología',3);
INSERT INTO careers (name,degree_id) VALUES ('Canto',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias Políticas y Administración Pública - Opción Administración Pública',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias de la Computación',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias de la Comunicación',3);
INSERT INTO careers (name,degree_id) VALUES ('Cirujano Dentista (Odontología)',3);
INSERT INTO careers (name,degree_id) VALUES ('Composición',3);
INSERT INTO careers (name,degree_id) VALUES ('Comunicación Gráfica',3);
INSERT INTO careers (name,degree_id) VALUES ('Contaduría',3);
INSERT INTO careers (name,degree_id) VALUES ('Derecho',3);
INSERT INTO careers (name,degree_id) VALUES ('Diseño Gráfico',3);
INSERT INTO careers (name,degree_id) VALUES ('Diseño Industrial',3);
INSERT INTO careers (name,degree_id) VALUES ('Economía',3);
INSERT INTO careers (name,degree_id) VALUES ('Educación Musical',3);
INSERT INTO careers (name,degree_id) VALUES ('Enfermería y Obstetricia',3);
INSERT INTO careers (name,degree_id) VALUES ('Enseñanza del Inglés',3);
INSERT INTO careers (name,degree_id) VALUES ('Estudios Latinomericanos',3);
INSERT INTO careers (name,degree_id) VALUES ('Etnomusicología',3);
INSERT INTO careers (name,degree_id) VALUES ('Filosofía',3);
INSERT INTO careers (name,degree_id) VALUES ('Física',3);
INSERT INTO careers (name,degree_id) VALUES ('Geografía',3);
INSERT INTO careers (name,degree_id) VALUES ('Historia',3);
INSERT INTO careers (name,degree_id) VALUES ('Informática',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Agrícola',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Civil',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Eléctrica y Electrónica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Geofísica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Geológica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Industrial',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Mecánica Eléctrica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Mecánica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Petrolera',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Química Metalúrgica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Química',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería Topográfica y Geodésica',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería de Minas y Metalurgía',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería en Alimentos',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería en Computación',3);
INSERT INTO careers (name,degree_id) VALUES ('Ingeniería en Telecomunicaciones',3);
INSERT INTO careers (name,degree_id) VALUES ('Instrumentista',3);
INSERT INTO careers (name,degree_id) VALUES ('Investigación Biomédica Básica',3);
INSERT INTO careers (name,degree_id) VALUES ('Lengua y Literaturas Hispánicas',3);
INSERT INTO careers (name,degree_id) VALUES ('Lengua y Literaturas Modernas',3);
INSERT INTO careers (name,degree_id) VALUES ('Letras Clásicas',3);
INSERT INTO careers (name,degree_id) VALUES ('Literatura Dramática y Teatro',3);
INSERT INTO careers (name,degree_id) VALUES ('Matemáticas Aplicadas y Computación',3);
INSERT INTO careers (name,degree_id) VALUES ('Matemáticas',3);
INSERT INTO careers (name,degree_id) VALUES ('Medicina Veterinaria y Zootecnia',3);
INSERT INTO careers (name,degree_id) VALUES ('Medicina',3);
INSERT INTO careers (name,degree_id) VALUES ('Optometría',3);
INSERT INTO careers (name,degree_id) VALUES ('Pedagogía',3);
INSERT INTO careers (name,degree_id) VALUES ('Periodismo y Comunicación Colectiva',3);
INSERT INTO careers (name,degree_id) VALUES ('Piano',3);
INSERT INTO careers (name,degree_id) VALUES ('Planificación para el Desarrollo Agropecuario',3);
INSERT INTO careers (name,degree_id) VALUES ('Psicología',3);
INSERT INTO careers (name,degree_id) VALUES ('Química Farmacéutico Biológica',3);
INSERT INTO careers (name,degree_id) VALUES ('Química Industrial',3);
INSERT INTO careers (name,degree_id) VALUES ('Química de Alimentos',3);
INSERT INTO careers (name,degree_id) VALUES ('Química',3);
INSERT INTO careers (name,degree_id) VALUES ('Relaciones Internacionales',3);
INSERT INTO careers (name,degree_id) VALUES ('Sociología',3);
INSERT INTO careers (name,degree_id) VALUES ('Trabajo Social',3);
INSERT INTO careers (name,degree_id) VALUES ('Urbanismo',3);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias Políticas y Administración Pública - Opción Ciencia Política',3);      
INSERT INTO careers (name, degree_id) VALUES ('Antropología', 5);
INSERT INTO careers (name, degree_id) VALUES ('Arquitectura', 5);
INSERT INTO careers (name, degree_id) VALUES ('Bibliotecología y Estudios de la Información', 5);
INSERT INTO careers (name, degree_id) VALUES ('Astronomía', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias e Ingeniería de Materiales', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Biológicas', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Bioquímicas', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias de la Administración', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias de la Producción y Salud Animal', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias de la Tierra', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Matemáticas y de la Especialización en Estadística Aplicada', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias del Mar y Limnología', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencia e Ingeniería de la Computación', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Físicas', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Médicas Odontológicas y de la Salud', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Políticas y Sociales', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Químicas', 5);
INSERT INTO careers (name, degree_id) VALUES ('Economía', 5);
INSERT INTO careers (name, degree_id) VALUES ('Estudios Latinoamericanos', 5);
INSERT INTO careers (name, degree_id) VALUES ('Estudios Mesoamericanos', 5);
INSERT INTO careers (name, degree_id) VALUES ('Filosofía', 5);
INSERT INTO careers (name, degree_id) VALUES ('Filosofía de la Ciencia', 5);
INSERT INTO careers (name, degree_id) VALUES ('Geografía', 5);
INSERT INTO careers (name, degree_id) VALUES ('Historia', 5);
INSERT INTO careers (name, degree_id) VALUES ('Ingeniería', 5);
INSERT INTO careers (name, degree_id) VALUES ('Letras', 5);
INSERT INTO careers (name, degree_id) VALUES ('Lingüística', 5);
INSERT INTO careers (name, degree_id) VALUES ('Música', 5);
INSERT INTO careers (name, degree_id) VALUES ('Pedagogía', 5);
INSERT INTO careers (name, degree_id) VALUES ('Psicología', 5);
INSERT INTO careers (name, degree_id) VALUES ('Urbanismo', 5);
INSERT INTO careers (name, degree_id) VALUES ('Artes visuales', 5);
INSERT INTO careers (name, degree_id) VALUES ('Diseño Industrial', 5);
INSERT INTO careers (name, degree_id) VALUES ('Docencia para la Educación Media Superior', 5);
INSERT INTO careers (name, degree_id) VALUES ('Enfermería', 5);
INSERT INTO careers (name, degree_id) VALUES ('Neurobiología', 5);
INSERT INTO careers (name, degree_id) VALUES ('Trabajo Social', 5);
INSERT INTO careers (name, degree_id) VALUES ('Maestrías y Doctorados', 6);
INSERT INTO careers (name, degree_id) VALUES ('Antropología', 6);
INSERT INTO careers (name, degree_id) VALUES ('Arquitectura', 6);
INSERT INTO careers (name, degree_id) VALUES ('Bibliotecología y Estudios de la Información', 6);
INSERT INTO careers (name, degree_id) VALUES ('Astronomía', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias e Ingeniería de Materiales', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Biológicas', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Bioquímicas', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias de la Administración', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias de la Producción y Salud Animal', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias de la Tierra', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Matemáticas y de la Especialización en Estadística Aplicada', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias del Mar y Limnología', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencia e Ingeniería de la Computación', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Físicas', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Médicas Odontológicas y de la Salud', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Políticas y Sociales', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Químicas', 6);
INSERT INTO careers (name, degree_id) VALUES ('Economía', 6);
INSERT INTO careers (name, degree_id) VALUES ('Estudios Latinoamericanos', 6);
INSERT INTO careers (name, degree_id) VALUES ('Estudios Mesoamericanos', 6);
INSERT INTO careers (name, degree_id) VALUES ('Filosofía', 6);
INSERT INTO careers (name, degree_id) VALUES ('Filosofía de la Ciencia', 6);
INSERT INTO careers (name, degree_id) VALUES ('Geografía', 6);
INSERT INTO careers (name, degree_id) VALUES ('Historia', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ingeniería', 6);
INSERT INTO careers (name, degree_id) VALUES ('Letras', 6);
INSERT INTO careers (name, degree_id) VALUES ('Lingüística', 6);
INSERT INTO careers (name, degree_id) VALUES ('Música', 6);
INSERT INTO careers (name, degree_id) VALUES ('Pedagogía', 6);
INSERT INTO careers (name, degree_id) VALUES ('Psicología', 6);
INSERT INTO careers (name, degree_id) VALUES ('Urbanismo', 6);
INSERT INTO careers (name, degree_id) VALUES ('Ciencias Biomédicas', 6);
