INSERT INTO newspapers (name, url, country_id) VALUES ('El Sur de Campeche', 'http://www.elsur.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Siglo de Torreón', 'http://www.elsiglodetorreon.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Hidrocálido', 'http://www.hidrocalido.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Diario de Delicias', 'http://www.eldiariodechihuahua.com.mx/regional/delicias/index.html', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Norte', 'http://www.elnorte.com/edicionimpresa/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Informador', 'http://www.informador.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('La Jornada de Oriente', 'http://www.jornada.unam.mx/oriente/oriente.html', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('La Jornada', 'http://www.jornada.unam.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Noroeste (Culiacán)', 'http://www.noroeste.com.mx/Culiacan/hoy/noroeste.php3', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Tabasco Hoy', 'http://www.tabascohoy.com.mx/th/nuevo/hoy.php', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Milenio Público (Guadalajara)', 'http://www.milenio.com/guadalajara/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Sur (Acapulco)', 'http://www.suracapulco.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Imparcial (Oaxaca)', 'http://www.imparoax.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Cuarto Poder', 'http://www.cuarto-poder.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Diario de Colima', 'http://www.diariodecolima.com/palm.asp', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('A.M. (Guanajuato)', 'http://www.am.com.mx', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Noroeste (Mazatlán)', 'http://www.noroeste.com/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Imparcial (Sonora)', 'http://www.elimparcial.com/EdicionImpresa/Hoy/General/Home.asp', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Diario de Chihuahua', 'http://www.eldiariodechihuahua.com.mx/edicion/impresa/index.html', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Financiero', 'http://www.elfinanciero.com.mx/pages/Home.asp?Show=CH', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Reforma', 'http://www.reforma.com/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Meridiano', 'http://www.meridiano.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Pulso de San Luis Potosí', 'http://www.pulsoslp.com.mx/index.asp', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('La Crónica', 'http://www.cronica.com.mx/welcome.php', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('La Opinión de Veracruz', 'http://www.laopinion.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Diario de Yucatán', 'http://edicion.yucatan.com.mx/noticias/portada.asp', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Imagen de Zacatecas', 'http://www.imagenzac.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Diario de Nuevo Laredo', 'http://www.diario.net/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Diario de Ciudad Juárez', 'http://www.diario.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('La Jornada de Morelos', 'http://lajornadamorelos.com/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('El Universal', 'http://www.eluniversal.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('Cambio de Michoacán', 'http://www.cambiodemichoacan.com.mx/', 484);
INSERT INTO newspapers (name, url, country_id) VALUES ('La Crónica de Baja California', 'http://www.lacronica.com/EdicionImpresa/Hoy/General/Home.asp', 484);
