INSERT INTO states (country_id, name) VALUES (484, 'Aguascalientes');
INSERT INTO states (country_id, name) VALUES (484, 'Baja California Norte');
INSERT INTO states (country_id, name) VALUES (484, 'Baja California Sur');
INSERT INTO states (country_id, name) VALUES (484, 'Campeche');
INSERT INTO states (country_id, name) VALUES (484, 'Chiapas');
INSERT INTO states (country_id, name) VALUES (484, 'Chihuahua');
INSERT INTO states (country_id, name) VALUES (484, 'Coahuila');
INSERT INTO states (country_id, name) VALUES (484, 'Colima');
INSERT INTO states (country_id, name) VALUES (484, 'Distrito Federal');
INSERT INTO states (country_id, name) VALUES (484, 'Durango');
INSERT INTO states (country_id, name) VALUES (484, 'Estado de México');
INSERT INTO states (country_id, name) VALUES (484, 'Guanajuato');
INSERT INTO states (country_id, name) VALUES (484, 'Guerrero');
INSERT INTO states (country_id, name) VALUES (484, 'Hidalgo');
INSERT INTO states (country_id, name) VALUES (484, 'Jalisco');
INSERT INTO states (country_id, name) VALUES (484, 'Michoacan');
INSERT INTO states (country_id, name) VALUES (484, 'Morelos');
INSERT INTO states (country_id, name) VALUES (484, 'Nayarit');
INSERT INTO states (country_id, name) VALUES (484, 'Nuevo León');
INSERT INTO states (country_id, name) VALUES (484, 'Oaxaca');
INSERT INTO states (country_id, name) VALUES (484, 'Puebla');
INSERT INTO states (country_id, name) VALUES (484, 'Queretaro');
INSERT INTO states (country_id, name) VALUES (484, 'Quintana Roo');
INSERT INTO states (country_id, name) VALUES (484, 'San Luis Potosí');
INSERT INTO states (country_id, name) VALUES (484, 'Sinaloa');
INSERT INTO states (country_id, name) VALUES (484, 'Sonora');
INSERT INTO states (country_id, name) VALUES (484, 'Tabasco');
INSERT INTO states (country_id, name) VALUES (484, 'Tamaulipas');
INSERT INTO states (country_id, name) VALUES (484, 'Tlaxcala');
INSERT INTO states (country_id, name) VALUES (484, 'Veracruz');
INSERT INTO states (country_id, name) VALUES (484, 'Yucatán');
INSERT INTO states (country_id, name) VALUES (484, 'Zacatecas');
INSERT INTO states (country_id, name, code) VALUES (840, 'Alabama', 'AL');
INSERT INTO states (country_id, name, code) VALUES (840, 'Alaska', 'AK');
INSERT INTO states (country_id, name, code) VALUES (840, 'Arizona', 'AZ');
INSERT INTO states (country_id, name, code) VALUES (840, 'Arkansas', 'AR');
INSERT INTO states (country_id, name, code) VALUES (840, 'California', 'CA');
INSERT INTO states (country_id, name, code) VALUES (840, 'Colorado', 'CO');
INSERT INTO states (country_id, name, code) VALUES (840, 'Connecticut', 'CT');
INSERT INTO states (country_id, name, code) VALUES (840, 'Delaware', 'DE');
INSERT INTO states (country_id, name, code) VALUES (840, 'Florida', 'FL');
INSERT INTO states (country_id, name, code) VALUES (840, 'Georgia', 'GA');
INSERT INTO states (country_id, name, code) VALUES (840, 'Hawaii', 'HI');
INSERT INTO states (country_id, name, code) VALUES (840, 'Idaho', 'ID');
INSERT INTO states (country_id, name, code) VALUES (840, 'Illinois', 'IL');
INSERT INTO states (country_id, name, code) VALUES (840, 'Indiana', 'IN');
INSERT INTO states (country_id, name, code) VALUES (840, 'Iowa', 'IA');
INSERT INTO states (country_id, name, code) VALUES (840, 'Kansas', 'KS');
INSERT INTO states (country_id, name, code) VALUES (840, 'Kentucky', 'KY');
INSERT INTO states (country_id, name, code) VALUES (840, 'Louisiana', 'LA');
INSERT INTO states (country_id, name, code) VALUES (840, 'Maine', 'ME');
INSERT INTO states (country_id, name, code) VALUES (840, 'Maryland', 'MD');
INSERT INTO states (country_id, name, code) VALUES (840, 'Massachusetts', 'MA');
INSERT INTO states (country_id, name, code) VALUES (840, 'Michigan', 'MI');
INSERT INTO states (country_id, name, code) VALUES (840, 'Minnesota', 'MN');
INSERT INTO states (country_id, name, code) VALUES (840, 'Mississippi', 'MS');
INSERT INTO states (country_id, name, code) VALUES (840, 'Missouri', 'MO');
INSERT INTO states (country_id, name, code) VALUES (840, 'Montana', 'MT');
INSERT INTO states (country_id, name, code) VALUES (840, 'Nebraska', 'NE');
INSERT INTO states (country_id, name, code) VALUES (840, 'Nevada', 'NV');
INSERT INTO states (country_id, name, code) VALUES (840, 'New Hampshire', 'NH');
INSERT INTO states (country_id, name, code) VALUES (840, 'New Jersey', 'NJ');
INSERT INTO states (country_id, name, code) VALUES (840, 'New Mexico', 'NM');
INSERT INTO states (country_id, name, code) VALUES (840, 'New York', 'NY');
INSERT INTO states (country_id, name, code) VALUES (840, 'North Carolina', 'NC');
INSERT INTO states (country_id, name, code) VALUES (840, 'North Dakota', 'ND');
INSERT INTO states (country_id, name, code) VALUES (840, 'Ohio', 'OH');
INSERT INTO states (country_id, name, code) VALUES (840, 'Oklahoma', 'OK');
INSERT INTO states (country_id, name, code) VALUES (840, 'Oregon', 'OR');
INSERT INTO states (country_id, name, code) VALUES (840, 'Pennsylvania', 'PA');
INSERT INTO states (country_id, name, code) VALUES (840, 'Rhode Island', 'RI');
INSERT INTO states (country_id, name, code) VALUES (840, 'South Carolina', 'SC');
INSERT INTO states (country_id, name, code) VALUES (840, 'South Dakota', 'SD');
INSERT INTO states (country_id, name, code) VALUES (840, 'Tennessee', 'TN');
INSERT INTO states (country_id, name, code) VALUES (840, 'Texas', 'TX');
INSERT INTO states (country_id, name, code) VALUES (840, 'Utah', 'UT');
INSERT INTO states (country_id, name, code) VALUES (840, 'Vermont', 'VT');
INSERT INTO states (country_id, name, code) VALUES (840, 'Virginia', 'VA');
INSERT INTO states (country_id, name, code) VALUES (840, 'Washington', 'WA');
INSERT INTO states (country_id, name, code) VALUES (840, 'West Virginia', 'WV');
INSERT INTO states (country_id, name, code) VALUES (840, 'Wisconsin', 'WI');
INSERT INTO states (country_id, name, code) VALUES (840, 'Wyoming', 'WY');
