INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Aerobiología', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Aerosoles atmosféricos', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Citogenética ambiental', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Contaminación ambiental', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Fisicoquímica atmosférica', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Mutagénesis ambiental', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Química atmosférica', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Bioclimatología', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Cambio climático y radiación solar', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Climatología física', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Física de nubes', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Interacción micro y mesoescala', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Meteorología tropical', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Meteorología urbana', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Modelos climáticos', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Modelación matemática de procesos atmosféricos', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Instrumentación Meteorológica', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Cómputo', '', '', 57, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Sección Editorial', '', '', 57, '');
