INSERT INTO researchareas (name) VALUES ('Física del Clima');
INSERT INTO researchareas (name) VALUES ('Cambio y Variabilidad Climática');
INSERT INTO researchareas (name) VALUES ('Climatología Dinámica');
INSERT INTO researchareas (name) VALUES ('Meteorología Tropical');
INSERT INTO researchareas (name) VALUES ('Climatología Urbana');
INSERT INTO researchareas (name) VALUES ('Transferencia de Radiación');
INSERT INTO researchareas (name) VALUES ('Física de Nubes y de Aerosoles');
INSERT INTO researchareas (name) VALUES ('Interacción Micro y Mesoescala');
INSERT INTO researchareas (name) VALUES ('Modelación Atmosférica');
INSERT INTO researchareas (name) VALUES ('Bioclimatología y Electricidad Atmosférica');
INSERT INTO researchareas (name) VALUES ('Química Atmosférica'); 
INSERT INTO researchareas (name) VALUES ('Físico-Química Atmosférica');
INSERT INTO researchareas (name) VALUES ('Contaminación Ambiental'); 
INSERT INTO researchareas (name) VALUES ('Aerobiología'); 
INSERT INTO researchareas (name) VALUES ('Citogenética Ambiental');
INSERT INTO researchareas (name) VALUES ('Mutagénesis Ambiental');
