INSERT INTO institutions (name, url, abbrev, parent_id, institutiontype_id, institutiontitle_id, address, country_id, state_id, city, zipcode, phone, fax, administrative_key, other) VALUES ('Universidad Nacional Autónoma de México', 'http://www.unam.mx', 'UNAM', NULL, 1, 1, 'Ciudad Universitaria, Delegación Coyoacán', 484, 9, 'Ciudad de México', '04510', NULL, NULL, NULL, NULL);
INSERT INTO institutions (name, url, abbrev, parent_id, institutiontype_id, institutiontitle_id, address, country_id, state_id, city, zipcode, phone, fax, administrative_key, other) VALUES ('Instituto de Física', 'http://www.fisica.unam.mx', 'IFUNAM', 1, 1, 4, 'Circuito de la Investigación Cientifíca S/N, Ciudad Universitaria, Delegación Coyoacán', 484, 9, 'Ciudad de México', '04510', '56-65-72-63, 56-22-50-32', '56-16-15-35', '314-1', NULL);
INSERT INTO institutions (administrative_key, name, parent_id, abbrev, url, institutiontype_id, institutiontitle_id,address, country_id, state_id, city, zipcode, phone, fax,other) VALUES (NULL,'Universidad Nacional Autonoma de MÃxico', NULL, 'UNAM', 'http://www.unam.mx', 1, 1, 'Ciudad universitaria', 484, 1, NULL, NULL, NULL, NULL);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74401,'Direcci&oacute;n General de Finanzas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74501,'Unidad de Coordinaci&oacute;n de Tesorer&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74601,'Direcci&oacute;n General de Responsabilidades, Inconformidades y Registro Patrimonial',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74701,'Unidad de Coordinaci&oacute;n de la Contralor&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74801,'Direcci&oacute;n General de Presupuesto',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (75101,'Oficina del Rector',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (752,'Oficina del Secretario General',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (75301,'Oficina del Secretario Administrativo',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (75401,'Oficina del Secretario de Servicios a la Comunidad Universitaria',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (75501,'Oficina del Abogado General',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (75601,'Oficina del Tesorero',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (75701,'Oficina del Contralor',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (75801,'Oficina del Secretario de Desarrollo Institucional',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (77101,'Direcci&oacute;n General de Obras y Conservaci&oacute;n',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (78101,'Unidad Coordinadora de Servicios Institucionales',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45101,'Direcci&oacute;n General de la Escuela Nacional Preparatoria',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45201,'Plantel 1 Gabino Barreda',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45202,'Plantel 2 Erasmo Castellanos Quinto',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45203,'Plantel 3 Justo Sierra',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45204,'Plantel 4 Vidal Casta&ntilde;eda y N&aacute;jera',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45205,'Plantel 5 Jos&eacute; Vasconcelos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45206,'Plantel 6 Antonio Caso',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45207,'Plantel 7 Ezequiel A. Ch&aacute;vez',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45208,'Plantel 8 Miguel E. Schultz',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45209,'Plantel 9 Pedro de Alba',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (47201,'Direcci&oacute;n General del Colegio de Ciencias y Humanidades',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (47202,'Plantel Azcapotzalco',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (47203,'Plantel Naucalpan',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (47204,'Plantel Vallejo',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (47205,'Plantel Oriente',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (47206,'Plantel Sur',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (43201,'Escuela Nacional de Artes Pl&aacute;sticas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (434,'Escuela Nacional de Enfermer&iacute;a y Obstetricia',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (43501,'Escuela Nacional de M&uacute;sica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (43601,'Escuela Nacional de Trabajo Social',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (424,'Facultad de Arquitectura',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (411,'Facultad de Ciencias',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (412,'Facultad de Ciencias Pol&iacute;ticas y Sociales',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (413,'Facultad de Contadur&iacute;a y Administraci&oacute;n',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (414,'Facultad de Derecho',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (423,'Facultad de Econom&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (415,'Facultad de Filosof&iacute;a y Letras',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (416,'Facultad de Ingenier&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (417,'Facultad de Medicina',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (419,'Facultad de Medicina Veterinaria y Zootecnia',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (421,'Facultad de Odontolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (422,'Facultad de Psicolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (418,'Facultad de Qu&iacute;mica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (44201,'Escuela Nacional de Estudios Profesionales Acatl&aacute;n',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (44401,'Escuela Nacional de Estudios Profesionales Arag&oacute;n',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (44301,'Facultad de Estudios Superiores Iztacala',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (44101,'Facultad de Estudios Superiores Cuautitl&aacute;n',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (44501,'Facultad de Estudios Superiores Zaragoza',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (481,'Coordinaci&oacute;n del Sistema de Universidad Abierta',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31101,'Consejo T&eacute;cnico y Coordinaci&oacute;n de la Investigaci&oacute;n Cient&iacute;fica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31102,'Centro de Ciencias de la Atm&oacute;sfera',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31106,'Centro de Ciencias de la Materia Condensada en Ensenada, B.C.',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31105,'Centro de Ciencias Aplicadas y Desarrollo Tecnol&oacute;gico',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31108,'Centro de Investigaci&oacute;n en Energ&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31103,'Centro de Investigaci&oacute;n sobre Fijaci&oacute;n de Nitr&oacute;geno',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (33101,'Instituto de Neurobiolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (312,'Instituto de Astronom&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (313,'Instituto de Biolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (32801,'Instituto de Biotecnolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (325,'Instituto de Ciencias del Mar y Limnolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (32701,'Instituto de Ciencias Nucleares',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (329,'Instituto de Ecolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (314,'Instituto de F&iacute;sica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (32601,'Instituto de Fisiolog&iacute;a Celular',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (315,'Instituto de Geof&iacute;sica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31601,'Instituto de Geograf&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (317,'Instituto de Geolog&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (32301,'Instituto de Ingenier&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31801,'Instituto de Investigaciones Biom&eacute;dicas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (32201,'Instituto de Investigaciones en Matem&aacute;ticas Aplicadas y en Sistemas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (32401,'Instituto de Investigaciones en Materiales',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (319,'Instituto de Matem&aacute;ticas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (32101,'Instituto de Qu&iacute;mica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21101,'Coordinaci&oacute;n y Consejo T&eacute;cnico de Humanidades',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21105,'Centro Coordinador y Difusor de Estudios Latinoamericanos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21102,'Centro de Estudios sobre la Universidad',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21103,'Centro de Investigaciones Interdisciplinarias en Ciencias y Humanidades',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21107,'Centro de Investigaciones sobre Am&eacute;rica del Norte',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21106,'Centro Regional de Investigaciones Multidisciplinarias',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21104,'Centro Universitario de Investigaciones Bibliotecol&oacute;gicas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (221,'Instituto de Investigaciones Antropol&oacute;gicas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (212,'Instituto de Investigaciones Bibliogr&aacute;ficas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21301,'Instituto de Investigaciones Econ&oacute;micas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21401,'Instituto de Investigaciones Est&eacute;ticas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21901,'Instituto de Investigaciones Filol&oacute;gicas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21501,'Instituto de Investigaciones Filos&oacute;ficas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21601,'Instituto de Investigaciones Hist&oacute;ricas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21701,'Instituto de Investigaciones Jur&iacute;dicas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21801,'Instituto de Investigaciones Sociales',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31107,'Centro de Ciencias F&iacute;sicas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (42901,'Proyectos de Investigaci&oacute;n, de Innovaci&oacute;n Tecnol&oacute;gica y de Mejoramiento de la Ense&ntilde;anza en Facultades',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (45901,'Proyectos de Investigaci&oacute;n y Mejoramiento de la Ense&ntilde;anza en el Bachillerato',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (21109,'Programa Universitario de Estudios de G&eacute;nero',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31118,'Centro de F&iacute;sica Aplicada y Tecnolog&iacute;a Avanzada en Juriquilla, Qro.',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31109,'Centro de Geociencias en Juriquilla, Qro.',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (51101,'Oficina de Colaboraci&oacute;n Interinstitucional',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (51201,'Unidad Coordinadora de Servicios Acad&eacute;micos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (513,'Direcci&oacute;n General de Estudios de Posgrado',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (51501,'Oficina del Consejo Acad&eacute;mico del Bachillerato',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (51901,'Direcci&oacute;n General de Evaluaci&oacute;n Educativa',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (71201,'Direcci&oacute;n General de Planeaci&oacute;n',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (522,'Direcci&oacute;n General de Servicios de C&oacute;mputo Acad&eacute;mico',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (52301,'Direcci&oacute;n General de Asuntos del Personal Acad&eacute;mico',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (52601,'Unidad para el Desarrollo de Planes y Programas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (52701,'Coordinaci&oacute;n de Servicios Administrativos en Juriquilla, Qro.',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (52901,'Coordinaci&oacute;n de Servicios Administrativos en Morelia, Mich.',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (53201,'Coordinaci&oacute;n de Vinculaci&oacute;n con el Consejo Universitario',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (55101,'Direcci&oacute;n General de Incorporaci&oacute;n y Revalidaci&oacute;n de Estudios',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (55201,'Direcci&oacute;n General de Orientaci&oacute;n y Servicios Educativos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (55301,'Direcci&oacute;n General de Administraci&oacute;n Escolar',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (55401,'Unidad Coordinadora de Vinculaci&oacute;n con Egresados',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (56201,'Direcci&oacute;n General de Actividades Deportivas y Recreativas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (56301,'Direcci&oacute;n General de Servicios M&eacute;dicos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (56401,'Direcci&oacute;n General de Bibliotecas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (56501,'Direcci&oacute;n General de Atenci&oacute;n a la Comunidad Universitaria',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (61101,'Coordinaci&oacute;n de Difusi&oacute;n Cultural',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (61201,'Centro de Ense&ntilde;anza de Lenguas Extranjeras',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (613,'Centro de Ense&ntilde;anza para Extranjeros',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (61401,'Centro Universitario de Estudios Cinematogr&aacute;ficos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (61501,'Centro Universitario de Teatro',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (61601,'Caga del Lago Maestro Juan Jos&eacute; Arreola',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (61701,'Museo Universitario del Chopo',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (62101,'Direcci&oacute;n General de Artes Pl&aacute;sticas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (62201,'Direcci&oacute;n General de M&uacute;sica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (62301,'Direcci&oacute;n General de Actividades Cinematogr&aacute;ficas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (62401,'Direcci&oacute;n de Literatura',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (62501,'Direcci&oacute;n de Teatro',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (64101,'Direcci&oacute;n General de Divulgaci&oacute;n de la Ciencia',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (65201,'Direcci&oacute;n General de Publicaciones',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (65301,'Direcci&oacute;n General de Televisi&oacute;n Universitaria',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (65501,'Direcci&oacute;n General de Comunicaci&oacute;n Social',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (65601,'Direcci&oacute;n General de Radio UNAM',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (71101,'Coordinaci&oacute;n de Asesores',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (72201,'Unidad de Coordinaci&oacute;n Administrativa',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (723,'Direcci&oacute;n General de Personal',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (72401,'Direcci&oacute;n General de Proveedur&iacute;a',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (72501,'Unidad de Coordinaci&oacute;n Institucional',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (73101,'Direcci&oacute;n General de Estudios de Legislaci&oacute;n Universitaria',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (73201,'Direcci&oacute;n General de Asuntos Jur&iacute;dicos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (73301,'Unidad de Coordinaci&oacute;n Jur&iacute;dica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74101,'Auditoria Interna',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74201,'Direcci&oacute;n General de Patrimonio Universitario',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (74301,'Direcci&oacute;n General de Control e Inform&aacute;tica',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31104,'Centro de Radioastronom&iacute;a y Astrof&iacute;sica en Morelia, Mich.',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (31119,'Centro de Investigaciones en Ecosistemas',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (62601,'Direcci&oacute;n de Danza',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (764,'Direcci&oacute;n General de Servicios Administrativos',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (76301,'Direcci&oacute;n General de Servicios Generales',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (76201,'Defensor&iacute;a de los Derechos Universitarios',1);
INSERT INTO institutions (administrative_key,name,parent_id) VALUES (661,'Recintos para el Desarrollo de Eventos',1);          
