INSERT INTO researchlines (name, researcharea_id) VALUES ('Caracterización óptica de Materiales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Crecimiento de cristales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cálculo de propiedades de soluciones electrolíticas en vegetales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cálculo de propiedades magnéticas en ferritas policristalinas y cintas magnéticas amorfas', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cálculo de propiedades ópticas de materiales fotorrefractivos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cálculos de primeros principios de propiedades electrónicas y de transporte en sólidos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Desarrollo de Instrumentos para la Caracterización y Síntesis de Nuevos Materiales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Ecosistemas,Agrosistemas y estructuras biológicas disipativas.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Edo. sólido', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Efecto Casimir entre Materiales Reales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Esparcimiento de luz en medios coloidales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Espectroscopia Optica.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Espectroscopía de tierras raras en cerámicas sol-gel', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estado Sólido', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estado Sólidos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estructura atómica y electrónica y propiedades ópticas de sistemas de baja dimensionalidad: superficies e interfaces, procesos de adsorbción atómica, relajación y reconstrucción.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estructura y propiedades físicas de germanatos laminares', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estructura y propiedades físicas de materiales naturales de interés arqueológico y paleontológico', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estructura y propiedades físicas de materiales naturales de interés odontológico', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de centros y radicales libres en diversos materiales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de la Estructura y Propiedades Físicas de Nuevos Materiales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de las propiedades electrónicas de materiales semiconductores nanoestructurados mediante métodos variacionales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fisica del Estado Sólido', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Formacion de nanoparticulas por implantacion de iones', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física Computacional: modelaje numérico, Dinámica Molecular Clásica y Cuántica.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de la Materia Condensada', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de sistemas a escala nanométrica o Nanosistemas: propiedades ópticas de nanopartículas, alambres atómicos, cúmulos atómicos quirales, fuerzas dispersivas.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Interacción Radiación-Materia en Sólidos Cristalinos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Materia condensada a alta presión', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Nanociencias', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('OPTICA NO LINEAL', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('PROPIEDADES ELECTRONICAS Y OPTICAS EN HETEROESTRUCTURAS SEMICONDUCTORAS', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('PROPIEDADES OPTICAS DE MATERIALES FOTOREFRACTIVOS', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('PROPIEDADES TERMODINAMICAS Y DE TRANSPORTE EN METALES', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Pinzas ópticas', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Planeación Energética Estratégica', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propagación de ondas en medios inhomogéneos.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades Mecánicas: Termofluencia por Dislocaciones y Superplasticidad', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades Mécanicas:Termofluencia por Dislocaciones y Superplasticidad.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades electrónicas, termodinámicas,  magnéticas y ópticas de sólidos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas de defectos en sólidos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas de medios inhomogéneos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas de nanopartículas', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas de nanopartículas metálicas incorporadas en materiales sol-gel', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas de películas delgadas nanoestructuradas producidas por sol-gel', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas de solidos.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas efectivas de nanocompuestos', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas en medios con absorción', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades ópticas lineales y no lineales de materiales nanoestructurados', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Química de óxidos de nitrógeno', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Radiación por medio de electrones acelerados', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Rctificadores moleculares de películas delgadas sol-gel nanoestrucutradas orientadas', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas de de baja dimensionalidad', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Síntesis de Nuevos Materiales', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Teoría del Estado Sólido', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Termodinámica de Procesos Irreversibles.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Transporte de carga y óptica no lineal en nanomateriales producidos por sol-gel', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Tráfico Vehicular y Temas Afines.', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Tráfico vehicular', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Tráfico vehicular y temas afines', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('analogias entre la mec. Cuantica, la electrodinamiaca y la acustica', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('fisica del estado solido (propiedades opticas y magneticas de solidos)RPE en elpasolitas', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('piezoelectricos laminados', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('propiedades magneticas de dobles fosfatos de tierras raras', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('propiedades opticas', 1);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Análisis de Materiales con haces de iones', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Análisis de materiales de origen orgánico e inorgánico con técnicas analíticas con haces de iones.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Análisis de materiales por medio de técnicas con haces de iones', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Análisis elemental de aerosoles atmosféricos', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Análisis usando técnicas nucleares', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Análisis y modificación de materiales por medio de haces iónicos', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Aplicaciones de las radiaciones', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Biofisica', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Caracterización de sistemas multicapas y de materiales', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Caracterización y modificación de materiales usando haces de iones', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Deformación de partículas coloidales de sílice mediante la irradiación con iones pesados', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Desarrollo de un Nano-Sistema de Quimio-Radiación para Tratamiento de Cáncer Cérvico Uterino basado en el uso de Liposomas cargados con Cisplatino y Núcleos Radiactivos Emisores de Partículas Beta de Alta Energía', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Digitalizacion de Imagenes.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Dosimetría de partículas beta de alta energía transportadas por liposomas en tejido tumoral', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Dosimetría termoluminiscente de partículas cargadas pesadas', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Dosimetría termoluminiscente y sus aplicaciones en física médica', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('ESTUDIO DE PELICULAS FERROELECTRICAS: de Pb(ZrTi)', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('ESTUDIO SE SUPERCONDUCTORES DE MgB2', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de la luz en geometrias del corte brillante', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de la modificación de los materiales utilizando radiaciones ionizantes.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio experimental de nuevos detctores de centelleo', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudios básicos de colisiones ion-átomo que involucran la emisión de rayos X y UV.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fechamiento mediante Carbono 14', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fecheo de ceramicas por TL.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fisica Nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fisica de Nanocumulos', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fisica nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Formación por implantación de iones de nanopartículas metálicas en muestras de SiO2', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física Nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física atómica', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física médica', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Haces de iones radiactivos', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Implantación de iones', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Instrumentacion', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Instrumentacion nuclear.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Instrumentación nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Interaccion de Radiaciones con los Materiales.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Interacción de radiación con materia	', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Irradiación con electrones mediante el acelerador Van de Graaff.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Medica fisica', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Metodos de optimizacion en fisica computacional', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Modificación de Materiales con haces de iones.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Modificación y síntesis de materiales utilizando Implantación de iones.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Métodos no destructivos mediante haces de iones aplicados la arqueología, historia y arte (Arqueometría).', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades opticas de defectos en solidos .', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Rayos Cósmicos', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Reacciones Nucleares', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Simulación Monte Carlo del Transporte de Radiacióin', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Trazas Nucleares en Solidos y Materiales.', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Técnicas de análisis basadas en aceleradores de partículas', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('USO DE PIXE PARA DETERMINACION DE TRAZAS DE METALES EN LIQUIDOS', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('USO DE TECNICAS DE ORIGEN NUCLEAR PARA EL ANALISIS DE MATERIALES', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('astrofisica nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('caracterización de materiales por técnicas de origen nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('fisica de radiaciones', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('fisica nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Instrumentación nuclear', 2);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Catalizadores multifásicos, metales soportados y óxidos, para control de la contaminación ambiental', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Ciencia y Tecnología del Mexico Milenario', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cinética de Transformaciones de Fases', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cristales líqudos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cuasicristales', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Difusiión anómala en sistemas con reacciones químicas.', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Dinámica de estados caóticos incipientes en mapeos no lineales', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Dinámica de la vitrificación', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de Geles con partículas coloidales y mediante dispersión de onda difusa', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de sistemas nano-estructurados con aplicación en catálisis heterogénea', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudios espectroscópicos de propiedades superficiales de catalizadores', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física Estadística', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fíusiac Estadística de sistemas inhomogéneos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Hidrodinámica de Cristales Líquidos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Inestabilidades y formación de patrones en monocapas', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Interacción de proteínas (apolipoproteína A II) en confinamiento sobre distintos substratos.', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Liquidos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Mecánica estadística de fluidos complejos de interés biológico', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Monocapas de Langmuir de fosfolípidos penetradas por apolipoproteínas', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Nanocatálisis computacional', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Optica de Cristales Líquidos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Orden Local en Sólidos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Procesos Estocásticos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades electrónicas de nanoestructuras', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades electrónicas de semiconductores', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas Complejos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas Dinamicos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas coloidales, propiedades de interfases en fluidos complejos,   fluidos confinados.', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Solidos Desordenados', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Superconductividad anisotrópica', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Síntesis y propiedades de materiales mesoporosos', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Transiciones de Fase', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Transiciones de fase', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Transiciones de fase y fenómenos críticos en sistemas de baja   dimensionalidad: sistemas magnéticos, redes de superconductores', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Transiciones en Cristales líquidos liótrópicos inducidas por esfuerzos de corte', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('óptica no lineal', 3);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Problemas de física matemática aplicados a mecánica cuántica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Aspectos térmicos y no-lineales en teorías de campos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Bariogénesis de burbujas en campos magnéticos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Condensación en Sistemas Cuánticos Restringidos Espacialmente', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Correciones radiativas electrodébiles', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Desarrollo del interés principal en la definición relativista para el problema de n-cuerpos y su aplicación en el caso de n=2 al problema del positronio y del quarkonio y de n=3 para bariones como se indica en los artículos publicados con arbitraje.', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Divulgación y  participar  en seminarios y congresos de mi especialidad (ELAF cada vez que es en México, ICGTMP anual en cualquier parte del mundo, NPS cada año en Morelos, APC bianual en Roma, Italia),  intercambio académico a nivel mundial.', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Energía oscura, burbujas e implicaciones cosmológicas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estados resonantes', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estructura del vacio cuantico', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de Condensados de Bose-Einstein', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Extensiones del modelo estándar, y modelo extendido de espín', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de altas presiones dina'micas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fundamentos de teoría cuántica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física Teórica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física atómica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física computacional', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de Altas Energías y Teoría del Campo', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de Neutrinos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física molecular', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Gases cuanticos superfluidos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Gases degenerados de Fermi con interaccion', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Gases degenerados de átomos alcalinos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Glitches en Pulsares', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Masas, Simetrías y Bosón de Higgs en el Modelo Standard y sus extensiones.', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Materia Oscura y Cosmología', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Materia condensada', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Materia en condiciones extremas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Modelos matematicos en Biomedicina', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('PARTÍCULAS Y CAMPOS', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Partículas elementales|', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Pinzas ópticas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Problemas cuánticos de muchos cuerpos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Procesamiento de materiales  a altas presiones dinámicas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Procesos estocásticos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades físicas y matemáticas de la mezcla y degeneración de eigenestados de la energía no ligados (resonancias cuánticas).', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades físicas y matemáticas de la mezcla y degeneración de eigenestados de la energía no-ligados (resonancias cuánticas).', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Química cuántica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Realizar investigación original y de alta calidad en el área de “Teoría de grupos en problemas de física nuclear y partículas elementales”. Los resultados se publicarán  en revistas arbitradas e indexadas de reconocido prestigio.', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas de tres nanopartículas cargadas confinadas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Superconductividad de Alta Tc', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Teoría de muchos cuerpos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Teorías bidimensionales de campos y efectos cuánticos de Hall', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Violacion de CP', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('diseño y preparación catalizadores en industria petroquim', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('efectos no-aditivos=pocos cuerpos en fuerzas intermolec.', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('filosofia de la fisica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('física matemática en reacciones quim. y en ondas sísmicas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('teoria cuantica de campos', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('teoría de la catálisis: importancia capas-d +cruces evitados', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('vehículos liberación IN SITU drogas antiepilépticas', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Óptica cuántica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Óptica física', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('óptica cuántica', 4);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio microestructural   de muestras arqueológicas', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Biomateriales', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Caracterizacion de superficies', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Caracterizaciòn de materiales por técnicas de espectroscopía y microscopía electrónica', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Ciencia de Materiales', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Contaminación Atmosférica', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Corrosión electroquímica de materiales', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Crecimiento de cristales', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cristalografía Matemática', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Cristalografía por difracción de rayos X.', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Daños por radiaciôn', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Difracción Electrónica y de Rayos-X', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Docencia', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estado sólido.', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de propiedades magnéticas de nanopartículas', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de sistemas nanoestructurados de 1 dimension', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio de transporte de fármacos usando nanoesferas de TiO2', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Estudio microestructural de nanopartículas', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de los Materiales', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física del Estado Sólido', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fîsica de Materiales', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Holografía con electrones. Procesos de formación de imágenes en Microscopía electrónica', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Materia Condensada', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Microscopía Electrónica', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Nanomateriales por sol-gel', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Optica', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Películas delgadas', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('microscopia electronica  de materiales', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('síntesis y caracterizacion de peliculas delgadas', 5);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Biología teórica', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Ciencias de Materiales', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Dinámica No lineal y Biocoplejidad', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Dinámica no-lineal', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Efectos Transitorios y Evolución Temporal en Mecánica Cuántica', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fisica Nolineal y Estadistica', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Fundamentos de Mecanica Cuantica', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física Computacional de Nanomateriales', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física Estadística fuera de Equilibrio', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física Estadística y Termodinámica de sistemas no uniformes (Gases fríos, Condensación de Bose-Einstein)', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física No Lineal', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de Cúmulos Atómicos', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física de los Sistemas Complejos', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física estadística', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Física estadística de sistemas fuera de equilibrio (matracas estocásticas).', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Interacción de pulsos ultracortos de luz con sistemas moleculares.', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Procesos Estocásticos en Sistemas No Lineales', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Propiedades Estructurales y Electrónicas de Materiales', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Redes complejas', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas Complejos y  Ecologia', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas Mesoscopicos', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sistemas complejos', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Sociofísica', 6);
INSERT INTO researchlines (name, researcharea_id) VALUES ('Teoría de Procesos Coherentes e Incoherentes en Corrales Cuánticos', 6);
