
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Antropología', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias de la Administración', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Derecho', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Economía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Geografía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Pedagogía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Psicología', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Arquitectura', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Urbanismo', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Bibliotecología y Estudios de la Información,', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencxias e Ingeniería de Materiales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias (Astronomía)', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Biológicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Bioquímicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias de la producción y salud animal', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias de la Tierra', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Matemáticas y de la Especialización en Estadística Aplicada', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría eb Ciencias del Mar y Limnología', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencia e In genriería de la Computación', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Físicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Médicas Odontológicas y de la Salud', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias Químicas', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios Mesoamericanos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Filosofía', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Filosofía de la Ciencia', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Historia', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestrá en Historia del Arte', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ingeniería', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Letras', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Lingüística', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Música', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Artes Visuales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Ciencias (Neurobiología)', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Diseño Industrial', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Enfermería', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios Políticos y Sociales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Gobierno y Asuntos Públicos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Comunicación', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios en Relaciones Internacionales', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios México-Estados Unidos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Estudios Latinoamericanos', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Docencia para la Educación Media Superior', 5);
INSERT INTO careers (name,degree_id) VALUES ('Maestría en Trabajo Social', 5);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Antropología', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias de la Administración', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Derecho', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Pedagogía', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Economía', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Arquitectura', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Urbanismo', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Bibliotecología y Estudios de la Información', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias e Ingeniería de Materiales', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias (Astronomía)', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Biológicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Bioquímicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias de la producción y salud animal', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias de la Tierra', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Matemáticas y de la Especialización en Estadística Aplicada', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias del Mar y Limnología', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencia e In genriería de la Computación', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Físicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Médicas Odontológicas y de la Salud', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Químicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Estudios Mesoamericanos', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Filosofía', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Filosofía de la Ciencia', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Historia', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ingeniería', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Letras', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Lingüística', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Música', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Ciencias Biomédicas', 6);
INSERT INTO careers (name,degree_id) VALUES ('Ciencia Política', 6);
INSERT INTO careers (name,degree_id) VALUES ('Sociología', 6);
INSERT INTO careers (name,degree_id) VALUES ('Administración Pública', 6);
INSERT INTO careers (name,degree_id) VALUES ('Ciencias de la Comunicación', 6);
INSERT INTO careers (name,degree_id) VALUES ('Relaciones Internacionales', 6);
INSERT INTO careers (name,degree_id) VALUES ('Doctorado en Estudios Latinoamericanos', 6);
