INSERT INTO publishers (name) VALUES ('Cal y Arena');
INSERT INTO publishers (name) VALUES ('Comisión Nacional de Derechos Humanos');
INSERT INTO publishers (name) VALUES ('El Caballito');
INSERT INTO publishers (name) VALUES ('El Colegio de México');
INSERT INTO publishers (name) VALUES ('El Colegio Nacional');
INSERT INTO publishers (name) VALUES ('Facultad de Ciencias Políticas y Sociales');
INSERT INTO publishers (name) VALUES ('Fondo de Cultura Económica');
INSERT INTO publishers (name) VALUES ('Gernika');
INSERT INTO publishers (name) VALUES ('Grupo Patria Cultural');
INSERT INTO publishers (name) VALUES ('Juan Pablos, Editor, S.A.');
INSERT INTO publishers (name) VALUES ('Miguel �ngel Porrúa');
INSERT INTO publishers (name) VALUES ('Nostra Ediciones');
INSERT INTO publishers (name) VALUES ('Pearson');
INSERT INTO publishers (name) VALUES ('Plaza y Valdés');
INSERT INTO publishers (name) VALUES ('Siglo XXI Editores');
INSERT INTO publishers (name) VALUES ('Trillas');
INSERT INTO publishers (name) VALUES ('Universidad Autónoma del Estado de México');
INSERT INTO publishers (name) VALUES ('Universidad Nacional Autónoma de México');
