\set ON_ERROR_STOP 1

\i catalogs/groups.sql
\i catalogs/roles.sql
\i catalogs/actions.sql
\i catalogs/controllers.sql
\i catalogs/userstatuses.sql
\i catalogs/roleingroups.sql
\i catalogs/permissions.sql
\i catalogs/default_user.sql
\i catalogs/countries.sql
\i catalogs/states.sql
\i catalogs/cities.sql
\i catalogs/maritalstatuses.sql
\i catalogs/addresstypes.sql
\i catalogs/booktypes.sql
\i catalogs/bookchaptertypes.sql
\i catalogs/volumes.sql
\i catalogs/mediatypes.sql
\i catalogs/publishers.sql
\i catalogs/editions.sql
\i catalogs/editionstatuses.sql
\i catalogs/roleinbooks.sql
\i catalogs/institutiontypes.sql
\i catalogs/institutiontitles.sql
\i catalogs/sectors.sql
\i catalogs/institutions.sql
\i catalogs/languages.sql
\i catalogs/languagelevels.sql
\i catalogs/publicationcategories.sql
\i catalogs/articlestatuses.sql
\i catalogs/idtypes.sql
\i catalogs/migratorystatuses.sql
\i catalogs/citizenmodalities.sql
\i catalogs/degrees.sql
\i catalogs/titlemodalities.sql
\i catalogs/credentials.sql
\i catalogs/jobpositiontypes.sql
\i catalogs/roleinjobpositions.sql
\i catalogs/jobpositionlevels.sql
\i catalogs/jobpositioncategories.sql
\i catalogs/contracttypes.sql
\i catalogs/careers.sql
\i catalogs/institutioncareers.sql
\i catalogs/documenttypes.sql
\i catalogs/stimulus.sql
\i catalogs/identifications.sql
\i catalogs/grants.sql
\i catalogs/schoolarships.sql
\i catalogs/schooling_filetypes.sql
\i catalogs/acadvisittypes.sql
\i catalogs/courses.sql
\i catalogs/modalities.sql
\i catalogs/attendeetypes.sql
\i catalogs/prizetypes.sql
\i catalogs/conferences.sql
\i catalogs/genericworkgroups.sql
\i catalogs/genericworktypes.sql
\i catalogs/genericworkstatuses.sql
\i catalogs/userroles.sql
\i catalogs/roleinjournals.sql
