# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "academicprograms", :force => true do |t|
    t.column "institutioncareer_id",   :integer,  :null => false
    t.column "academicprogramtype_id", :integer,  :null => false
    t.column "year",                   :integer,  :null => false
    t.column "moduser_id",             :integer
    t.column "created_on",             :datetime
    t.column "updated_on",             :datetime
  end

  add_index "academicprograms", ["institutioncareer_id", "year"], :name => "academicprograms_institutioncareer_id_key", :unique => true

  create_table "academicprogramtypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "academicprogramtypes", ["name"], :name => "academicprogramtypes_name_key", :unique => true

  create_table "acadvisits", :force => true do |t|
    t.column "user_id",          :integer,  :null => false
    t.column "institution_id",   :integer,  :null => false
    t.column "country_id",       :integer,  :null => false
    t.column "acadvisittype_id", :integer,  :null => false
    t.column "name",             :text,     :null => false
    t.column "startyear",        :integer,  :null => false
    t.column "startmonth",       :integer
    t.column "endyear",          :integer
    t.column "endmonth",         :integer
    t.column "place",            :text
    t.column "goals",            :text
    t.column "other",            :text
    t.column "externaluser_id",  :integer
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  create_table "acadvisittypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "acadvisittypes", ["name"], :name => "acadvisittypes_name_key", :unique => true

  create_table "actions", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "actions", ["name"], :name => "actions_name_key", :unique => true

  create_table "activities", :force => true do |t|
    t.column "user_id",         :integer,  :null => false
    t.column "activitytype_id", :integer,  :null => false
    t.column "name",            :text,     :null => false
    t.column "descr",           :text
    t.column "year",            :integer,  :null => false
    t.column "month",           :integer
    t.column "moduser_id",      :integer
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  create_table "activitygroups", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "activitygroups", ["name"], :name => "activitygroups_name_key", :unique => true

  create_table "activitytypes", :force => true do |t|
    t.column "name",             :text,     :null => false
    t.column "activitygroup_id", :integer,  :null => false
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "activitytypes", ["name"], :name => "activitytypes_name_key", :unique => true

  create_table "addresses", :force => true do |t|
    t.column "user_id",        :integer,                     :null => false
    t.column "addresstype_id", :integer,                     :null => false
    t.column "location",       :text,                        :null => false
    t.column "pobox",          :text
    t.column "country_id",     :integer,                     :null => false
    t.column "state_id",       :integer
    t.column "city_id",        :integer
    t.column "zipcode",        :integer
    t.column "phone",          :text
    t.column "fax",            :text
    t.column "movil",          :text
    t.column "other",          :text
    t.column "is_postaddress", :boolean,  :default => false, :null => false
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "addresses", ["user_id", "addresstype_id"], :name => "addresses_user_id_key", :unique => true

  create_table "addresstypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "addresstypes", ["name"], :name => "addresstypes_name_key", :unique => true

  create_table "adscriptions", :force => true do |t|
    t.column "name",               :text,     :null => false
    t.column "abbrev",             :text
    t.column "descr",              :text
    t.column "institution_id",     :integer,  :null => false
    t.column "administrative_key", :text
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "adscriptions", ["name", "institution_id"], :name => "adscriptions_name_key", :unique => true

  create_table "adviceactivities", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "adviceactivities", ["name"], :name => "adviceactivities_name_key", :unique => true

  create_table "approved_documents", :force => true do |t|
    t.column "document_id", :integer,  :null => false
    t.column "user_id",     :integer,  :null => false
    t.column "ip_address",  :text,     :null => false
    t.column "approved",    :boolean,  :null => false
    t.column "moduser_id",  :integer
    t.column "created_on",  :datetime
    t.column "updated_on",  :datetime
  end

  create_table "articles", :force => true do |t|
    t.column "title",            :text,     :null => false
    t.column "journal_id",       :integer,  :null => false
    t.column "articlestatus_id", :integer,  :null => false
    t.column "pages",            :text
    t.column "year",             :integer,  :null => false
    t.column "month",            :integer
    t.column "vol",              :text
    t.column "num",              :text
    t.column "authors",          :text,     :null => false
    t.column "url",              :text
    t.column "pacsnum",          :text
    t.column "other",            :text
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "articles", ["title", "journal_id", "year"], :name => "articles_title_key", :unique => true

  create_table "articlesfiles", :force => true do |t|
    t.column "filename",      :text,     :null => false
    t.column "articles_id",   :integer,  :null => false
    t.column "filedescr",     :text
    t.column "content",       :binary,   :null => false
    t.column "creationtime",  :datetime, :null => false
    t.column "lastmodiftime", :datetime, :null => false
    t.column "moduser_id",    :integer
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "articlesfiles", ["filename", "articles_id"], :name => "articlesfiles_articles_id_key", :unique => true
  add_index "articlesfiles", ["articles_id"], :name => "articlesfiles_articles_idx"
  add_index "articlesfiles", ["filename"], :name => "articlesfiles_filename_idx"

  create_table "articleslog", :force => true do |t|
    t.column "article_id",           :integer,  :null => false
    t.column "old_articlestatus_id", :integer,  :null => false
    t.column "changedate",           :date,     :null => false
    t.column "moduser_id",           :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  create_table "articlestatuses", :force => true do |t|
    t.column "name", :string, :limit => 50, :null => false
  end

  add_index "articlestatuses", ["name"], :name => "articlestatuses_name_key", :unique => true

  create_table "bookchaptertypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "bookchaptertypes", ["name"], :name => "bookchaptertypes_name_key", :unique => true

  create_table "bookedition_comments", :force => true do |t|
    t.column "user_id",        :integer,  :null => false
    t.column "bookedition_id", :integer,  :null => false
    t.column "comment",        :text
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "bookedition_comments", ["user_id", "bookedition_id"], :name => "bookedition_comments_user_id_key", :unique => true

  create_table "bookedition_roleinbooks", :force => true do |t|
    t.column "user_id",        :integer, :null => false
    t.column "bookedition_id", :integer, :null => false
    t.column "roleinbook_id",  :integer, :null => false
  end

  add_index "bookedition_roleinbooks", ["user_id", "bookedition_id", "roleinbook_id"], :name => "bookedition_roleinbooks_user_id_key", :unique => true

  create_table "bookeditions", :force => true do |t|
    t.column "book_id",          :integer,  :null => false
    t.column "edition_id",       :integer,  :null => false
    t.column "pages",            :integer
    t.column "isbn",             :text
    t.column "publisher_id",     :integer,  :null => false
    t.column "mediatype_id",     :integer,  :null => false
    t.column "editionstatus_id", :integer
    t.column "month",            :integer
    t.column "year",             :integer,  :null => false
    t.column "other",            :text
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "bookeditions", ["book_id", "edition_id"], :name => "bookeditions_book_id_key", :unique => true

  create_table "books", :force => true do |t|
    t.column "title",             :text,     :null => false
    t.column "author",            :text,     :null => false
    t.column "booklink",          :text
    t.column "country_id",        :integer,  :null => false
    t.column "booktype_id",       :integer,  :null => false
    t.column "volume_id",         :integer
    t.column "orig_language_id",  :integer
    t.column "trans_language_id", :integer
    t.column "moduser_id",        :integer
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  create_table "booksfiles", :force => true do |t|
    t.column "filename",      :text,     :null => false
    t.column "books_id",      :integer,  :null => false
    t.column "filedescr",     :text
    t.column "content",       :binary,   :null => false
    t.column "creationtime",  :datetime, :null => false
    t.column "lastmodiftime", :datetime, :null => false
    t.column "moduser_id",    :integer
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "booksfiles", ["filename", "books_id"], :name => "booksfiles_books_id_key", :unique => true
  add_index "booksfiles", ["books_id"], :name => "booksfiles_books_idx"
  add_index "booksfiles", ["filename"], :name => "booksfiles_filename_idx"

  create_table "booktypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "booktypes", ["name"], :name => "booktypes_name_key", :unique => true

  create_table "careers", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "abbrev",     :text
    t.column "degree_id",  :integer,  :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "careers", ["name", "degree_id"], :name => "careers_name_key", :unique => true

  create_table "chapterinbook_comments", :force => true do |t|
    t.column "user_id",          :integer,  :null => false
    t.column "chapterinbook_id", :integer,  :null => false
    t.column "comment",          :text
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "chapterinbook_comments", ["user_id", "chapterinbook_id"], :name => "chapterinbook_comments_user_id_key", :unique => true

  create_table "chapterinbook_roleinchapters", :force => true do |t|
    t.column "user_id",          :integer,  :null => false
    t.column "chapterinbook_id", :integer,  :null => false
    t.column "roleinchapter_id", :integer,  :null => false
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "chapterinbook_roleinchapters", ["user_id", "chapterinbook_id", "roleinchapter_id"], :name => "chapterinbook_roleinchapters_user_id_key", :unique => true

  create_table "chapterinbooks", :force => true do |t|
    t.column "bookedition_id",     :integer,  :null => false
    t.column "bookchaptertype_id", :integer,  :null => false
    t.column "title",              :text,     :null => false
    t.column "pages",              :text
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "chapterinbooks", ["bookedition_id", "bookchaptertype_id", "title"], :name => "chapterinbooks_bookedition_id_key", :unique => true
  add_index "chapterinbooks", ["title"], :name => "chapterinbooks_title_idx"

  create_table "chapterinbooksfiles", :force => true do |t|
    t.column "filename",         :text,     :null => false
    t.column "chapterinbook_id", :integer,  :null => false
    t.column "filedescr",        :text
    t.column "content",          :binary,   :null => false
    t.column "creationtime",     :datetime, :null => false
    t.column "lastmodiftime",    :datetime, :null => false
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "chapterinbooksfiles", ["filename", "chapterinbook_id"], :name => "chapterinbooksfiles_chapterinbook_id_key", :unique => true
  add_index "chapterinbooksfiles", ["chapterinbook_id"], :name => "chapterinbooksfiles_chapterinbooks_idx"
  add_index "chapterinbooksfiles", ["filename"], :name => "chapterinbooksfiles_filename_idx"

  create_table "cities", :force => true do |t|
    t.column "state_id",   :integer,  :null => false
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "cities", ["state_id", "name"], :name => "cities_state_id_key", :unique => true

  create_table "citizenmodalities", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "citizenmodalities", ["name"], :name => "citizenmodalities_name_key", :unique => true

  create_table "citizens", :force => true do |t|
    t.column "user_id",            :integer,  :null => false
    t.column "citizen_country_id", :integer,  :null => false
    t.column "migratorystatus_id", :integer,  :null => false
    t.column "citizenmodality_id", :integer,  :null => false
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "citizens", ["user_id", "citizen_country_id"], :name => "citizens_user_id_key", :unique => true

  create_table "conference_institutions", :force => true do |t|
    t.column "conference_id",  :integer,  :null => false
    t.column "institution_id", :integer,  :null => false
    t.column "moduser_id",     :integer,  :null => false
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "conference_institutions", ["conference_id", "institution_id"], :name => "conference_institutions_conference_id_key", :unique => true

  create_table "conferences", :force => true do |t|
    t.column "name",               :text,                        :null => false
    t.column "url",                :text
    t.column "month",              :integer
    t.column "year",               :integer,                     :null => false
    t.column "conferencetype_id",  :integer,                     :null => false
    t.column "country_id",         :integer,                     :null => false
    t.column "conferencescope_id", :integer
    t.column "location",           :text
    t.column "isspecialized",      :boolean,  :default => false, :null => false
    t.column "moduser_id",         :integer,                     :null => false
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "conferences", ["name", "year", "country_id"], :name => "conferences_name_key", :unique => true

  create_table "conferencescopes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "conferencescopes", ["name"], :name => "conferencescopes_name_key", :unique => true

  create_table "conferencetalks", :force => true do |t|
    t.column "title",             :text,     :null => false
    t.column "authors",           :text,     :null => false
    t.column "abstract",          :text
    t.column "conference_id",     :integer,  :null => false
    t.column "talktype_id",       :integer,  :null => false
    t.column "talkacceptance_id", :integer,  :null => false
    t.column "modality_id",       :integer,  :null => false
    t.column "moduser_id",        :integer,  :null => false
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  add_index "conferencetalks", ["title", "authors", "conference_id"], :name => "conferencetalks_conference_id_key", :unique => true

  create_table "conferencetalksfiles", :force => true do |t|
    t.column "filename",           :text,     :null => false
    t.column "conferencetalks_id", :integer,  :null => false
    t.column "filedescr",          :text
    t.column "content",            :binary,   :null => false
    t.column "creationtime",       :datetime, :null => false
    t.column "lastmodiftime",      :datetime, :null => false
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "conferencetalksfiles", ["filename", "conferencetalks_id"], :name => "conferencetalksfiles_conferencetalks_id_key", :unique => true
  add_index "conferencetalksfiles", ["conferencetalks_id"], :name => "conferencetalksfiles_conferencetalks_idx"
  add_index "conferencetalksfiles", ["filename"], :name => "conferencetalksfiles_filename_idx"

  create_table "conferencetypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "conferencetypes", ["name"], :name => "conferencetypes_name_key", :unique => true

  create_table "contracttypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "contracttypes", ["name"], :name => "contracttypes_name_key", :unique => true

  create_table "controllers", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "controllers", ["name"], :name => "controllers_name_key", :unique => true

  create_table "countries", :force => true do |t|
    t.column "name",    :text,                :null => false
    t.column "citizen", :text,                :null => false
    t.column "code",    :string, :limit => 3, :null => false
  end

  add_index "countries", ["code"], :name => "countries_code_key", :unique => true
  add_index "countries", ["name"], :name => "countries_name_key", :unique => true

  create_table "coursedurations", :force => true do |t|
    t.column "name", :text,    :null => false
    t.column "days", :integer, :null => false
  end

  add_index "coursedurations", ["name"], :name => "coursedurations_name_key", :unique => true

  create_table "coursegroups", :force => true do |t|
    t.column "name",               :text,    :null => false
    t.column "coursegrouptype_id", :integer, :null => false
    t.column "startyear",          :integer, :null => false
    t.column "startmonth",         :integer
    t.column "endyear",            :integer
    t.column "endmonth",           :integer
    t.column "totalhours",         :integer
  end

  add_index "coursegroups", ["name"], :name => "coursegroups_name_key", :unique => true

  create_table "coursegrouptypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "coursegrouptypes", ["name"], :name => "coursegrouptypes_name_key", :unique => true

  create_table "courses", :force => true do |t|
    t.column "name",              :text,    :null => false
    t.column "country_id",        :integer, :null => false
    t.column "institution_id",    :integer
    t.column "coursegroup_id",    :integer
    t.column "courseduration_id", :integer, :null => false
    t.column "modality_id",       :integer, :null => false
    t.column "startyear",         :integer, :null => false
    t.column "startmonth",        :integer
    t.column "endyear",           :integer
    t.column "endmonth",          :integer
    t.column "hoursxweek",        :integer
    t.column "location",          :text
    t.column "totalhours",        :integer
  end

  add_index "courses", ["name", "startyear", "startmonth"], :name => "courses_name_key", :unique => true

  create_table "credentials", :force => true do |t|
    t.column "name",       :text
    t.column "abbrev",     :text
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "credentials", ["name"], :name => "credentials_name_key", :unique => true

  create_table "degrees", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "degrees", ["name"], :name => "degrees_name_key", :unique => true

  create_table "documents", :force => true do |t|
    t.column "user_id",               :integer,  :null => false
    t.column "is_published",          :boolean,  :null => false
    t.column "date_published",        :date,     :null => false
    t.column "documenttype_id",       :integer,  :null => false
    t.column "document",              :binary,   :null => false
    t.column "document_filename",     :text,     :null => false
    t.column "document_content_type", :text,     :null => false
    t.column "ip_addr",               :text,     :null => false
    t.column "moduser_id",            :integer
    t.column "created_on",            :datetime
    t.column "updated_on",            :datetime
  end

  create_table "documenttypes", :force => true do |t|
    t.column "name",  :text, :null => false
    t.column "descr", :text
  end

  add_index "documenttypes", ["name"], :name => "documenttypes_name_key", :unique => true

  create_table "editions", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "editions", ["name"], :name => "editions_name_key", :unique => true

  create_table "editionstatuses", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "editionstatuses", ["name"], :name => "editionstatuses_name_key", :unique => true

  create_table "externaluserlevels", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "externaluserlevels", ["name"], :name => "externaluserlevels_name_key", :unique => true

  create_table "externalusers", :force => true do |t|
    t.column "firstname",            :text,    :null => false
    t.column "lastname1",            :text,    :null => false
    t.column "lastname2",            :text
    t.column "institution_id",       :integer
    t.column "externaluserlevel_id", :integer
    t.column "degree_id",            :integer
  end

  create_table "file_articles", :force => true do |t|
    t.column "article_id",    :integer,  :null => false
    t.column "filename",      :text,     :null => false
    t.column "conten_type",   :text
    t.column "content",       :binary,   :null => false
    t.column "creationtime",  :datetime, :null => false
    t.column "lastmodiftime", :datetime, :null => false
    t.column "moduser_id",    :integer
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "file_articles", ["article_id", "filename"], :name => "file_articles_article_id_key", :unique => true

  create_table "genericworkgroups", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "genericworkgroups", ["name"], :name => "genericworkgroups_name_key", :unique => true

  create_table "genericworks", :force => true do |t|
    t.column "title",                :text,     :null => false
    t.column "authors",              :text,     :null => false
    t.column "genericworktype_id",   :integer,  :null => false
    t.column "genericworkstatus_id", :integer,  :null => false
    t.column "institution_id",       :integer
    t.column "publisher_id",         :integer
    t.column "reference",            :text
    t.column "vol",                  :text
    t.column "pages",                :text
    t.column "year",                 :integer,  :null => false
    t.column "month",                :integer
    t.column "isbn_issn",            :text
    t.column "other",                :text
    t.column "moduser_id",           :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  create_table "genericworksfiles", :force => true do |t|
    t.column "filename",        :text,     :null => false
    t.column "genericworks_id", :integer,  :null => false
    t.column "filedescr",       :text
    t.column "content",         :binary,   :null => false
    t.column "creationtime",    :datetime, :null => false
    t.column "lastmodiftime",   :datetime, :null => false
    t.column "moduser_id",      :integer
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  add_index "genericworksfiles", ["filename"], :name => "genericworksfiles_filename_idx"
  add_index "genericworksfiles", ["filename", "genericworks_id"], :name => "genericworksfiles_genericworks_id_key", :unique => true
  add_index "genericworksfiles", ["genericworks_id"], :name => "genericworksfiles_genericworks_idx"

  create_table "genericworkslog", :force => true do |t|
    t.column "genericwork_id",           :integer,  :null => false
    t.column "old_genericworkstatus_id", :integer,  :null => false
    t.column "changedate",               :date,     :null => false
    t.column "moduser_id",               :integer
    t.column "created_on",               :datetime
    t.column "updated_on",               :datetime
  end

  create_table "genericworkstatuses", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "genericworkstatuses", ["name"], :name => "genericworkstatuses_name_key", :unique => true

  create_table "genericworktypes", :force => true do |t|
    t.column "name",                :text,     :null => false
    t.column "abbrev",              :text
    t.column "genericworkgroup_id", :integer,  :null => false
    t.column "moduser_id",          :integer
    t.column "created_on",          :datetime
    t.column "updated_on",          :datetime
  end

  add_index "genericworktypes", ["name", "genericworkgroup_id"], :name => "genericworktypes_name_key", :unique => true

  create_table "grants", :force => true do |t|
    t.column "name",           :text,    :null => false
    t.column "institution_id", :integer, :null => false
    t.column "moduser_id",     :integer
  end

  add_index "grants", ["name", "institution_id"], :name => "grants_name_key", :unique => true

  create_table "groupmodalities", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "groupmodalities", ["name"], :name => "groupmodalities_name_key", :unique => true

  create_table "groups", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "descr",      :text
    t.column "parent_id",  :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "groups", ["name", "parent_id"], :name => "groups_name_key", :unique => true

  create_table "identifications", :force => true do |t|
    t.column "idtype_id",          :integer,  :null => false
    t.column "citizen_country_id", :integer,  :null => false
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "identifications", ["idtype_id", "citizen_country_id"], :name => "identifications_idtype_id_key", :unique => true

  create_table "idtypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "idtypes", ["name"], :name => "idtypes_name_key", :unique => true

  create_table "indivadviceprograms", :force => true do |t|
    t.column "name",           :text,    :null => false
    t.column "descr",          :text
    t.column "institution_id", :integer, :null => false
  end

  add_index "indivadviceprograms", ["name"], :name => "indivadviceprograms_name_key", :unique => true

  create_table "indivadvices", :force => true do |t|
    t.column "user_id",               :integer,  :null => false
    t.column "indivname",             :text
    t.column "indivuser_id",          :integer
    t.column "institution_id",        :integer
    t.column "indivadvicetarget_id",  :integer,  :null => false
    t.column "indivadviceprogram_id", :integer
    t.column "degree_id",             :integer
    t.column "year",                  :integer,  :null => false
    t.column "month",                 :integer
    t.column "hours",                 :integer,  :null => false
    t.column "other",                 :text
    t.column "moduser_id",            :integer
    t.column "created_on",            :datetime
    t.column "updated_on",            :datetime
  end

  create_table "indivadvicetargets", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "indivadvicetargets", ["name"], :name => "indivadvicetargets_name_key", :unique => true

  create_table "inproceedings", :force => true do |t|
    t.column "proceeding_id", :integer,  :null => false
    t.column "title",         :text,     :null => false
    t.column "authors",       :text,     :null => false
    t.column "pages",         :text
    t.column "comment",       :text
    t.column "moduser_id",    :integer,  :null => false
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "inproceedings", ["proceeding_id", "title"], :name => "inproceedings_proceeding_id_key", :unique => true

  create_table "instadviceactivities", :force => true do |t|
    t.column "instadvice_id",     :integer,  :null => false
    t.column "adviceactivity_id", :integer,  :null => false
    t.column "duration",          :text
    t.column "moduser_id",        :integer
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  add_index "instadviceactivities", ["instadvice_id", "adviceactivity_id"], :name => "instadviceactivities_instadvice_id_key", :unique => true

  create_table "instadvices", :force => true do |t|
    t.column "title",               :text,     :null => false
    t.column "user_id",             :integer,  :null => false
    t.column "institution_id",      :integer,  :null => false
    t.column "instadvicetarget_id", :integer,  :null => false
    t.column "other",               :text
    t.column "year",                :integer,  :null => false
    t.column "month",               :integer
    t.column "moduser_id",          :integer
    t.column "created_on",          :datetime
    t.column "updated_on",          :datetime
  end

  create_table "instadvicetargets", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "instadvicetargets", ["name"], :name => "instadvicetargets_name_key", :unique => true

  create_table "institution_sectors", :force => true do |t|
    t.column "institution_id", :integer, :null => false
    t.column "sector_id",      :integer, :null => false
    t.column "moduser_id",     :integer
  end

  add_index "institution_sectors", ["institution_id", "sector_id"], :name => "institution_sectors_institution_id_key", :unique => true

  create_table "institutional_activities", :force => true do |t|
    t.column "user_id",        :integer,  :null => false
    t.column "descr",          :text,     :null => false
    t.column "institution_id", :integer,  :null => false
    t.column "startmonth",     :integer
    t.column "startyear",      :integer,  :null => false
    t.column "endmonth",       :integer
    t.column "endyear",        :integer
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  create_table "institutioncareers", :force => true do |t|
    t.column "institution_id", :integer,  :null => false
    t.column "career_id",      :integer,  :null => false
    t.column "url",            :text
    t.column "other",          :text
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "institutioncareers", ["institution_id", "career_id"], :name => "institutioncareers_institution_id_key", :unique => true

  create_table "institutions", :force => true do |t|
    t.column "institutiontype_id",  :integer,  :null => false
    t.column "name",                :text,     :null => false
    t.column "url",                 :text
    t.column "abbrev",              :text
    t.column "institution_id",      :integer
    t.column "institutiontitle_id", :integer,  :null => false
    t.column "addr",                :text
    t.column "country_id",          :integer,  :null => false
    t.column "state_id",            :integer
    t.column "city_id",             :integer
    t.column "zipcode",             :text
    t.column "phone",               :text
    t.column "fax",                 :text
    t.column "administrative_key",  :text
    t.column "other",               :text
    t.column "moduser_id",          :integer
    t.column "created_on",          :datetime
    t.column "updated_on",          :datetime
  end

  add_index "institutions", ["name", "country_id", "state_id"], :name => "institutions_name_key", :unique => true

  create_table "institutiontitles", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "institutiontitles", ["name"], :name => "institutiontitles_name_key", :unique => true

  create_table "institutiontypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "institutiontypes", ["name"], :name => "institutiontypes_name_key", :unique => true

  create_table "jobposition_logs", :force => true do |t|
    t.column "user_id",    :integer,  :null => false
    t.column "worker_key", :text,     :null => false
    t.column "years",      :integer,  :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "jobposition_logs", ["user_id", "worker_key"], :name => "jobposition_logs_user_id_key", :unique => true

  create_table "jobpositioncategories", :force => true do |t|
    t.column "jobpositiontype_id",   :integer, :null => false
    t.column "roleinjobposition_id", :integer, :null => false
    t.column "jobpositionlevel_id",  :integer
    t.column "administrative_key",   :text
  end

  create_table "jobpositionlevels", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "jobpositionlevels", ["name"], :name => "jobpositionlevels_name_key", :unique => true

  create_table "jobpositions", :force => true do |t|
    t.column "user_id",                :integer,  :null => false
    t.column "jobpositioncategory_id", :integer
    t.column "contracttype_id",        :integer
    t.column "institution_id",         :integer,  :null => false
    t.column "descr",                  :text
    t.column "startmonth",             :integer
    t.column "startyear",              :integer,  :null => false
    t.column "endmonth",               :integer
    t.column "endyear",                :integer
    t.column "moduser_id",             :integer
    t.column "created_on",             :datetime
    t.column "updated_on",             :datetime
  end

  create_table "jobpositiontypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "jobpositiontypes", ["name"], :name => "jobpositiontypes_name_key", :unique => true

  create_table "journal_publicationcategories", :force => true do |t|
    t.column "journal_id",             :integer,  :null => false
    t.column "publicationcategory_id", :integer,  :null => false
    t.column "moduser_id",             :integer
    t.column "created_on",             :datetime
    t.column "updated_on",             :datetime
  end

  add_index "journal_publicationcategories", ["journal_id", "publicationcategory_id"], :name => "journal_publicationcategories_journal_id_key", :unique => true

  create_table "journals", :force => true do |t|
    t.column "name",         :text,     :null => false
    t.column "issn",         :text
    t.column "url",          :text
    t.column "abbrev",       :text
    t.column "other",        :text
    t.column "mediatype_id", :integer,  :null => false
    t.column "publisher_id", :integer
    t.column "country_id",   :integer,  :null => false
    t.column "moduser_id",   :integer
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
  end

  add_index "journals", ["issn"], :name => "journals_issn_key", :unique => true

  create_table "journalstatistics", :force => true do |t|
    t.column "journal_id",   :integer,  :null => false
    t.column "totalcites",   :integer
    t.column "impactfactor", :float
    t.column "immediacy",    :text
    t.column "dateupdate",   :date
    t.column "moduser_id",   :integer
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
  end

  create_table "languagelevels", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "languagelevels", ["name"], :name => "languagelevels_name_key", :unique => true

  create_table "languages", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "languages", ["name"], :name => "languages_name_key", :unique => true

  create_table "maritalstatuses", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "maritalstatuses", ["name"], :name => "maritalstatuses_name_key", :unique => true

  create_table "mediatypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "mediatypes", ["name"], :name => "mediatypes_name_key", :unique => true

  create_table "memberships", :force => true do |t|
    t.column "user_id",        :integer,  :null => false
    t.column "institution_id", :integer,  :null => false
    t.column "descr",          :text
    t.column "startyear",      :integer
    t.column "endyear",        :integer
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  create_table "menus", :force => true do |t|
    t.column "label",          :text,                       :null => false
    t.column "parent_menu_id", :integer
    t.column "group_id",       :integer,                    :null => false
    t.column "ordering",       :integer,                    :null => false
    t.column "iconopen",       :text
    t.column "iconclosed",     :text
    t.column "iconpath",       :text
    t.column "style",          :text
    t.column "action",         :text
    t.column "target",         :text
    t.column "expanded",       :boolean, :default => false, :null => false
  end

  add_index "menus", ["label", "parent_menu_id"], :name => "menus_label_key", :unique => true

  create_table "migratorystatuses", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "migratorystatuses", ["name"], :name => "migratorystatuses_name_key", :unique => true

  create_table "modalities", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "modalities", ["name"], :name => "modalities_name_key", :unique => true

  create_table "newspaperarticle_logs", :force => true do |t|
    t.column "newspaperarticle_id",  :integer,  :null => false
    t.column "old_articlestatus_id", :integer,  :null => false
    t.column "changedate",           :date,     :null => false
    t.column "moduser_id",           :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  create_table "newspaperarticles", :force => true do |t|
    t.column "title",        :text,     :null => false
    t.column "authors",      :text,     :null => false
    t.column "newspaper_id", :integer,  :null => false
    t.column "newsdate",     :date,     :null => false
    t.column "pages",        :text
    t.column "url",          :text
    t.column "moduser_id",   :integer
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
  end

  add_index "newspaperarticles", ["title", "newspaper_id", "newsdate"], :name => "newspaperarticles_title_key", :unique => true

  create_table "newspapers", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "url",        :text
    t.column "country_id", :integer,  :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "newspapers", ["name"], :name => "newspapers_name_key", :unique => true

  create_table "organ", :force => true do |t|
    t.column "name",           :text,    :null => false
    t.column "abbrev",         :text
    t.column "organtype_id",   :integer, :null => false
    t.column "institution_id", :integer, :null => false
    t.column "moduser_id",     :integer
  end

  add_index "organ", ["abbrev"], :name => "organ_abbrev_key", :unique => true
  add_index "organ", ["name"], :name => "organ_name_key", :unique => true

  create_table "organtype", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "organtype", ["name"], :name => "organtype_name_key", :unique => true

  create_table "people", :id => false, :force => true do |t|
    t.column "user_id",            :integer,  :null => false
    t.column "firstname",          :text,     :null => false
    t.column "lastname1",          :text,     :null => false
    t.column "lastname2",          :text
    t.column "gender",             :boolean,  :null => false
    t.column "maritalstatus_id",   :integer
    t.column "dateofbirth",        :date,     :null => false
    t.column "country_id",         :integer,  :null => false
    t.column "state_id",           :integer
    t.column "city_id",            :integer
    t.column "photo_filename",     :text
    t.column "photo_content_type", :text
    t.column "photo",              :binary
    t.column "other",              :text
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "people", ["firstname"], :name => "people_firstname_idx"
  add_index "people", ["lastname1"], :name => "people_lastname1_idx"
  add_index "people", ["lastname2"], :name => "people_lastname2_idx"

  create_table "people_identifications", :force => true do |t|
    t.column "user_id",           :integer,  :null => false
    t.column "identification_id", :integer,  :null => false
    t.column "descr",             :text,     :null => false
    t.column "moduser_id",        :integer
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  add_index "people_identifications", ["user_id", "identification_id"], :name => "people_identifications_user_id_key", :unique => true

  create_table "periods", :force => true do |t|
    t.column "title",      :text,     :null => false
    t.column "startdate",  :date,     :null => false
    t.column "enddate",    :date,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "periods", ["title"], :name => "periods_title_key", :unique => true
  add_index "periods", ["title", "startdate", "enddate"], :name => "periods_title_key1", :unique => true

  create_table "permissions", :force => true do |t|
    t.column "roleingroup_id", :integer,  :null => false
    t.column "controller_id",  :integer,  :null => false
    t.column "action_id",      :integer,  :null => false
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "permissions", ["roleingroup_id", "controller_id", "action_id"], :name => "permissions_roleingroup_id_key", :unique => true

  create_table "plan", :force => true do |t|
    t.column "user_id",      :integer, :null => false
    t.column "plan",         :text,    :null => false
    t.column "extendedinfo", :binary
    t.column "year",         :integer, :null => false
  end

  create_table "prizes", :force => true do |t|
    t.column "name",           :text,     :null => false
    t.column "prizetype_id",   :integer,  :null => false
    t.column "institution_id", :integer,  :null => false
    t.column "other",          :text
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "prizes", ["name", "institution_id"], :name => "prizes_name_key", :unique => true

  create_table "prizetypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "prizetypes", ["name"], :name => "prizetypes_name_key", :unique => true

  create_table "proceedings", :force => true do |t|
    t.column "conference_id", :integer,                    :null => false
    t.column "title",         :text,                       :null => false
    t.column "year",          :integer
    t.column "publisher_id",  :integer
    t.column "isrefereed",    :boolean,  :default => true, :null => false
    t.column "volume",        :text
    t.column "other",         :text
    t.column "moduser_id",    :integer,                    :null => false
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "proceedings", ["conference_id", "title"], :name => "proceedings_conference_id_key", :unique => true

  create_table "professionaltitles", :force => true do |t|
    t.column "schooling_id",     :integer,  :null => false
    t.column "titlemodality_id", :integer,  :null => false
    t.column "professionalid",   :text
    t.column "year",             :integer
    t.column "thesistitle",      :text
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "professionaltitles", ["schooling_id"], :name => "professionaltitles_schooling_id_key", :unique => true

  create_table "projectacadvisits", :force => true do |t|
    t.column "project_id",   :integer, :null => false
    t.column "acadvisit_id", :integer, :null => false
  end

  add_index "projectacadvisits", ["project_id", "acadvisit_id"], :name => "projectacadvisits_project_id_key", :unique => true

  create_table "projectarticles", :force => true do |t|
    t.column "project_id", :integer, :null => false
    t.column "article_id", :integer, :null => false
  end

  add_index "projectarticles", ["project_id", "article_id"], :name => "projectarticles_project_id_key", :unique => true

  create_table "projectbooks", :force => true do |t|
    t.column "project_id", :integer, :null => false
    t.column "book_id",    :integer, :null => false
  end

  add_index "projectbooks", ["project_id", "book_id"], :name => "projectbooks_project_id_key", :unique => true

  create_table "projectchapterinbooks", :force => true do |t|
    t.column "project_id",       :integer, :null => false
    t.column "chapterinbook_id", :integer, :null => false
  end

  add_index "projectchapterinbooks", ["project_id", "chapterinbook_id"], :name => "projectchapterinbooks_project_id_key", :unique => true

  create_table "projectconferencetalks", :force => true do |t|
    t.column "project_id",        :integer, :null => false
    t.column "conferencetalk_id", :integer, :null => false
  end

  add_index "projectconferencetalks", ["project_id", "conferencetalk_id"], :name => "projectconferencetalks_project_id_key", :unique => true

  create_table "projectfiles", :force => true do |t|
    t.column "project_id",    :integer,  :null => false
    t.column "filename",      :text,     :null => false
    t.column "filedescr",     :text
    t.column "content",       :binary,   :null => false
    t.column "creationtime",  :datetime, :null => false
    t.column "lastmodiftime", :datetime, :null => false
    t.column "moduser_id",    :integer
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "projectfiles", ["project_id", "filename"], :name => "projectfiles_project_id_key", :unique => true

  create_table "projectfinancingsources", :force => true do |t|
    t.column "project_id",     :integer, :null => false
    t.column "institution_id", :integer, :null => false
    t.column "amount",         :integer, :null => false
    t.column "other",          :text
  end

  add_index "projectfinancingsources", ["project_id", "institution_id"], :name => "projectfinancingsources_project_id_key", :unique => true

  create_table "projectgenericworks", :force => true do |t|
    t.column "project_id",     :integer, :null => false
    t.column "genericwork_id", :integer, :null => false
  end

  add_index "projectgenericworks", ["project_id", "genericwork_id"], :name => "projectgenericworks_project_id_key", :unique => true

  create_table "projectinstitutions", :force => true do |t|
    t.column "project_id",     :integer, :null => false
    t.column "institution_id", :integer, :null => false
    t.column "other",          :text
  end

  add_index "projectinstitutions", ["project_id", "institution_id"], :name => "projectinstitutions_project_id_key", :unique => true

  create_table "projectresearchareas", :force => true do |t|
    t.column "project_id",      :integer, :null => false
    t.column "researcharea_id", :integer, :null => false
    t.column "other",           :text
  end

  add_index "projectresearchareas", ["project_id", "researcharea_id"], :name => "projectresearchareas_project_id_key", :unique => true

  create_table "projectresearchlines", :force => true do |t|
    t.column "project_id",      :integer, :null => false
    t.column "researchline_id", :integer, :null => false
    t.column "other",           :text
  end

  add_index "projectresearchlines", ["project_id", "researchline_id"], :name => "projectresearchlines_project_id_key", :unique => true

  create_table "projects", :force => true do |t|
    t.column "name",             :text,     :null => false
    t.column "responsible",      :text,     :null => false
    t.column "descr",            :text,     :null => false
    t.column "projecttype_id",   :integer,  :null => false
    t.column "projectstatus_id", :integer,  :null => false
    t.column "project_id",       :integer
    t.column "abstract",         :text
    t.column "abbrev",           :text
    t.column "startyear",        :integer,  :null => false
    t.column "startmonth",       :integer
    t.column "endyear",          :integer
    t.column "endmonth",         :integer
    t.column "url",              :text
    t.column "other",            :text
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "projects", ["descr"], :name => "projects_descr_idx"
  add_index "projects", ["name"], :name => "projects_name_idx"
  add_index "projects", ["name"], :name => "projects_name_key", :unique => true

  create_table "projectslog", :force => true do |t|
    t.column "project_id",           :integer,  :null => false
    t.column "old_projectstatus_id", :integer,  :null => false
    t.column "year",                 :integer,  :null => false
    t.column "month",                :integer
    t.column "moduser_id",           :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  create_table "projectstatuses", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "projectstatuses", ["name"], :name => "projectstatuses_name_key", :unique => true

  create_table "projecttheses", :force => true do |t|
    t.column "project_id", :integer, :null => false
    t.column "thesis_id",  :integer, :null => false
  end

  add_index "projecttheses", ["project_id", "thesis_id"], :name => "projecttheses_project_id_key", :unique => true

  create_table "projecttypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "projecttypes", ["name"], :name => "projecttypes_name_key", :unique => true

  create_table "publicationcategories", :force => true do |t|
    t.column "name",       :string,   :limit => 50, :null => false
    t.column "descr",      :text
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "publicationcategories", ["name"], :name => "publicationcategories_name_key", :unique => true

  create_table "publishers", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "descr",      :text
    t.column "url",        :text
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "publishers", ["name"], :name => "publishers_name_key", :unique => true

  create_table "pubtorefereed", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "pubtorefereed", ["name"], :name => "pubtorefereed_name_key", :unique => true

  create_table "refereedpubs", :force => true do |t|
    t.column "title",            :text,    :null => false
    t.column "pubtorefereed_id", :integer, :null => false
    t.column "institution_id",   :integer, :null => false
    t.column "moduser_id",       :integer
  end

  create_table "regularcourses", :force => true do |t|
    t.column "title",              :text,     :null => false
    t.column "academicprogram_id", :integer
    t.column "modality_id",        :integer,  :null => false
    t.column "semester",           :integer
    t.column "credits",            :integer
    t.column "administrative_key", :text
    t.column "other",              :text
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  create_table "researchareas", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "descr",      :text
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "researchareas", ["name"], :name => "researchareas_name_key", :unique => true

  create_table "researchgroupmodalities", :force => true do |t|
    t.column "groupmodality_id", :integer
    t.column "researchgroup_id", :integer, :null => false
    t.column "adscription_id",   :integer
  end

  create_table "researchgroups", :force => true do |t|
    t.column "name",       :text,    :null => false
    t.column "descr",      :text
    t.column "moduser_id", :integer
  end

  add_index "researchgroups", ["name"], :name => "researchgroups_name_key", :unique => true

  create_table "researchlines", :force => true do |t|
    t.column "name",            :text,     :null => false
    t.column "descr",           :text
    t.column "researcharea_id", :integer
    t.column "moduser_id",      :integer
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  add_index "researchlines", ["name", "researcharea_id"], :name => "researchlines_name_key", :unique => true

  create_table "roleinbooks", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleinbooks", ["name"], :name => "roleinbooks_name_key", :unique => true

  create_table "roleinchapters", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleinchapters", ["name"], :name => "roleinchapters_name_key", :unique => true

  create_table "roleinconferences", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleinconferences", ["name"], :name => "roleinconferences_name_key", :unique => true

  create_table "roleinconferencetalks", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleinconferencetalks", ["name"], :name => "roleinconferencetalks_name_key", :unique => true

  create_table "roleincourses", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleincourses", ["name"], :name => "roleincourses_name_key", :unique => true

  create_table "roleingroups", :force => true do |t|
    t.column "group_id",   :integer,  :default => 1, :null => false
    t.column "role_id",    :integer,                 :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "roleingroups", ["group_id", "role_id"], :name => "roleingroups_group_id_key", :unique => true

  create_table "roleinjobpositions", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleinjobpositions", ["name"], :name => "roleinjobpositions_name_key", :unique => true

  create_table "roleinjournals", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "roleinjournals", ["name"], :name => "roleinjournals_name_key", :unique => true

  create_table "roleinjuries", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "roleinjuries", ["name"], :name => "roleinjuries_name_key", :unique => true

  create_table "roleinorgan", :force => true do |t|
    t.column "name",       :text,    :null => false
    t.column "moduser_id", :integer
  end

  add_index "roleinorgan", ["name"], :name => "roleinorgan_name_key", :unique => true

  create_table "roleinprojects", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleinprojects", ["name"], :name => "roleinprojects_name_key", :unique => true

  create_table "roleinregularcourses", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "roleinregularcourses", ["name"], :name => "roleinregularcourses_name_key", :unique => true

  create_table "roleinseminaries", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "roleinseminaries", ["name"], :name => "roleinseminaries_name_key", :unique => true

  create_table "roleintheses", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "roleintheses", ["name"], :name => "roleintheses_name_key", :unique => true

  create_table "roleproceedings", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "roleproceedings", ["name"], :name => "roleproceedings_name_key", :unique => true

  create_table "roles", :force => true do |t|
    t.column "name",            :text,                       :null => false
    t.column "has_group_right", :boolean,  :default => true, :null => false
    t.column "descr",           :text
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  add_index "roles", ["name"], :name => "roles_name_key", :unique => true

  create_table "schoolarships", :force => true do |t|
    t.column "name",           :text,    :null => false
    t.column "institution_id", :integer
    t.column "moduser_id",     :integer
  end

  add_index "schoolarships", ["name", "institution_id"], :name => "schoolarships_name_key", :unique => true

  create_table "schooling_files", :force => true do |t|
    t.column "schooling_id",          :integer,  :null => false
    t.column "schooling_filetype_id", :integer,  :null => false
    t.column "filename",              :text,     :null => false
    t.column "content_type",          :text
    t.column "content",               :binary,   :null => false
    t.column "moduser_id",            :integer
    t.column "created_on",            :datetime
    t.column "updated_on",            :datetime
  end

  add_index "schooling_files", ["schooling_id", "schooling_filetype_id"], :name => "schooling_files_schooling_id_key", :unique => true

  create_table "schooling_filetypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "descr",      :text
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "schooling_filetypes", ["name"], :name => "schooling_filetypes_name_key", :unique => true

  create_table "schoolings", :force => true do |t|
    t.column "user_id",              :integer,                     :null => false
    t.column "institutioncareer_id", :integer,                     :null => false
    t.column "startyear",            :integer,                     :null => false
    t.column "endyear",              :integer
    t.column "studentid",            :text
    t.column "credits",              :integer
    t.column "average",              :integer
    t.column "is_studying_this",     :boolean,  :default => false, :null => false
    t.column "is_titleholder",       :boolean,  :default => false, :null => false
    t.column "other",                :text
    t.column "moduser_id",           :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  add_index "schoolings", ["user_id", "institutioncareer_id"], :name => "schoolings_user_id_key", :unique => true

  create_table "sectors", :force => true do |t|
    t.column "name",       :text,    :null => false
    t.column "moduser_id", :integer
  end

  add_index "sectors", ["name"], :name => "sectors_name_key", :unique => true

  create_table "selfevaluation", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "plan",    :text,    :null => false
    t.column "year",    :integer, :null => false
  end

  create_table "seminaries", :force => true do |t|
    t.column "title",          :text,                       :null => false
    t.column "isseminary",     :boolean,  :default => true, :null => false
    t.column "url",            :text
    t.column "month",          :integer
    t.column "year",           :integer,                    :null => false
    t.column "institution_id", :integer,                    :null => false
    t.column "location",       :text
    t.column "moduser_id",     :integer,                    :null => false
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "seminaries", ["title", "year", "institution_id"], :name => "seminaries_title_key", :unique => true

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "skilltypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "skilltypes", ["name"], :name => "skilltypes_name_key", :unique => true

  create_table "sponsor_acadvisits", :force => true do |t|
    t.column "acadvisit_id",   :integer,  :null => false
    t.column "institution_id", :integer,  :null => false
    t.column "amount",         :integer,  :null => false
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  create_table "states", :force => true do |t|
    t.column "country_id", :integer,  :null => false
    t.column "name",       :text,     :null => false
    t.column "code",       :text
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "states", ["name"], :name => "states_name_key", :unique => true

  create_table "stimuluslevels", :force => true do |t|
    t.column "name",            :text,    :null => false
    t.column "stimulustype_id", :integer, :null => false
  end

  add_index "stimuluslevels", ["name", "stimulustype_id"], :name => "stimuluslevels_name_key", :unique => true

  create_table "stimuluslogs", :force => true do |t|
    t.column "stimulus_id",           :integer,  :null => false
    t.column "old_stimulusstatus_id", :integer,  :null => false
    t.column "changedate",            :date,     :null => false
    t.column "moduser_id",            :integer
    t.column "created_on",            :datetime
    t.column "updated_on",            :datetime
  end

  create_table "stimulusstatus", :force => true do |t|
    t.column "name", :string, :limit => 50, :null => false
  end

  add_index "stimulusstatus", ["name"], :name => "stimulusstatus_name_key", :unique => true

  create_table "stimulustypes", :force => true do |t|
    t.column "name",           :text,    :null => false
    t.column "descr",          :text
    t.column "institution_id", :integer, :null => false
  end

  add_index "stimulustypes", ["name"], :name => "stimulustypes_name_key", :unique => true

  create_table "student_activities", :force => true do |t|
    t.column "user_id",               :integer
    t.column "schooling_id",          :integer
    t.column "studentroles_id",       :integer
    t.column "tutor_is_internal",     :boolean
    t.column "tutor_user_id",         :integer
    t.column "tutor_externaluser_id", :integer
    t.column "moduser_id",            :integer
    t.column "created_on",            :datetime
    t.column "updated_on",            :datetime
  end

  add_index "student_activities", ["user_id", "tutor_user_id"], :name => "student_activities_user_id_key", :unique => true
  add_index "student_activities", ["user_id", "tutor_externaluser_id"], :name => "student_activities_user_id_key1", :unique => true

  create_table "studentroles", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "studentroles", ["name"], :name => "studentroles_name_key", :unique => true

  create_table "talkacceptances", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "talkacceptances", ["name"], :name => "talkacceptances_name_key", :unique => true

  create_table "talktypes", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "talktypes", ["name"], :name => "talktypes_name_key", :unique => true

  create_table "techproduct_financingsources", :force => true do |t|
    t.column "techproduct_id",     :integer,  :null => false
    t.column "financingsource_id", :integer,  :null => false
    t.column "amount",             :integer,  :null => false
    t.column "other",              :text
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  add_index "techproduct_financingsources", ["techproduct_id", "financingsource_id"], :name => "techproduct_financingsources_techproduct_id_key", :unique => true

  create_table "techproduct_versions", :force => true do |t|
    t.column "techproduct_id",       :integer
    t.column "techproductstatus_id", :integer,  :null => false
    t.column "release",              :text,     :null => false
    t.column "descr",                :text
    t.column "year",                 :integer,  :null => false
    t.column "month",                :integer
    t.column "isbn",                 :text
    t.column "other",                :text
    t.column "moduser_id",           :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  create_table "techproducts", :force => true do |t|
    t.column "title",              :text,     :null => false
    t.column "techproducttype_id", :integer
    t.column "authors",            :text,     :null => false
    t.column "descr",              :text
    t.column "institution_id",     :integer
    t.column "other",              :text
    t.column "moduser_id",         :integer
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
  end

  create_table "techproductstatuses", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "techproductstatuses", ["name"], :name => "techproductstatuses_name_key", :unique => true

  create_table "techproducttypes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "theses", :force => true do |t|
    t.column "title",                :text,     :null => false
    t.column "authors",              :text,     :null => false
    t.column "degree_id",            :integer,  :null => false
    t.column "institutioncareer_id", :integer,  :null => false
    t.column "thesisstatus_id",      :integer,  :null => false
    t.column "thesismodality_id",    :integer,  :null => false
    t.column "year",                 :integer,  :null => false
    t.column "month",                :integer
    t.column "other",                :text
    t.column "moduser_id",           :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  add_index "theses", ["title", "degree_id", "year"], :name => "theses_title_key", :unique => true

  create_table "thesis_jurors", :force => true do |t|
    t.column "user_id",       :integer
    t.column "thesis_id",     :integer,  :null => false
    t.column "roleinjury_id", :integer,  :null => false
    t.column "year",          :integer,  :null => false
    t.column "month",         :integer
    t.column "moduser_id",    :integer
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "thesis_jurors", ["user_id", "thesis_id", "roleinjury_id"], :name => "thesis_jurors_user_id_key", :unique => true

  create_table "thesislog", :force => true do |t|
    t.column "thesis_id",             :integer,  :null => false
    t.column "old_thesisstatuses_id", :integer,  :null => false
    t.column "year",                  :integer,  :null => false
    t.column "month",                 :integer
    t.column "moduser_id",            :integer
    t.column "created_on",            :datetime
    t.column "updated_on",            :datetime
  end

  create_table "thesismodalities", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "thesismodalities", ["name"], :name => "thesismodalities_name_key", :unique => true

  create_table "thesisstatuses", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "thesisstatuses", ["name"], :name => "thesisstatuses_name_key", :unique => true

  create_table "titlemodalities", :force => true do |t|
    t.column "name", :text, :null => false
  end

  add_index "titlemodalities", ["name"], :name => "titlemodalities_name_key", :unique => true

  create_table "user_adscriptions", :force => true do |t|
    t.column "jobposition_id", :integer,  :null => false
    t.column "adscription_id", :integer,  :null => false
    t.column "name",           :text
    t.column "descr",          :text
    t.column "startmonth",     :integer
    t.column "startyear",      :integer,  :null => false
    t.column "endmonth",       :integer
    t.column "endyear",        :integer
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  create_table "user_articles", :force => true do |t|
    t.column "user_id",      :integer,                    :null => false
    t.column "article_id",   :integer,                    :null => false
    t.column "ismainauthor", :boolean,  :default => true, :null => false
    t.column "other",        :text
    t.column "moduser_id",   :integer
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
  end

  create_table "user_conferencetalks", :force => true do |t|
    t.column "user_id",                 :integer,  :null => false
    t.column "conferencetalk_id",       :integer
    t.column "roleinconferencetalk_id", :integer,  :null => false
    t.column "comment",                 :text
    t.column "moduser_id",              :integer,  :null => false
    t.column "created_on",              :datetime
    t.column "updated_on",              :datetime
  end

  add_index "user_conferencetalks", ["user_id", "conferencetalk_id", "roleinconferencetalk_id"], :name => "user_conferencetalks_user_id_key", :unique => true

  create_table "user_courses", :force => true do |t|
    t.column "user_id",         :integer, :null => false
    t.column "course_id",       :integer
    t.column "roleincourse_id", :integer, :null => false
    t.column "other",           :text
  end

  create_table "user_genericworks", :force => true do |t|
    t.column "genericwork_id", :integer,  :null => false
    t.column "user_id",        :integer
    t.column "userrole_id",    :integer,  :null => false
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "user_genericworks", ["genericwork_id", "user_id", "userrole_id"], :name => "user_genericworks_genericwork_id_key", :unique => true

  create_table "user_grants", :force => true do |t|
    t.column "grant_id",   :integer, :null => false
    t.column "user_id",    :integer, :null => false
    t.column "descr",      :text
    t.column "startyear",  :integer, :null => false
    t.column "startmonth", :integer
    t.column "endyear",    :integer
    t.column "endmonth",   :integer
  end

  add_index "user_grants", ["grant_id", "user_id", "startyear", "startmonth"], :name => "user_grants_grant_id_key", :unique => true

  create_table "user_inproceedings", :force => true do |t|
    t.column "inproceeding_id", :integer,                    :null => false
    t.column "user_id",         :integer
    t.column "ismainauthor",    :boolean,  :default => true, :null => false
    t.column "moduser_id",      :integer
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  add_index "user_inproceedings", ["inproceeding_id", "user_id"], :name => "user_inproceedings_inproceeding_id_key", :unique => true

  create_table "user_journals", :force => true do |t|
    t.column "user_id",          :integer,  :null => false
    t.column "journal_id",       :integer,  :null => false
    t.column "roleinjournal_id", :integer,  :null => false
    t.column "startyear",        :integer,  :null => false
    t.column "startmonth",       :integer
    t.column "endyear",          :integer
    t.column "endmonth",         :integer
    t.column "other",            :text
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "user_journals", ["user_id", "journal_id", "roleinjournal_id"], :name => "user_journals_user_id_key", :unique => true

  create_table "user_languages", :force => true do |t|
    t.column "user_id",                  :integer,  :null => false
    t.column "language_id",              :integer,  :null => false
    t.column "spoken_languagelevel_id",  :integer,  :null => false
    t.column "written_languagelevel_id", :integer,  :null => false
    t.column "comment",                  :text
    t.column "moduser_id",               :integer
    t.column "created_on",               :datetime
    t.column "updated_on",               :datetime
  end

  add_index "user_languages", ["language_id", "spoken_languagelevel_id", "written_languagelevel_id"], :name => "user_languages_language_id_key", :unique => true

  create_table "user_newspaperarticles", :force => true do |t|
    t.column "user_id",             :integer,                    :null => false
    t.column "newspaperarticle_id", :integer,                    :null => false
    t.column "ismainauthor",        :boolean,  :default => true, :null => false
    t.column "other",               :text
    t.column "moduser_id",          :integer
    t.column "created_on",          :datetime
    t.column "updated_on",          :datetime
  end

  create_table "user_prizes", :force => true do |t|
    t.column "user_id",    :integer,  :null => false
    t.column "prize_id",   :integer,  :null => false
    t.column "year",       :integer,  :null => false
    t.column "month",      :integer
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "user_prizes", ["user_id", "prize_id", "year"], :name => "user_prizes_prize_id_key", :unique => true

  create_table "user_proceedings", :force => true do |t|
    t.column "proceeding_id",     :integer,  :null => false
    t.column "user_id",           :integer
    t.column "roleproceeding_id", :integer,  :null => false
    t.column "comment",           :text
    t.column "moduser_id",        :integer
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  add_index "user_proceedings", ["proceeding_id", "user_id", "roleproceeding_id"], :name => "user_proceedings_proceeding_id_key", :unique => true

  create_table "user_projects", :force => true do |t|
    t.column "project_id",       :integer,  :null => false
    t.column "user_id",          :integer
    t.column "roleinproject_id", :integer,  :null => false
    t.column "moduser_id",       :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
  end

  add_index "user_projects", ["project_id", "user_id", "roleinproject_id"], :name => "user_projects_project_id_key", :unique => true

  create_table "user_regularcourses", :force => true do |t|
    t.column "user_id",                :integer,  :null => false
    t.column "regularcourse_id",       :integer,  :null => false
    t.column "period_id",              :integer,  :null => false
    t.column "roleinregularcourse_id", :integer,  :null => false
    t.column "hoursxweek",             :integer
    t.column "moduser_id",             :integer
    t.column "created_on",             :datetime
    t.column "updated_on",             :datetime
  end

  add_index "user_regularcourses", ["user_id", "regularcourse_id", "period_id", "roleinregularcourse_id"], :name => "user_regularcourses_user_id_key", :unique => true

  create_table "user_researchlines", :force => true do |t|
    t.column "user_id",         :integer,  :null => false
    t.column "researchline_id", :integer,  :null => false
    t.column "moduser_id",      :integer
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  create_table "user_roleingroups", :force => true do |t|
    t.column "user_id",        :integer,  :null => false
    t.column "roleingroup_id", :integer,  :null => false
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "user_roleingroups", ["user_id", "roleingroup_id"], :name => "user_roleingroups_user_id_key", :unique => true

  create_table "user_schoolarships", :force => true do |t|
    t.column "schoolarship_id", :integer, :null => false
    t.column "user_id",         :integer, :null => false
    t.column "descr",           :text
    t.column "startyear",       :integer, :null => false
    t.column "startmonth",      :integer
    t.column "endyear",         :integer
    t.column "endmonth",        :integer
    t.column "amount",          :float
  end

  add_index "user_schoolarships", ["schoolarship_id", "user_id", "startyear", "startmonth"], :name => "user_schoolarships_schoolarship_id_key", :unique => true

  create_table "user_seminaries", :force => true do |t|
    t.column "seminary_id",       :integer,  :null => false
    t.column "user_id",           :integer,  :null => false
    t.column "roleinseminary_id", :integer,  :null => false
    t.column "moduser_id",        :integer,  :null => false
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  add_index "user_seminaries", ["seminary_id", "user_id", "roleinseminary_id"], :name => "user_seminaries_user_id_key", :unique => true

  create_table "user_skills", :force => true do |t|
    t.column "user_id",      :integer,  :null => false
    t.column "skilltype_id", :integer,  :null => false
    t.column "descr",        :text
    t.column "moduser_id",   :integer
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
  end

  create_table "user_stimulus", :force => true do |t|
    t.column "user_id",          :integer, :null => false
    t.column "stimuluslevel_id", :integer, :null => false
    t.column "startyear",        :integer, :null => false
    t.column "startmonth",       :integer
    t.column "endyear",          :integer
    t.column "endmonth",         :integer
  end

  create_table "user_techproducts", :force => true do |t|
    t.column "techproduct_id", :integer,  :null => false
    t.column "user_id",        :integer
    t.column "userrole_id",    :integer
    t.column "moduser_id",     :integer
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
  end

  add_index "user_techproducts", ["techproduct_id", "user_id", "userrole_id"], :name => "user_techproducts_techproduct_id_key", :unique => true

  create_table "user_theses", :force => true do |t|
    t.column "thesis_id",       :integer,  :null => false
    t.column "user_id",         :integer
    t.column "roleinthesis_id", :integer,  :null => false
    t.column "moduser_id",      :integer
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
  end

  add_index "user_theses", ["thesis_id", "user_id", "roleinthesis_id"], :name => "user_theses_thesis_id_key", :unique => true

  create_table "userconferences", :force => true do |t|
    t.column "conference_id",       :integer,  :null => false
    t.column "user_id",             :integer,  :null => false
    t.column "roleinconference_id", :integer,  :null => false
    t.column "moduser_id",          :integer,  :null => false
    t.column "created_on",          :datetime
    t.column "updated_on",          :datetime
  end

  add_index "userconferences", ["conference_id", "user_id", "roleinconference_id"], :name => "userconferences_user_id_key", :unique => true

  create_table "usercredits", :force => true do |t|
    t.column "user_id",              :integer
    t.column "internalusergive_id",  :integer
    t.column "externalusergive_id",  :integer
    t.column "usergive_is_internal", :boolean
    t.column "other",                :text
    t.column "year",                 :integer, :null => false
    t.column "month",                :integer
  end

  create_table "usercreditsarticles", :force => true do |t|
    t.column "usercredits_id", :integer, :null => false
    t.column "articles_id",    :integer, :null => false
  end

  add_index "usercreditsarticles", ["usercredits_id", "articles_id"], :name => "usercreditsarticles_usercredits_id_key", :unique => true

  create_table "usercreditsbooks", :force => true do |t|
    t.column "usercredits_id", :integer, :null => false
    t.column "books_id",       :integer, :null => false
  end

  add_index "usercreditsbooks", ["usercredits_id", "books_id"], :name => "usercreditsbooks_usercredits_id_key", :unique => true

  create_table "usercreditschapterinbooks", :force => true do |t|
    t.column "usercredits_id",    :integer, :null => false
    t.column "chapterinbooks_id", :integer, :null => false
  end

  add_index "usercreditschapterinbooks", ["usercredits_id", "chapterinbooks_id"], :name => "usercreditschapterinbooks_usercredits_id_key", :unique => true

  create_table "usercreditsconferencetalks", :force => true do |t|
    t.column "usercredits_id",     :integer, :null => false
    t.column "conferencetalks_id", :integer, :null => false
  end

  add_index "usercreditsconferencetalks", ["usercredits_id", "conferencetalks_id"], :name => "usercreditsconferencetalks_usercredits_id_key", :unique => true

  create_table "usercreditsgenericworks", :force => true do |t|
    t.column "usercredits_id",  :integer, :null => false
    t.column "genericworks_id", :integer, :null => false
  end

  add_index "usercreditsgenericworks", ["usercredits_id", "genericworks_id"], :name => "usercreditsgenericworks_usercredits_id_key", :unique => true

  create_table "userorgan", :force => true do |t|
    t.column "user_id",        :integer, :null => false
    t.column "organ_id",       :integer, :null => false
    t.column "roleinorgan_id", :integer, :null => false
    t.column "startyear",      :integer, :null => false
    t.column "startmonth",     :integer
    t.column "endyear",        :integer
    t.column "endmonth",       :integer
  end

  create_table "userrefereedpubs", :force => true do |t|
    t.column "refereedpubs_id",  :integer, :null => false
    t.column "user_is_internal", :boolean
    t.column "externaluser_id",  :integer
    t.column "internaluser_id",  :integer
  end

  add_index "userrefereedpubs", ["refereedpubs_id", "externaluser_id", "internaluser_id"], :name => "userrefereedpubs_refereedpubs_id_key", :unique => true

  create_table "userresearchgroups", :force => true do |t|
    t.column "researchgroup_id", :integer, :null => false
    t.column "year",             :integer, :null => false
    t.column "user_is_internal", :boolean
    t.column "externaluser_id",  :integer
    t.column "internaluser_id",  :integer
    t.column "moduser_id",       :integer
  end

  add_index "userresearchgroups", ["researchgroup_id", "internaluser_id"], :name => "userresearchgroups_researchgroup_id_key", :unique => true
  add_index "userresearchgroups", ["researchgroup_id", "externaluser_id"], :name => "userresearchgroups_researchgroup_id_key1", :unique => true

  create_table "userroles", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "userroles", ["name"], :name => "userroles_name_key", :unique => true

  create_table "users", :force => true do |t|
    t.column "login",         :text,                    :null => false
    t.column "passwd",        :text
    t.column "salt",          :text
    t.column "userstatus_id", :integer,  :default => 1, :null => false
    t.column "email",         :text
    t.column "homepage",      :text
    t.column "blog",          :text
    t.column "calendar",      :text
    t.column "pkcs7",         :text
    t.column "token",         :text
    t.column "token_expiry",  :datetime
    t.column "moduser_id",    :integer
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  add_index "users", ["id"], :name => "users_id_idx"
  add_index "users", ["login"], :name => "users_login_idx"
  add_index "users", ["login"], :name => "users_login_key", :unique => true

  create_table "users_logs", :force => true do |t|
    t.column "user_id",           :integer,  :null => false
    t.column "old_userstatus_id", :integer,  :null => false
    t.column "moduser_id",        :integer
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  create_table "usersstatuses_comments", :force => true do |t|
    t.column "user_id",       :integer,  :null => false
    t.column "userstatus_id", :integer,  :null => false
    t.column "comments",      :text,     :null => false
    t.column "moduser_id",    :integer,  :null => false
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  create_table "userstatuses", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "userstatuses", ["name"], :name => "userstatuses_name_key", :unique => true

  create_table "volumes", :force => true do |t|
    t.column "name",       :text,     :null => false
    t.column "moduser_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "volumes", ["name"], :name => "volumes_name_key", :unique => true

end
