INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en programas de servicio social, de becarios y otros', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Revisión, elaboración, registro y clasificación de proyectos de tesis', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en la integración de jurados para exámenes profesionales o de grado', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Aplicación de exámenes de conocimientos', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en el servicio bibliotecario', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en el desarrollo de la Mediateca ', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en búsquedas bibliográficas automatizadas  ', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en el seguimiento de proyectos de investigación ', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en búsqueda de financiamiento externo ', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en el manejo de programas de cómputo', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Evaluación de equipo de cómputo', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Instalación y mantenimiento preventivo y correctivo de equipo de cómputo', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo técnico a laboratorios de Cómputo ', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en el manejo de medios audiovisuales', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Evaluación de equipo audiovisual', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Instalación y mantenimiento preventivo y correctivo de equipo audiovisual', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Clasificación de videos', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Sonorización ', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Clasificación de fotografías', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo técnico en sala de videoconferencias ', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Dirección y/o coordinación de ediciones', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Recopilación de material para publicaciones', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Dictaminación de artículos', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Corrección de estilo', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Revisión y corrección de galeras', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Diseño en publicaciones', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Cuidado de edición', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Atención y asesoría de alumnos en trámites escolares', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en la elaboración de plantillas', 7);
INSERT INTO activitytypes (name, activitygroup_id) VALUES ('Apoyo en actividades colegiadas', 7);
