INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Estudios Básicos en Teoría Social', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Estudios de Opinión Pública', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Estudios en Administración Pública', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de estudios en Ciencias de la Comunicación', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Estudios Europeos', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Estudios Latinoamericanos', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Estudios Políticos', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Estudios Sociológicos', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Centro de Relaciones Internacionales', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Coordinación de Extensión Universitaria', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Coordinación de Informática', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Coordinación de Orientación Escolar', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Coordinación de Servicios Audiovisuales', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Coordinación de Servicios Bibliotecarios y Documentales', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Coordinación del Programa de Idiomas', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('División de Educación Continua y Vinculación', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('División de Estudios de Posgrado', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('División de Estudios Profesionales', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('División Sistema Universidad Abierta', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Programa de Investigación Social Aplicada', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Secretaría Administrativa', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Secretaría de Asuntos Estudiantiles', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Secretaría de Desarrollo Académico', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Secretaría de Personal Académico', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Secretaría de Planeación y Evaluación', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Secretaría de Servicios Escolares', '', '', 15, '');
INSERT INTO adscriptions (name, abbrev, descr, institution_id, administrative_key) VALUES ('Secretaría General', '', '', 15, '');
